/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rh.visao;

import dao.FechoPeriodoDao;
import entity.FechoPeriodo;
import java.util.Calendar;
import java.util.Date;
import java.util.Objects;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import static kitanda.util.CfMethodsSwing.resizeJButtonIcon;
import util.JPAEntityMannagerFactoryUtil;
import util.MetodosUtil;

/**
 *
 * @author Domingos Dala Vunge
 */
public class DataAberturaPeriodoVisao extends javax.swing.JDialog
{

    private static EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;
    private FechoPeriodoDao fechoPeriodoDao = new FechoPeriodoDao(emf);
    private Integer idUsuario = 0, idPeriodo = 0, idAnoEconomico;

    public DataAberturaPeriodoVisao(java.awt.Frame parent ,boolean modal ,int idUsuario ,int idAnoEconomico ,int idPeriodo)
    {
        super(parent ,modal);
        initComponents();  
        setLocationRelativeTo(null);
        this.idAnoEconomico = idAnoEconomico;
        this.idPeriodo = idPeriodo;
        this.idUsuario = idUsuario;
        confirguracao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        dcDataAbertura = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        dcDataAbertura.setDateFormatString("dd-MM-yyyy");
        dcDataAbertura.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel16.setText("(Dia-Mês-Ano)");

        btnConfirmar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnSair.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dcDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSairActionPerformed
    {//GEN-HEADEREND:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConfirmarActionPerformed
    {//GEN-HEADEREND:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        confirmarData();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals(info.getName()) )
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger(DataAberturaPeriodoVisao.class.getName()).log(java.util.logging.Level.SEVERE ,null ,ex);
        } catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger(DataAberturaPeriodoVisao.class.getName()).log(java.util.logging.Level.SEVERE ,null ,ex);
        } catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger(DataAberturaPeriodoVisao.class.getName()).log(java.util.logging.Level.SEVERE ,null ,ex);
        } catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger(DataAberturaPeriodoVisao.class.getName()).log(java.util.logging.Level.SEVERE ,null ,ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                DataAberturaPeriodoVisao dialog = new DataAberturaPeriodoVisao(new javax.swing.JFrame() ,true ,15 ,1 ,1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnSair;
    public static com.toedter.calendar.JDateChooser dcDataAbertura;
    private javax.swing.JLabel jLabel16;
    // End of variables declaration//GEN-END:variables

    private void confirguracao()
    {
        resizeJButtonIcon(16 ,16 ,getClass().getResource("/imagens/confirmacao.png") ,btnConfirmar);
        resizeJButtonIcon(16 ,16 ,getClass().getResource("/imagens/SAIR/Logout.png") ,btnSair);

        //dcDataAbertura.setMinSelectableDate(new Date());
        try
        {
            setMinimuDataAbertura();

        } catch ( Exception e )
        {
            e.printStackTrace();
        }

    }

    private void setMinimuDataAbertura()
    {

        FechoPeriodo periodoAnterior;

        System.out.println("ID ANO ECONOMICO: " + this.idAnoEconomico);
        System.out.println("ID PERIODO: " + this.idPeriodo);
        periodoAnterior = fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido(idAnoEconomico ,idPeriodo - 1);

        if ( !Objects.isNull(periodoAnterior) )
        {

            Calendar calendar = Calendar.getInstance();
            calendar.setTime(periodoAnterior.getDataFecho());
            calendar.add(Calendar.DATE ,1);
            System.out.println("Data Minima: " + MetodosUtil.getDataBanco(calendar.getTime()));
            dcDataAbertura.setMinSelectableDate(calendar.getTime());
            dcDataAbertura.setDate(calendar.getTime());
            //dcDataAbertura.setMinSelectableDate(new Date());

        }
//        else 
//        {
//            dcDataAbertura.setMinSelectableDate(null);
//        }

    }

    private void confirmarData()
    {
        int opcao = JOptionPane.showConfirmDialog(null ,"Caro usuário pretendes abrir mesmo este período?");

        if ( opcao == JOptionPane.YES_OPTION )
        {
            dispose();
            DefinicoesVisao.procedimentoAbrirPeriodo(idAnoEconomico ,idPeriodo ,dcDataAbertura.getDate());
        }

    }

}
