/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rh.visao;


import java.sql.Connection;
import dao.AnoDao;
import dao.FechoPeriodoDao;
import dao.MesRhDao;
import dao.UsuarioDao;
import java.util.Vector;
import entity.FechoPeriodo;
import java.util.Date;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static kitanda.util.CfMethodsSwing.resizeJButtonIcon;
import util.BDConexao;
import util.DVML;
import static util.DVML.*;
import util.JPAEntityMannagerFactoryUtil;
import util.MetodosUtil;

/**
 *
 * @author Domingos Dala Vunge
 */
public final class DefinicoesVisao extends javax.swing.JFrame implements Runnable
{

    private static EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;
    public static FechoPeriodoDao fechoPeriodoDao = new FechoPeriodoDao( emf );
    public static FechoPeriodo fechoPeriodo = null;
    public static UsuarioDao usuarioDao = new UsuarioDao( emf );
    public static MesRhDao mesRhDao = new MesRhDao( emf );
    public static AnoDao anoDao = new AnoDao( emf );
    private static BDConexao conexao;
    private static DefaultTableModel modelo;
    public static Date data_fecho_periodo = null;
    public static int idUsuario = 0;
    public Thread t;
    private int idEmpresa = 0, posicao_periodo_actual = -1;
    private static final int largura = 20;
    private static final int altura = 24;
    private static final String path_open = "/imagens/open.png";
    private static final String path_close = "/imagens/close.png";
    private static final String path_eliminar = "/imagens/eliminar_32x32.png";

    boolean estado = false;

    public DefinicoesVisao( int idUsuario, int idEmpresa, BDConexao conexao )
    {
        initComponents();
        setLocationRelativeTo( null );
        t = new Thread( this );
        t.start();
        this.idUsuario = idUsuario;
        this.idEmpresa = idEmpresa;
        this.conexao = conexao;
        setComBoBox();
        resetPeriodos();
        desenharPeriodos();

        //GestaoPeriodoUtil.construirTabela(fechoPeriodoDao.getFonteDados(getIdAno()));
        //resetPeriodos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lb_seja_bem_vindo1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        painelJaneiro = new javax.swing.JPanel();
        btnOpenJaneiro = new javax.swing.JButton();
        btnCloseJaneiro = new javax.swing.JButton();
        btnEliminarJaneiro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbTitleJaneiro = new javax.swing.JLabel();
        painelFevereiro = new javax.swing.JPanel();
        btnOpenFevereiro = new javax.swing.JButton();
        btnCloseFevereiro = new javax.swing.JButton();
        btnEliminarFevereiro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbTitleFevereiro = new javax.swing.JLabel();
        cmbAnoEconomico = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        painelMarco = new javax.swing.JPanel();
        btnOpenMarco = new javax.swing.JButton();
        btnCloseMarco = new javax.swing.JButton();
        btnEliminarMarco = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbTitleFevereiro1 = new javax.swing.JLabel();
        painelAbril = new javax.swing.JPanel();
        btnOpenAbril = new javax.swing.JButton();
        btnCloseAbril = new javax.swing.JButton();
        btnEliminarAbril = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbTitleFevereiro2 = new javax.swing.JLabel();
        painelMaio = new javax.swing.JPanel();
        btnOpenMaio = new javax.swing.JButton();
        btnCloseMaio = new javax.swing.JButton();
        btnEliminarMaio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbTitleJaneiro1 = new javax.swing.JLabel();
        painelJunho = new javax.swing.JPanel();
        btnOpenJunho = new javax.swing.JButton();
        btnCloseJunho = new javax.swing.JButton();
        btnEliminarJunho = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbTitleFevereiro3 = new javax.swing.JLabel();
        painelJulho = new javax.swing.JPanel();
        btnOpenJulho = new javax.swing.JButton();
        btnCloseJulho = new javax.swing.JButton();
        btnEliminarJulho = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbTitleFevereiro4 = new javax.swing.JLabel();
        painelAgosto = new javax.swing.JPanel();
        btnOpenAgosto = new javax.swing.JButton();
        btnCloseAgosto = new javax.swing.JButton();
        btnEliminarAgosto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lbTitleFevereiro5 = new javax.swing.JLabel();
        painelSetembro = new javax.swing.JPanel();
        btnOpenSetembro = new javax.swing.JButton();
        btnCloseSetembro = new javax.swing.JButton();
        btnEliminarSetembro = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lbTitleJaneiro2 = new javax.swing.JLabel();
        painelOutubro = new javax.swing.JPanel();
        btnOpenOutubro = new javax.swing.JButton();
        btnCloseOutubro = new javax.swing.JButton();
        btnEliminarOutubro = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lbTitleFevereiro6 = new javax.swing.JLabel();
        painelNovembro = new javax.swing.JPanel();
        btnOpenNovembro = new javax.swing.JButton();
        btnCloseNovembro = new javax.swing.JButton();
        btnEliminarNovembro = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lbTitleFevereiro7 = new javax.swing.JLabel();
        painelDezembro = new javax.swing.JPanel();
        btnOpenDezembro = new javax.swing.JButton();
        btnCloseDezembro = new javax.swing.JButton();
        btnEliminarDezembro = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lbTitleFevereiro8 = new javax.swing.JLabel();
        lbEmpresa = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DEFINIÇÕES");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lb_seja_bem_vindo1.setFont(new java.awt.Font("Times New Roman", 3, 10)); // NOI18N
        lb_seja_bem_vindo1.setText("EMPRESA:");

        painelJaneiro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelJaneiro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenJaneiro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenJaneiroMouseClicked(evt);
            }
        });
        btnOpenJaneiro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpenJaneiroActionPerformed(evt);
            }
        });
        painelJaneiro.add(btnOpenJaneiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseJaneiro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseJaneiroMouseClicked(evt);
            }
        });
        btnCloseJaneiro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseJaneiroActionPerformed(evt);
            }
        });
        painelJaneiro.add(btnCloseJaneiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarJaneiro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarJaneiroMouseClicked(evt);
            }
        });
        painelJaneiro.add(btnEliminarJaneiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Janeiro");
        jLabel3.setOpaque(true);
        painelJaneiro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 172, -1));

        lbTitleJaneiro.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleJaneiro.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleJaneiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleJaneiro.setText("1");
        lbTitleJaneiro.setOpaque(true);
        painelJaneiro.add(lbTitleJaneiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 172, -1));

        painelFevereiro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelFevereiro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenFevereiro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenFevereiroMouseClicked(evt);
            }
        });
        painelFevereiro.add(btnOpenFevereiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseFevereiro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseFevereiroMouseClicked(evt);
            }
        });
        btnCloseFevereiro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseFevereiroActionPerformed(evt);
            }
        });
        painelFevereiro.add(btnCloseFevereiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarFevereiro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarFevereiroMouseClicked(evt);
            }
        });
        painelFevereiro.add(btnEliminarFevereiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fevereiro");
        jLabel5.setOpaque(true);
        painelFevereiro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 170, -1));

        lbTitleFevereiro.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleFevereiro.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleFevereiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleFevereiro.setText("2");
        lbTitleFevereiro.setOpaque(true);
        painelFevereiro.add(lbTitleFevereiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 170, -1));

        cmbAnoEconomico.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
        cmbAnoEconomico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbAnoEconomicoActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Lucida Sans Typewriter", 2, 13)); // NOI18N
        jLabel21.setText("Ano");

        painelMarco.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelMarco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenMarco.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenMarcoMouseClicked(evt);
            }
        });
        painelMarco.add(btnOpenMarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseMarco.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseMarcoMouseClicked(evt);
            }
        });
        btnCloseMarco.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseMarcoActionPerformed(evt);
            }
        });
        painelMarco.add(btnCloseMarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarMarco.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarMarcoMouseClicked(evt);
            }
        });
        painelMarco.add(btnEliminarMarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Março");
        jLabel6.setOpaque(true);
        painelMarco.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 170, -1));

        lbTitleFevereiro1.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleFevereiro1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleFevereiro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleFevereiro1.setText("3");
        lbTitleFevereiro1.setOpaque(true);
        painelMarco.add(lbTitleFevereiro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 170, -1));

        painelAbril.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelAbril.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenAbril.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenAbrilMouseClicked(evt);
            }
        });
        painelAbril.add(btnOpenAbril, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseAbril.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseAbrilMouseClicked(evt);
            }
        });
        painelAbril.add(btnCloseAbril, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarAbril.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarAbrilMouseClicked(evt);
            }
        });
        btnEliminarAbril.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarAbrilActionPerformed(evt);
            }
        });
        painelAbril.add(btnEliminarAbril, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Abril");
        jLabel7.setOpaque(true);
        painelAbril.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 170, -1));

        lbTitleFevereiro2.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleFevereiro2.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleFevereiro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleFevereiro2.setText("4");
        lbTitleFevereiro2.setOpaque(true);
        painelAbril.add(lbTitleFevereiro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 170, -1));

        painelMaio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelMaio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenMaio.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenMaioMouseClicked(evt);
            }
        });
        btnOpenMaio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpenMaioActionPerformed(evt);
            }
        });
        painelMaio.add(btnOpenMaio, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseMaio.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseMaioMouseClicked(evt);
            }
        });
        btnCloseMaio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseMaioActionPerformed(evt);
            }
        });
        painelMaio.add(btnCloseMaio, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarMaio.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarMaioMouseClicked(evt);
            }
        });
        painelMaio.add(btnEliminarMaio, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Maio");
        jLabel4.setOpaque(true);
        painelMaio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 172, -1));

        lbTitleJaneiro1.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleJaneiro1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleJaneiro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleJaneiro1.setText("5");
        lbTitleJaneiro1.setOpaque(true);
        painelMaio.add(lbTitleJaneiro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 172, -1));

        painelJunho.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelJunho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenJunho.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenJunhoMouseClicked(evt);
            }
        });
        painelJunho.add(btnOpenJunho, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseJunho.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseJunhoMouseClicked(evt);
            }
        });
        painelJunho.add(btnCloseJunho, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarJunho.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarJunhoMouseClicked(evt);
            }
        });
        painelJunho.add(btnEliminarJunho, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Junho");
        jLabel8.setOpaque(true);
        painelJunho.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 170, -1));

        lbTitleFevereiro3.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleFevereiro3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleFevereiro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleFevereiro3.setText("6");
        lbTitleFevereiro3.setOpaque(true);
        painelJunho.add(lbTitleFevereiro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 170, -1));

        painelJulho.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelJulho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenJulho.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenJulhoMouseClicked(evt);
            }
        });
        btnOpenJulho.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpenJulhoActionPerformed(evt);
            }
        });
        painelJulho.add(btnOpenJulho, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseJulho.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseJulhoMouseClicked(evt);
            }
        });
        painelJulho.add(btnCloseJulho, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarJulho.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarJulhoMouseClicked(evt);
            }
        });
        painelJulho.add(btnEliminarJulho, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Julho");
        jLabel9.setOpaque(true);
        painelJulho.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 170, -1));

        lbTitleFevereiro4.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleFevereiro4.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleFevereiro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleFevereiro4.setText("7");
        lbTitleFevereiro4.setOpaque(true);
        painelJulho.add(lbTitleFevereiro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 170, -1));

        painelAgosto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelAgosto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenAgosto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenAgostoMouseClicked(evt);
            }
        });
        btnOpenAgosto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpenAgostoActionPerformed(evt);
            }
        });
        painelAgosto.add(btnOpenAgosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseAgosto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseAgostoMouseClicked(evt);
            }
        });
        painelAgosto.add(btnCloseAgosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarAgosto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarAgostoMouseClicked(evt);
            }
        });
        painelAgosto.add(btnEliminarAgosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Agosto");
        jLabel10.setOpaque(true);
        painelAgosto.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 170, -1));

        lbTitleFevereiro5.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleFevereiro5.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleFevereiro5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleFevereiro5.setText("8");
        lbTitleFevereiro5.setOpaque(true);
        painelAgosto.add(lbTitleFevereiro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 170, -1));

        painelSetembro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelSetembro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenSetembro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenSetembroMouseClicked(evt);
            }
        });
        btnOpenSetembro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpenSetembroActionPerformed(evt);
            }
        });
        painelSetembro.add(btnOpenSetembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseSetembro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseSetembroMouseClicked(evt);
            }
        });
        btnCloseSetembro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseSetembroActionPerformed(evt);
            }
        });
        painelSetembro.add(btnCloseSetembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarSetembro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarSetembroMouseClicked(evt);
            }
        });
        btnEliminarSetembro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarSetembroActionPerformed(evt);
            }
        });
        painelSetembro.add(btnEliminarSetembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Setembro");
        jLabel11.setOpaque(true);
        painelSetembro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 172, -1));

        lbTitleJaneiro2.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleJaneiro2.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleJaneiro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleJaneiro2.setText("9");
        lbTitleJaneiro2.setOpaque(true);
        painelSetembro.add(lbTitleJaneiro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 172, -1));

        painelOutubro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelOutubro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenOutubro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenOutubroMouseClicked(evt);
            }
        });
        painelOutubro.add(btnOpenOutubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseOutubro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseOutubroMouseClicked(evt);
            }
        });
        painelOutubro.add(btnCloseOutubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarOutubro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarOutubroMouseClicked(evt);
            }
        });
        painelOutubro.add(btnEliminarOutubro, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Outubro");
        jLabel12.setOpaque(true);
        painelOutubro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 170, -1));

        lbTitleFevereiro6.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleFevereiro6.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleFevereiro6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleFevereiro6.setText("10");
        lbTitleFevereiro6.setOpaque(true);
        painelOutubro.add(lbTitleFevereiro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 170, -1));

        painelNovembro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelNovembro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenNovembro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenNovembroMouseClicked(evt);
            }
        });
        btnOpenNovembro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpenNovembroActionPerformed(evt);
            }
        });
        painelNovembro.add(btnOpenNovembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseNovembro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseNovembroMouseClicked(evt);
            }
        });
        btnCloseNovembro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseNovembroActionPerformed(evt);
            }
        });
        painelNovembro.add(btnCloseNovembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarNovembro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarNovembroMouseClicked(evt);
            }
        });
        painelNovembro.add(btnEliminarNovembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Novembro");
        jLabel13.setOpaque(true);
        painelNovembro.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 170, -1));

        lbTitleFevereiro7.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleFevereiro7.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleFevereiro7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleFevereiro7.setText("11");
        lbTitleFevereiro7.setOpaque(true);
        painelNovembro.add(lbTitleFevereiro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 170, -1));

        painelDezembro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelDezembro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenDezembro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOpenDezembroMouseClicked(evt);
            }
        });
        btnOpenDezembro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpenDezembroActionPerformed(evt);
            }
        });
        painelDezembro.add(btnOpenDezembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 50, 50));

        btnCloseDezembro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCloseDezembroMouseClicked(evt);
            }
        });
        painelDezembro.add(btnCloseDezembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 76, 51, 50));

        btnEliminarDezembro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminarDezembroMouseClicked(evt);
            }
        });
        btnEliminarDezembro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarDezembroActionPerformed(evt);
            }
        });
        painelDezembro.add(btnEliminarDezembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 76, 47, 50));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Dezembro");
        jLabel14.setOpaque(true);
        painelDezembro.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 170, -1));

        lbTitleFevereiro8.setBackground(new java.awt.Color(153, 153, 153));
        lbTitleFevereiro8.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitleFevereiro8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitleFevereiro8.setText("12");
        lbTitleFevereiro8.setOpaque(true);
        painelDezembro.add(lbTitleFevereiro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 170, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(painelJaneiro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painelFevereiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelMarco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelAbril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAnoEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(painelMaio, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painelJunho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelJulho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelAgosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(painelSetembro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painelOutubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelNovembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelDezembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAnoEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelFevereiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelJaneiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelMarco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelAbril, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelJunho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelMaio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelJulho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelAgosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelOutubro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelSetembro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelNovembro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDezembro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Período", jPanel6);

        lbEmpresa.setFont(new java.awt.Font("Times New Roman", 3, 10)); // NOI18N
        lbEmpresa.setText("BEM VINDO!....");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOUT - CINZA/Logout-32x32.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logout 32x32.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_seja_bem_vindo1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(186, 186, 186))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_seja_bem_vindo1)
                        .addComponent(lbEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbAnoEconomicoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbAnoEconomicoActionPerformed
    {//GEN-HEADEREND:event_cmbAnoEconomicoActionPerformed
        // TODO add your handling code here:
        resetPeriodos();
        desenharPeriodos();
    }//GEN-LAST:event_cmbAnoEconomicoActionPerformed

    private void btnOpenJaneiroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenJaneiroActionPerformed
    {//GEN-HEADEREND:event_btnOpenJaneiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenJaneiroActionPerformed

    private void btnOpenJaneiroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenJaneiroMouseClicked
    {//GEN-HEADEREND:event_btnOpenJaneiroMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), JANEIRO ).show();
        resetMes( painelJaneiro, btnOpenJaneiro, btnCloseJaneiro, btnEliminarJaneiro );
    }//GEN-LAST:event_btnOpenJaneiroMouseClicked

    private void btnCloseJaneiroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseJaneiroActionPerformed
    {//GEN-HEADEREND:event_btnCloseJaneiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseJaneiroActionPerformed

    private void btnCloseJaneiroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseJaneiroMouseClicked
    {//GEN-HEADEREND:event_btnCloseJaneiroMouseClicked
        // TODO add your handling code here:
        new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), JANEIRO ).show();
    }//GEN-LAST:event_btnCloseJaneiroMouseClicked

    private void btnOpenFevereiroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenFevereiroMouseClicked
    {//GEN-HEADEREND:event_btnOpenFevereiroMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), FEVEREIRO ).show();
        resetMes( painelFevereiro, btnOpenFevereiro, btnCloseFevereiro, btnEliminarFevereiro );
    }//GEN-LAST:event_btnOpenFevereiroMouseClicked

    private void btnOpenMarcoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenMarcoMouseClicked
    {//GEN-HEADEREND:event_btnOpenMarcoMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), MARCO ).show();
        resetMes( painelMarco, btnOpenMarco, btnCloseMarco, btnEliminarMarco );
    }//GEN-LAST:event_btnOpenMarcoMouseClicked

    private void btnCloseFevereiroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseFevereiroMouseClicked
    {//GEN-HEADEREND:event_btnCloseFevereiroMouseClicked
        // TODO add your handling code here:
        new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), FEVEREIRO ).show();
//       
//            procedimentoFechar( FEVEREIRO );
//            resetMes( painelFevereiro, btnOpenFevereiro, btnCloseFevereiro, btnEliminarFevereiro );
//        

    }//GEN-LAST:event_btnCloseFevereiroMouseClicked

    private void btnCloseMarcoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseMarcoMouseClicked
    {//GEN-HEADEREND:event_btnCloseMarcoMouseClicked
        // TODO add your handling code here:
        new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), MARCO ).show();
    }//GEN-LAST:event_btnCloseMarcoMouseClicked

    private void btnOpenAbrilMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenAbrilMouseClicked
    {//GEN-HEADEREND:event_btnOpenAbrilMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), ABRIL ).show();
        resetMes( painelAbril, btnOpenAbril, btnCloseAbril, btnEliminarAbril );
    }//GEN-LAST:event_btnOpenAbrilMouseClicked

    private void btnCloseAbrilMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseAbrilMouseClicked
    {//GEN-HEADEREND:event_btnCloseAbrilMouseClicked
        // TODO add your handling code here:
         new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), ABRIL ).show();
    }//GEN-LAST:event_btnCloseAbrilMouseClicked

    private void btnOpenMaioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenMaioMouseClicked
    {//GEN-HEADEREND:event_btnOpenMaioMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), MAIO ).show();
        resetMes( painelMaio, btnOpenMaio, btnCloseMaio, btnEliminarMaio );
    }//GEN-LAST:event_btnOpenMaioMouseClicked

    private void btnOpenMaioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenMaioActionPerformed
    {//GEN-HEADEREND:event_btnOpenMaioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenMaioActionPerformed

    private void btnCloseMaioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseMaioMouseClicked
    {//GEN-HEADEREND:event_btnCloseMaioMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), MAIO ).show();
    }//GEN-LAST:event_btnCloseMaioMouseClicked

    private void btnCloseMaioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseMaioActionPerformed
    {//GEN-HEADEREND:event_btnCloseMaioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMaioActionPerformed

    private void btnOpenJunhoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenJunhoMouseClicked
    {//GEN-HEADEREND:event_btnOpenJunhoMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), JUNHO ).show();
        resetMes( painelJunho, btnOpenJunho, btnCloseJunho, btnEliminarJunho );
    }//GEN-LAST:event_btnOpenJunhoMouseClicked

    private void btnCloseJunhoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseJunhoMouseClicked
    {//GEN-HEADEREND:event_btnCloseJunhoMouseClicked
        // TODO add your handling code here:
         new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), JUNHO ).show();
    }//GEN-LAST:event_btnCloseJunhoMouseClicked

    private void btnOpenJulhoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenJulhoMouseClicked
    {//GEN-HEADEREND:event_btnOpenJulhoMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), JULHO ).show();
        resetMes( painelJulho, btnOpenJulho, btnCloseJulho, btnEliminarJulho );
    }//GEN-LAST:event_btnOpenJulhoMouseClicked

    private void btnCloseJulhoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseJulhoMouseClicked
    {//GEN-HEADEREND:event_btnCloseJulhoMouseClicked
        // TODO add your handling code here:
         new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), JULHO ).show();
    }//GEN-LAST:event_btnCloseJulhoMouseClicked

    private void btnOpenAgostoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenAgostoMouseClicked
    {//GEN-HEADEREND:event_btnOpenAgostoMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), AGOSTO ).show();
        resetMes( painelAgosto, btnOpenAgosto, btnCloseAgosto, btnEliminarAgosto );
    }//GEN-LAST:event_btnOpenAgostoMouseClicked

    private void btnCloseAgostoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseAgostoMouseClicked
    {//GEN-HEADEREND:event_btnCloseAgostoMouseClicked
        // TODO add your handling code here:
         new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), AGOSTO ).show();
    }//GEN-LAST:event_btnCloseAgostoMouseClicked

    private void btnEliminarAbrilActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarAbrilActionPerformed
    {//GEN-HEADEREND:event_btnEliminarAbrilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarAbrilActionPerformed

    private void btnOpenJulhoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenJulhoActionPerformed
    {//GEN-HEADEREND:event_btnOpenJulhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenJulhoActionPerformed

    private void btnOpenAgostoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenAgostoActionPerformed
    {//GEN-HEADEREND:event_btnOpenAgostoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnOpenAgostoActionPerformed

    private void btnOpenSetembroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenSetembroMouseClicked
    {//GEN-HEADEREND:event_btnOpenSetembroMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), SETEMBRO ).show();
        resetMes( painelSetembro, btnOpenSetembro, btnCloseSetembro, btnEliminarSetembro );
    }//GEN-LAST:event_btnOpenSetembroMouseClicked

    private void btnOpenSetembroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenSetembroActionPerformed
    {//GEN-HEADEREND:event_btnOpenSetembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenSetembroActionPerformed

    private void btnCloseSetembroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseSetembroMouseClicked
    {//GEN-HEADEREND:event_btnCloseSetembroMouseClicked
        // TODO add your handling code here:
         new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), SETEMBRO ).show();
    }//GEN-LAST:event_btnCloseSetembroMouseClicked

    private void btnCloseSetembroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseSetembroActionPerformed
    {//GEN-HEADEREND:event_btnCloseSetembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseSetembroActionPerformed

    private void btnOpenOutubroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenOutubroMouseClicked
    {//GEN-HEADEREND:event_btnOpenOutubroMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), OUTUBRO ).show();
        resetMes( painelOutubro, btnOpenOutubro, btnCloseOutubro, btnEliminarOutubro );
    }//GEN-LAST:event_btnOpenOutubroMouseClicked

    private void btnCloseOutubroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseOutubroMouseClicked
    {//GEN-HEADEREND:event_btnCloseOutubroMouseClicked
        // TODO add your handling code here:

         new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), OUTUBRO ).show();
    }//GEN-LAST:event_btnCloseOutubroMouseClicked

    private void btnOpenNovembroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenNovembroMouseClicked
    {//GEN-HEADEREND:event_btnOpenNovembroMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), NOVEMBRO ).show();
        resetMes( painelNovembro, btnOpenNovembro, btnCloseNovembro, btnEliminarNovembro );
    }//GEN-LAST:event_btnOpenNovembroMouseClicked

    private void btnOpenNovembroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenNovembroActionPerformed
    {//GEN-HEADEREND:event_btnOpenNovembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenNovembroActionPerformed

    private void btnCloseNovembroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseNovembroMouseClicked
    {//GEN-HEADEREND:event_btnCloseNovembroMouseClicked
        // TODO add your handling code here:
        new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), NOVEMBRO ).show();
    }//GEN-LAST:event_btnCloseNovembroMouseClicked

    private void btnOpenDezembroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOpenDezembroMouseClicked
    {//GEN-HEADEREND:event_btnOpenDezembroMouseClicked
        // TODO add your handling code here:
        new DataAberturaPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), DEZEMBRO ).show();
        resetMes( painelDezembro, btnOpenDezembro, btnCloseDezembro, btnEliminarDezembro );
    }//GEN-LAST:event_btnOpenDezembroMouseClicked

    private void btnOpenDezembroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpenDezembroActionPerformed
    {//GEN-HEADEREND:event_btnOpenDezembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenDezembroActionPerformed

    private void btnCloseDezembroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCloseDezembroMouseClicked
    {//GEN-HEADEREND:event_btnCloseDezembroMouseClicked
        // TODO add your handling code here:
          new DataFechoPeriodoVisao( this, estado, idUsuario, getIdAnoEconomico(), FEVEREIRO ).show();
    }//GEN-LAST:event_btnCloseDezembroMouseClicked

    private void btnEliminarSetembroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarSetembroActionPerformed
    {//GEN-HEADEREND:event_btnEliminarSetembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSetembroActionPerformed

    private void btnCloseNovembroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseNovembroActionPerformed
    {//GEN-HEADEREND:event_btnCloseNovembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseNovembroActionPerformed

    private void btnEliminarDezembroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarDezembroActionPerformed
    {//GEN-HEADEREND:event_btnEliminarDezembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarDezembroActionPerformed

    private void btnEliminarJaneiroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarJaneiroMouseClicked
    {//GEN-HEADEREND:event_btnEliminarJaneiroMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( JANEIRO );
    }//GEN-LAST:event_btnEliminarJaneiroMouseClicked

    private void btnEliminarFevereiroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarFevereiroMouseClicked
    {//GEN-HEADEREND:event_btnEliminarFevereiroMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( FEVEREIRO );
    }//GEN-LAST:event_btnEliminarFevereiroMouseClicked

    private void btnEliminarMarcoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarMarcoMouseClicked
    {//GEN-HEADEREND:event_btnEliminarMarcoMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( MARCO );
    }//GEN-LAST:event_btnEliminarMarcoMouseClicked

    private void btnEliminarAbrilMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarAbrilMouseClicked
    {//GEN-HEADEREND:event_btnEliminarAbrilMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( ABRIL );
    }//GEN-LAST:event_btnEliminarAbrilMouseClicked

    private void btnEliminarMaioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarMaioMouseClicked
    {//GEN-HEADEREND:event_btnEliminarMaioMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( MAIO );
    }//GEN-LAST:event_btnEliminarMaioMouseClicked

    private void btnEliminarJunhoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarJunhoMouseClicked
    {//GEN-HEADEREND:event_btnEliminarJunhoMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( JUNHO );
    }//GEN-LAST:event_btnEliminarJunhoMouseClicked

    private void btnEliminarJulhoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarJulhoMouseClicked
    {//GEN-HEADEREND:event_btnEliminarJulhoMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( JULHO );
    }//GEN-LAST:event_btnEliminarJulhoMouseClicked

    private void btnEliminarAgostoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarAgostoMouseClicked
    {//GEN-HEADEREND:event_btnEliminarAgostoMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( AGOSTO );
    }//GEN-LAST:event_btnEliminarAgostoMouseClicked

    private void btnEliminarSetembroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarSetembroMouseClicked
    {//GEN-HEADEREND:event_btnEliminarSetembroMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( SETEMBRO );
    }//GEN-LAST:event_btnEliminarSetembroMouseClicked

    private void btnEliminarOutubroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarOutubroMouseClicked
    {//GEN-HEADEREND:event_btnEliminarOutubroMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( OUTUBRO );
    }//GEN-LAST:event_btnEliminarOutubroMouseClicked

    private void btnEliminarNovembroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarNovembroMouseClicked
    {//GEN-HEADEREND:event_btnEliminarNovembroMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( NOVEMBRO );
    }//GEN-LAST:event_btnEliminarNovembroMouseClicked

    private void btnEliminarDezembroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminarDezembroMouseClicked
    {//GEN-HEADEREND:event_btnEliminarDezembroMouseClicked
        // TODO add your handling code here:
        procedimentoEliminar( DEZEMBRO );
    }//GEN-LAST:event_btnEliminarDezembroMouseClicked

    private void btnCloseFevereiroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseFevereiroActionPerformed
    {//GEN-HEADEREND:event_btnCloseFevereiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseFevereiroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCloseMarcoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseMarcoActionPerformed
    {//GEN-HEADEREND:event_btnCloseMarcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMarcoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( DefinicoesVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( DefinicoesVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( DefinicoesVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( DefinicoesVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {

                new DefinicoesVisao( 15, 2, BDConexao.getInstancia() ).setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCloseAbril;
    public static javax.swing.JButton btnCloseAgosto;
    public static javax.swing.JButton btnCloseDezembro;
    public static javax.swing.JButton btnCloseFevereiro;
    public static javax.swing.JButton btnCloseJaneiro;
    public static javax.swing.JButton btnCloseJulho;
    public static javax.swing.JButton btnCloseJunho;
    public static javax.swing.JButton btnCloseMaio;
    public static javax.swing.JButton btnCloseMarco;
    public static javax.swing.JButton btnCloseNovembro;
    public static javax.swing.JButton btnCloseOutubro;
    public static javax.swing.JButton btnCloseSetembro;
    public static javax.swing.JButton btnEliminarAbril;
    public static javax.swing.JButton btnEliminarAgosto;
    public static javax.swing.JButton btnEliminarDezembro;
    public static javax.swing.JButton btnEliminarFevereiro;
    public static javax.swing.JButton btnEliminarJaneiro;
    public static javax.swing.JButton btnEliminarJulho;
    public static javax.swing.JButton btnEliminarJunho;
    public static javax.swing.JButton btnEliminarMaio;
    public static javax.swing.JButton btnEliminarMarco;
    public static javax.swing.JButton btnEliminarNovembro;
    public static javax.swing.JButton btnEliminarOutubro;
    public static javax.swing.JButton btnEliminarSetembro;
    public static javax.swing.JButton btnOpenAbril;
    public static javax.swing.JButton btnOpenAgosto;
    public static javax.swing.JButton btnOpenDezembro;
    public static javax.swing.JButton btnOpenFevereiro;
    public static javax.swing.JButton btnOpenJaneiro;
    public static javax.swing.JButton btnOpenJulho;
    public static javax.swing.JButton btnOpenJunho;
    public static javax.swing.JButton btnOpenMaio;
    public static javax.swing.JButton btnOpenMarco;
    public static javax.swing.JButton btnOpenNovembro;
    public static javax.swing.JButton btnOpenOutubro;
    public static javax.swing.JButton btnOpenSetembro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JComboBox<String> cmbAnoEconomico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbEmpresa;
    public static javax.swing.JLabel lbTitleFevereiro;
    public static javax.swing.JLabel lbTitleFevereiro1;
    public static javax.swing.JLabel lbTitleFevereiro2;
    public static javax.swing.JLabel lbTitleFevereiro3;
    public static javax.swing.JLabel lbTitleFevereiro4;
    public static javax.swing.JLabel lbTitleFevereiro5;
    public static javax.swing.JLabel lbTitleFevereiro6;
    public static javax.swing.JLabel lbTitleFevereiro7;
    public static javax.swing.JLabel lbTitleFevereiro8;
    public static javax.swing.JLabel lbTitleJaneiro;
    public static javax.swing.JLabel lbTitleJaneiro1;
    public static javax.swing.JLabel lbTitleJaneiro2;
    private javax.swing.JLabel lb_seja_bem_vindo1;
    public static javax.swing.JPanel painelAbril;
    public static javax.swing.JPanel painelAgosto;
    public static javax.swing.JPanel painelDezembro;
    public static javax.swing.JPanel painelFevereiro;
    public static javax.swing.JPanel painelJaneiro;
    public static javax.swing.JPanel painelJulho;
    public static javax.swing.JPanel painelJunho;
    public static javax.swing.JPanel painelMaio;
    public static javax.swing.JPanel painelMarco;
    public static javax.swing.JPanel painelNovembro;
    public static javax.swing.JPanel painelOutubro;
    public static javax.swing.JPanel painelSetembro;
    // End of variables declaration//GEN-END:variables

    private void setComBoBox()
    {
        cmbAnoEconomico.setModel( new DefaultComboBoxModel( (Vector) anoDao.buscaTodos() ) );
        //cmbPeriodo.setSelectedItem( MetodosUtil.getDescricaoMes( new Date().getMonth() ) );
        Date date = new Date();
        String ano_lectivo = String.valueOf( ( 1900 + date.getYear() ) );
        cmbAnoEconomico.setSelectedItem( ano_lectivo );

    }

    public static int getIdAnoEconomico()
    {
        return anoDao.getIdByDescricao( cmbAnoEconomico.getSelectedItem().toString() );
    }

    public void desenharPeriodos()
    {

        int idAnoEconomico = getIdAnoEconomico();

        for ( int idPeriodo = 1; idPeriodo <= 12; idPeriodo++ )
        {

            if ( idPeriodo == DVML.JANEIRO )
            {
                painelJaneiro.setVisible( true );
//                System.out.println("Resultado: " + fechoPeriodoDao.existe_abertura(fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido(idAnoEconomico ,idPeriodo)));
                btnOpenJaneiro.setVisible( !fechoPeriodoDao.existe_abertura( fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido( idAnoEconomico, idPeriodo ) ) );
                resizeJButtonIcon( largura, altura, getClass().getResource( path_open ), btnOpenJaneiro );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseJaneiro );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarJaneiro );
            }
            else if ( idPeriodo == DVML.FEVEREIRO )
            {
                visulaizar_paienl( idAnoEconomico, idPeriodo, painelFevereiro );
                visualizar_botao_abrir( idAnoEconomico, idPeriodo, btnOpenFevereiro );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseFevereiro );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarFevereiro );

            }
            else if ( idPeriodo == DVML.MARCO )
            {
                visulaizar_paienl( idAnoEconomico, idPeriodo, painelMarco );
                visualizar_botao_abrir( idAnoEconomico, idPeriodo, btnOpenMarco );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseMarco );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarMarco );
            }
            else if ( idPeriodo == DVML.ABRIL )
            {
                visulaizar_paienl( idAnoEconomico, idPeriodo, painelAbril );
                visualizar_botao_abrir( idAnoEconomico, idPeriodo, btnOpenAbril );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseAbril );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarAbril );
            }
            else if ( idPeriodo == DVML.MAIO )
            {
                visulaizar_paienl( idAnoEconomico, idPeriodo, painelMaio );
                visualizar_botao_abrir( idAnoEconomico, idPeriodo, btnOpenMaio );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseMaio );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarMaio );
            }
            else if ( idPeriodo == DVML.JUNHO )
            {
                visulaizar_paienl( idAnoEconomico, idPeriodo, painelJunho );
                visualizar_botao_abrir( idAnoEconomico, idPeriodo, btnOpenJunho );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseJunho );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarJunho );
            }
            else if ( idPeriodo == DVML.JULHO )
            {
                visulaizar_paienl( idAnoEconomico, idPeriodo, painelJulho );
                visualizar_botao_abrir( idAnoEconomico, idPeriodo, btnOpenJulho );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseJulho );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarJulho );
            }
            else if ( idPeriodo == DVML.AGOSTO )
            {
                visulaizar_paienl( idAnoEconomico, idPeriodo, painelAgosto );
                visualizar_botao_abrir( idAnoEconomico, idPeriodo, btnOpenAgosto );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseAgosto );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarAgosto );
            }
            else if ( idPeriodo == DVML.SETEMBRO )
            {
                visulaizar_paienl( idAnoEconomico, idPeriodo, painelSetembro );
                visualizar_botao_abrir( idAnoEconomico, idPeriodo, btnOpenSetembro );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseSetembro );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarSetembro );
            }
            else if ( idPeriodo == DVML.OUTUBRO )
            {
                visulaizar_paienl( idAnoEconomico, idPeriodo, painelOutubro );
                visualizar_botao_abrir( idAnoEconomico, idPeriodo, btnOpenOutubro );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseOutubro );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarOutubro );
            }
            else if ( idPeriodo == DVML.NOVEMBRO )
            {
                visulaizar_paienl( idAnoEconomico, idPeriodo, painelNovembro );
                visualizar_botao_abrir( idAnoEconomico, idPeriodo, btnOpenNovembro );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseNovembro );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarNovembro );
            }
            else if ( idPeriodo == DVML.DEZEMBRO )
            {
                visulaizar_paienl( idAnoEconomico, idPeriodo, painelDezembro );
                visualizar_botao_abrir( idAnoEconomico, idPeriodo, btnOpenDezembro );
                visualizar_botao_fechar( idAnoEconomico, idPeriodo, btnCloseDezembro );
                visulizar_botao_anular( idAnoEconomico, idPeriodo, btnEliminarDezembro );
            }

        }

    }

    public static void resetPeriodos()
    {

        resetMes( painelJaneiro, btnOpenJaneiro, btnCloseJaneiro, btnEliminarJaneiro );
        resetMes( painelFevereiro, btnOpenFevereiro, btnCloseFevereiro, btnEliminarFevereiro );
        resetMes( painelMarco, btnOpenMarco, btnCloseMarco, btnEliminarMarco );
        resetMes( painelAbril, btnOpenAbril, btnCloseAbril, btnEliminarAbril );

        resetMes( painelMaio, btnOpenMaio, btnCloseMaio, btnEliminarMaio );
        resetMes( painelJunho, btnOpenJunho, btnCloseJunho, btnEliminarJunho );
        resetMes( painelJulho, btnOpenJulho, btnCloseJulho, btnEliminarJulho );
        resetMes( painelAgosto, btnOpenAgosto, btnCloseAgosto, btnEliminarAgosto );

        resetMes( painelSetembro, btnOpenSetembro, btnCloseSetembro, btnEliminarSetembro );
        resetMes( painelOutubro, btnOpenOutubro, btnCloseOutubro, btnEliminarOutubro );
        resetMes( painelNovembro, btnOpenNovembro, btnCloseNovembro, btnEliminarNovembro );
        resetMes( painelDezembro, btnOpenDezembro, btnCloseDezembro, btnEliminarDezembro );

    }

    public static void procedimentoAbrirPeriodo( int idAnoEconomico, int idPerido, Date dataAbertura )
    {
        fechoPeriodo = new FechoPeriodo();
        fechoPeriodo.setDataAbertura( dataAbertura );
        fechoPeriodo.setDataFecho( null );
        fechoPeriodo.setFkAno( anoDao.findTbAno( idAnoEconomico ) );
        fechoPeriodo.setFkPeriodo( mesRhDao.findTbMesRh( idPerido ) );
        fechoPeriodo.setFkUsuario( usuarioDao.findTbUsuario( idUsuario ) );

        try
        {
            fechoPeriodoDao.create( fechoPeriodo );
            MetodosUtil.showMessageUtil( "Período aberto com sucesso.", DVML.TIPO_MENSAGEM_INFOR );

        }
        catch ( Exception e )
        {
            e.printStackTrace();
            MetodosUtil.showMessageUtil( "Falha ao abrir o período", DVML.TIPO_MENSAGEM_ERRO );

        }

    }

    @Override
    public void run()
    {
        while ( true )
        {
            try
            {
                Thread.sleep( 1000 );
                //jPanel6.repaint();
                //resetPeriodos();
                desenharPeriodos();
            }
            catch ( InterruptedException ex )
            {
                Logger.getLogger( DefinicoesVisao.class.getName() ).log( Level.SEVERE, null, ex );
            }
        }
    }

    public static void procedimentoFechar( int idPeriodo )
    {

        int opcao = JOptionPane.showConfirmDialog( null, "Caro usuário tens a plena certeza fechar este período?\nObs:Uma vez fechado não voltarás a abrir." );

        if ( opcao == JOptionPane.YES_OPTION )
        {

            FechoPeriodo periodoActual = fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido( getIdAnoEconomico(), idPeriodo );
            fechoPeriodo = fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido( getIdAnoEconomico(), idPeriodo );

            fechoPeriodo.setDataFecho( data_fecho_periodo );
            try
            {
                if ( !Objects.isNull( periodoActual ) )
                {
                    if ( MetodosUtil.maior_data_1_data_2( new Date(), periodoActual.getDataAbertura() ) || MetodosUtil.igual_data_1_data_2( new Date(), periodoActual.getDataAbertura() ) )
                    {
                        fechoPeriodoDao.edit( fechoPeriodo );
                    }
                    else
                    {
                        JOptionPane.showMessageDialog( null, "Caro usuário verifique a data do sistema" );
                    }
                }
                else
                {
                    fechoPeriodoDao.edit( fechoPeriodo );
                    data_fecho_periodo = null;
                }

            }
            catch ( Exception e )
            {
                e.printStackTrace();
                MetodosUtil.showMessageUtil( "Falha ao realizar o fecho do período", DVML.TIPO_MENSAGEM_INFOR );
            }

        }

    }

    private void visualizar_botao_abrir( int idAno, int idPeriodo, JButton button )
    {
        button.setVisible( false );
        if ( fechoPeriodoDao.existe_periodo( idAno, idPeriodo ) )
        {
            FechoPeriodo periodoAnterior = fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido( idAno, idPeriodo - 1 );
            FechoPeriodo periodoActual = fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido( idAno, idPeriodo );
            if ( fechoPeriodoDao.existe_fecho( periodoAnterior ) )
            {
                if ( !fechoPeriodoDao.existe_abertura( periodoActual ) )
                {
                    //visualiza
                    button.setVisible( true );
                    resizeJButtonIcon( largura, altura, getClass().getResource( path_open ), button );
                }

            }
            else
            {
                //não visualiza
                button.setVisible( false );
            }
        }
        else
        {

            //visualiza
            button.setVisible( true );
            resizeJButtonIcon( largura, altura, getClass().getResource( path_open ), button );
        }
    }

    private void visualizar_botao_fechar( int idAno, int idPeriodo, JButton button )
    {
        FechoPeriodo periodo = fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido( idAno, idPeriodo );
        button.setVisible( false );
        if ( fechoPeriodoDao.existe_periodo( idAno, idPeriodo ) )
        {
            if ( fechoPeriodoDao.existe_abertura( periodo ) )
            {
                //visualiza senão existe um fecho
                button.setVisible( !fechoPeriodoDao.existe_fecho( periodo ) );
                resizeJButtonIcon( largura, altura, getClass().getResource( path_close ), button );
            }
            else
            {
                //não visualiza
                button.setVisible( false );
            }
        }

    }

    private void visulaizar_paienl( int idAno, int idPeriodo, JPanel painelFevereiro )
    {

        FechoPeriodo periodoAnterior = fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido( idAno, idPeriodo - 1 );
        painelFevereiro.setVisible( fechoPeriodoDao.existe_fecho( periodoAnterior ) );

    }

    private static void resetMes( JPanel painel, JButton abrir, JButton fechar, JButton cancelar )
    {
//        painel.setVisible(false);
//        abrir.setVisible(false);
//        fechar.setVisible(false);
//        cancelar.setVisible(false);
    }

    private void visulizar_botao_anular( int idAnoEconomico, int idPeriodo, JButton btnClose )
    {

        btnClose.setVisible( false );
        if ( fechoPeriodoDao.existe_periodo( idAnoEconomico, idPeriodo ) )
        {
            FechoPeriodo periodoActual = fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido( idAnoEconomico, idPeriodo );
            FechoPeriodo periodoPosterior = fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido( idAnoEconomico, idPeriodo + 1 );
            if ( fechoPeriodoDao.existe_abertura( periodoActual ) && !fechoPeriodoDao.existe_abertura( periodoPosterior ) )
            {
                btnClose.setVisible( true );
                resizeJButtonIcon( largura, altura, getClass().getResource( path_eliminar ), btnClose );
            }
            else
            {
                btnClose.setVisible( false );
            }
        }
    }

    private void procedimentoEliminar( int idPeriodo )
    {
        int opcao = JOptionPane.showConfirmDialog( null, "Caro usuário deseja realmente cancelar o período?" );
        if ( opcao == JOptionPane.YES_OPTION )
        {
            try
            {
                FechoPeriodo periodo = fechoPeriodoDao.getFechoPeriodoByIdAnoAndPerido( getIdAnoEconomico(), idPeriodo );
                fechoPeriodoDao.destroy( periodo.getPkFechoPeriodo() );
                MetodosUtil.showMessageUtil( "Período cancelado com sucesso!", DVML.TIPO_MENSAGEM_INFOR );

            }
            catch ( Exception e )
            {
                MetodosUtil.showMessageUtil( "Falhao ao cancelar o período!", DVML.TIPO_MENSAGEM_INFOR );
            }
        }
        else
        {
        }
    }
}
