/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rh.visao;


import java.sql.Connection;
import dao.AnoDao;
import dao.FaltaDao;
import dao.FechoPeriodoDao;
import dao.FuncionarioDao;
import dao.ItemSalarioExtraDao;
import dao.MasterTableDao;
import dao.MesRhDao;
import dao.UsuarioDao;
import entity.Empresa;
import entity.TbFalta;
import entity.TbFuncionario;
import entity.TbUsuario;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.Vector;
import javax.persistence.EntityManagerFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import kitanda.util.CfMethodsSwing;
import util.BDConexao;
import util.JPAEntityMannagerFactoryUtil;
import static util.MetodosUtil.*;
import static util.DVML.*;
import util.FaltaInjusticadaUtil;
import util.FaltaJusticadaUtil;
import util.extrasalario.ExtraSalarioUtil;
import util.MetodosUtil;
import util.calendar.MyCalendarVisao;
import util.tabela_manual.tabela.Tabela;

/**
 *
 * @author Domingos Dala Vunge
 */
public class ExtraSalarioFuncionarioVisao extends javax.swing.JFrame
{

    private static EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;

    private static int idUsuario = 0;
    private static int idEmpresa = 0;
    public static final FuncionarioDao funcionarioDao = new FuncionarioDao( emf );
    public static final MasterTableDao masterTableDao = new MasterTableDao( emf );
    public static final FechoPeriodoDao fechoPeriodoDao = new FechoPeriodoDao( emf );
    public static final FaltaDao faltaDao = new FaltaDao( emf );

    public static ItemSalarioExtraDao itemSalarioExtraDao = new ItemSalarioExtraDao( emf );
    public static UsuarioDao usuarioDao = new UsuarioDao( emf );
    public static TbFuncionario funcionario_global = null;
    public static TbUsuario usuario_global = null;
    public static Empresa empresa_global = null;
    public static final AnoDao anoDao = new AnoDao( emf );
    public static final MesRhDao mesRhDao = new MesRhDao( emf );
    public static String log = "";
    private final ExtraSalarioUtil remuneracao_util, desconto_util, abonos_util;
    private static BDConexao conexao;
    Tabela t;

    public ExtraSalarioFuncionarioVisao( int idUsuario, int idEmpresa, BDConexao conexao )
    {
        initComponents();
        setLocationRelativeTo( null );
        this.idUsuario = idUsuario;
        this.idEmpresa = idEmpresa;
        this.conexao = conexao;

        init();
        remuneracao_util = new ExtraSalarioUtil( tabela_remuneracao, MASTER_TABLE_REMUNERACAO, cmbRemunuracoes, jsValorRemuneracao );
        desconto_util = new ExtraSalarioUtil( tabela_desconto, MASTER_TABLE_DESCONTO, cmbDesconto, jsValorDesconto );
        abonos_util = new ExtraSalarioUtil( tabela_abonos, MASTER_TABLE_ABONOS, cmbAbonos, jsValorAbono );

        desenhar_tabelas_justificadas_e_injustificadas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        buttonGroupEstadoCivil = new javax.swing.ButtonGroup();
        buttonGroupSegurançaSocial = new javax.swing.ButtonGroup();
        buttonGroupNIF = new javax.swing.ButtonGroup();
        buttonGroupFormaPagamento = new javax.swing.ButtonGroup();
        buttonDescontoSegurancaSocial = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroFuncionarioPesquisa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lb_nome_funcionario = new javax.swing.JLabel();
        lb_departamento = new javax.swing.JLabel();
        lb_funcao = new javax.swing.JLabel();
        cmbAno = new javax.swing.JComboBox<>();
        lbDataComeco = new javax.swing.JLabel();
        lbDataComeco1 = new javax.swing.JLabel();
        cmbPeriodo = new javax.swing.JComboBox<>();
        painel = new javax.swing.JPanel();
        painel_principal = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_remuneracao = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jsValorRemuneracao = new javax.swing.JSpinner();
        cmbRemunuracoes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jsValorDesconto = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_desconto = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        cmbDesconto = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela_abonos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jsValorAbono = new javax.swing.JSpinner();
        cmbAbonos = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableInjustificada = new javax.swing.JTable();
        lbDataTermino2 = new javax.swing.JLabel();
        lbDataTermino1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableJustificada = new javax.swing.JTable();
        jSpFalta = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lb_seja_bem_vindo1 = new javax.swing.JLabel();
        lbEmpresa = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("OUTRAS OPERAÇÕES");

        txtNumeroFuncionarioPesquisa.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
        txtNumeroFuncionarioPesquisa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNumeroFuncionarioPesquisaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 12)); // NOI18N
        jLabel4.setText("Pesq. Nº Func:*");

        lb_nome_funcionario.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        lb_nome_funcionario.setText("Nome do Funcionário");

        lb_departamento.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        lb_departamento.setText("Departamento:");

        lb_funcao.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        lb_funcao.setText("Função");

        cmbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAno.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbAnoActionPerformed(evt);
            }
        });

        lbDataComeco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDataComeco.setText("Ano:");

        lbDataComeco1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDataComeco1.setText("Período:");

        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPeriodo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbPeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroFuncionarioPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nome_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_funcao, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDataComeco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAno, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lbDataComeco1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNumeroFuncionarioPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lb_nome_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_funcao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataComeco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataComeco1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Typewriter", 1, 13))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N

        tabela_remuneracao.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        tabela_remuneracao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Cod.", "Designação", "Valor"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean []
            {
                true, false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabela_remuneracao.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tabela_remuneracaoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela_remuneracao);
        if (tabela_remuneracao.getColumnModel().getColumnCount() > 0)
        {
            tabela_remuneracao.getColumnModel().getColumn(0).setMaxWidth(50);
            tabela_remuneracao.getColumnModel().getColumn(2).setMaxWidth(600);
        }

        jLabel5.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 12)); // NOI18N
        jLabel5.setText("Valor*");

        cmbRemunuracoes.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
        cmbRemunuracoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione --", "Bilhete de Idêntidade", "Passaporte", "Cédula", "Outros" }));
        cmbRemunuracoes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbRemunuracoesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 12)); // NOI18N
        jLabel6.setText("Remuneração");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Button-Add-icon.png"))); // NOI18N
        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eliminar_16x16.png"))); // NOI18N
        jButton4.setText("Remover");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jsValorRemuneracao, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))
                            .addComponent(cmbRemunuracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(403, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRemunuracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsValorRemuneracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        painel_principal.addTab("Remuneração", jPanel3);

        jLabel7.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 12)); // NOI18N
        jLabel7.setText("Desconto");

        jLabel8.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 12)); // NOI18N
        jLabel8.setText("Valor*");

        tabela_desconto.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        tabela_desconto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Cod.", "Designação", "Valor"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean []
            {
                true, false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabela_desconto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tabela_descontoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabela_desconto);
        if (tabela_desconto.getColumnModel().getColumnCount() > 0)
        {
            tabela_desconto.getColumnModel().getColumn(0).setMaxWidth(50);
            tabela_desconto.getColumnModel().getColumn(2).setMaxWidth(600);
        }

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Button-Add-icon.png"))); // NOI18N
        jButton5.setText("Adicionar");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/2934_32x32.png"))); // NOI18N
        jButton6.setText("Remover");
        jButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6ActionPerformed(evt);
            }
        });

        cmbDesconto.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
        cmbDesconto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione --", "Bilhete de Idêntidade", "Passaporte", "Cédula", "Outros" }));
        cmbDesconto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbDescontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jsValorDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsValorDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_principal.addTab("Desconto", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Sans Typewriter", 1, 13))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 13)); // NOI18N

        tabela_abonos.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        tabela_abonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Cod.", "Designação", "Valor"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean []
            {
                true, false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabela_abonos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tabela_abonosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabela_abonos);
        if (tabela_abonos.getColumnModel().getColumnCount() > 0)
        {
            tabela_abonos.getColumnModel().getColumn(0).setMaxWidth(50);
            tabela_abonos.getColumnModel().getColumn(2).setMaxWidth(600);
        }

        jLabel9.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 12)); // NOI18N
        jLabel9.setText("Valor*");

        cmbAbonos.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
        cmbAbonos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione --", "Bilhete de Idêntidade", "Passaporte", "Cédula", "Outros" }));
        cmbAbonos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbAbonosActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 12)); // NOI18N
        jLabel10.setText("Abono");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Button-Add-icon.png"))); // NOI18N
        jButton7.setText("Adicionar");
        jButton7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eliminar_16x16.png"))); // NOI18N
        jButton8.setText("Remover");
        jButton8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jsValorAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(483, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsValorAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_principal.addTab("Abonos", jPanel5);

        jTableInjustificada.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableInjustificada.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
        jTableInjustificada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jTableInjustificada.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTableInjustificadaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableInjustificada);

        lbDataTermino2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        lbDataTermino2.setText("Faltas Injustificadas");

        lbDataTermino1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        lbDataTermino1.setText("Faltas Justificadas");

        jTableJustificada.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableJustificada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Data", "nº de Hora(s)", "dia", "Justificativa", "Data Just."
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTableJustificada.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTableJustificadaMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableJustificada);

        jLabel11.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        jLabel11.setText("hora(s)");

        jButton1.setText("Seleccione às datas à aplicar.");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jSpFalta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addComponent(lbDataTermino2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbDataTermino1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpFalta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDataTermino2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDataTermino1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        painel_principal.addTab("Falta", jPanel2);

        lb_seja_bem_vindo1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        lb_seja_bem_vindo1.setText("EMPRESA:");

        lbEmpresa.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 10)); // NOI18N
        lbEmpresa.setText("BEM VINDO!....");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOUT - CINZA/Logout-32x32.png"))); // NOI18N
        jButton11.setText("Sair");
        jButton11.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_principal)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addComponent(lb_seja_bem_vindo1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(389, 389, 389)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_seja_bem_vindo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroFuncionarioPesquisaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNumeroFuncionarioPesquisaActionPerformed
    {//GEN-HEADEREND:event_txtNumeroFuncionarioPesquisaActionPerformed
        // TODO add your handling code here:
        busca_funcionario( txtNumeroFuncionarioPesquisa.getText() );
    }//GEN-LAST:event_txtNumeroFuncionarioPesquisaActionPerformed

    private void cmbPeriodoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbPeriodoActionPerformed
    {//GEN-HEADEREND:event_cmbPeriodoActionPerformed
        // TODO add your handling code here:
        procedimento_adicionar_all();
    }//GEN-LAST:event_cmbPeriodoActionPerformed

    private void cmbAnoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbAnoActionPerformed
    {//GEN-HEADEREND:event_cmbAnoActionPerformed
        // TODO add your handling code here:
        procedimento_adicionar_all();
    }//GEN-LAST:event_cmbAnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        procedimento_chamar_calendario();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableJustificadaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableJustificadaMouseClicked
    {//GEN-HEADEREND:event_jTableJustificadaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableJustificadaMouseClicked

    private void jTableInjustificadaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableInjustificadaMouseClicked
    {//GEN-HEADEREND:event_jTableInjustificadaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableInjustificadaMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton8ActionPerformed
    {//GEN-HEADEREND:event_jButton8ActionPerformed
        // TODO add your handling code here:
        abonos_util.remover_item();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
        // TODO add your handling code here:
        abonos_util.registrar_item();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cmbAbonosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbAbonosActionPerformed
    {//GEN-HEADEREND:event_cmbAbonosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAbonosActionPerformed

    private void tabela_abonosMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tabela_abonosMouseClicked
    {//GEN-HEADEREND:event_tabela_abonosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabela_abonosMouseClicked

    private void cmbDescontoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbDescontoActionPerformed
    {//GEN-HEADEREND:event_cmbDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDescontoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        // TODO add your handling code here:
        desconto_util.remover_item();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        // TODO add your handling code here:
        desconto_util.registrar_item();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tabela_descontoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tabela_descontoMouseClicked
    {//GEN-HEADEREND:event_tabela_descontoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabela_descontoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        // TODO add your handling code here:
        remuneracao_util.remover_item();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
        remuneracao_util.registrar_item();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbRemunuracoesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbRemunuracoesActionPerformed
    {//GEN-HEADEREND:event_cmbRemunuracoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRemunuracoesActionPerformed

    private void tabela_remuneracaoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tabela_remuneracaoMouseClicked
    {//GEN-HEADEREND:event_tabela_remuneracaoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tabela_remuneracaoMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton11ActionPerformed
    {//GEN-HEADEREND:event_jButton11ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( ExtraSalarioFuncionarioVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( ExtraSalarioFuncionarioVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( ExtraSalarioFuncionarioVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( ExtraSalarioFuncionarioVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ExtraSalarioFuncionarioVisao( 15, 2, BDConexao.getInstancia() ).setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonDescontoSegurancaSocial;
    private javax.swing.ButtonGroup buttonGroupEstadoCivil;
    private javax.swing.ButtonGroup buttonGroupFormaPagamento;
    private javax.swing.ButtonGroup buttonGroupNIF;
    private javax.swing.ButtonGroup buttonGroupSegurançaSocial;
    private javax.swing.ButtonGroup buttonGroupSexo;
    public static javax.swing.JComboBox<String> cmbAbonos;
    public static javax.swing.JComboBox<String> cmbAno;
    public static javax.swing.JComboBox<String> cmbDesconto;
    public static javax.swing.JComboBox<String> cmbPeriodo;
    public static javax.swing.JComboBox<String> cmbRemunuracoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public static javax.swing.JSpinner jSpFalta;
    private static javax.swing.JTable jTableInjustificada;
    private static javax.swing.JTable jTableJustificada;
    public static javax.swing.JSpinner jsValorAbono;
    public static javax.swing.JSpinner jsValorDesconto;
    public static javax.swing.JSpinner jsValorRemuneracao;
    private javax.swing.JLabel lbDataComeco;
    private javax.swing.JLabel lbDataComeco1;
    private javax.swing.JLabel lbDataTermino1;
    private javax.swing.JLabel lbDataTermino2;
    private javax.swing.JLabel lbEmpresa;
    private javax.swing.JLabel lb_departamento;
    private javax.swing.JLabel lb_funcao;
    private javax.swing.JLabel lb_nome_funcionario;
    private javax.swing.JLabel lb_seja_bem_vindo1;
    public static javax.swing.JPanel painel;
    public static javax.swing.JTabbedPane painel_principal;
    public static javax.swing.JTable tabela_abonos;
    public static javax.swing.JTable tabela_desconto;
    public static javax.swing.JTable tabela_remuneracao;
    public static javax.swing.JTextField txtNumeroFuncionarioPesquisa;
    // End of variables declaration//GEN-END:variables

    private void init()
    {
        cmbRemunuracoes.setModel( new DefaultComboBoxModel( ( Vector ) masterTableDao.buscaTodosByIdMaster( MASTER_TABLE_REMUNERACAO ) ) );
        cmbDesconto.setModel( new DefaultComboBoxModel( ( Vector ) masterTableDao.buscaTodosByIdMaster( MASTER_TABLE_DESCONTO ) ) );
        cmbAbonos.setModel( new DefaultComboBoxModel( ( Vector ) masterTableDao.buscaTodosByIdMaster( MASTER_TABLE_ABONOS ) ) );

        usuario_global = usuarioDao.findTbUsuario( idUsuario );

        cmbPeriodo.setModel( new DefaultComboBoxModel( ( Vector ) mesRhDao.buscaTodos() ) );
        cmbAno.setModel( new DefaultComboBoxModel( ( Vector ) anoDao.buscaTodos() ) );
        
        cmbPeriodo.setSelectedItem( MetodosUtil.getDescricaoMes( new Date().getMonth() ) );
        jSpFalta.setModel( CfMethodsSwing.criarSpinnerDoubleModel( 0.0, 10000000000.00, 0.0 ) );

    }

    private void busca_funcionario( String parm_numero_func )
    {

        funcionario_global = funcionarioDao.getFuncionarioByNumeroFuncionario( parm_numero_func );
        if ( funcionario_global != null )
        {

            System.out.println( "Nome: " + funcionario_global.getNome() );
            lb_nome_funcionario.setText( "Nome: " + funcionario_global.getNome() );
            lb_departamento.setText( "Departamento: " + funcionario_global.getFkDepartamento().getDesignacao() );
            lb_funcao.setText( "Função: " + funcionario_global.getFkFuncao().getDesignacao() );

            procedimento_adicionar_all();

        }
        else
        {
            limpar_campos_funcionario();
            limpar_tabelas();
            showMessageUtil( "Não existe funcionário com este número.", TIPO_MENSAGEM_INFOR );
        }

    }

    private void limpar_campos_funcionario()
    {
        lb_nome_funcionario.setText( "" );
        lb_departamento.setText( "" );
        lb_funcao.setText( "" );
        funcionario_global = null;
    }

    private void procedimento_adicionar_all()
    {
        if ( funcionario_global != null )
        {
            try
            {
                remuneracao_util.adicionar_tabela();
                desconto_util.adicionar_tabela();
                abonos_util.adicionar_tabela();

            }
            catch ( Exception e )
            {
            }
            desenhar_tabelas_justificadas_e_injustificadas();
        }

    }

    private void limpar_tabelas()
    {
        MetodosUtil.esvaziar_tabela( tabela_remuneracao );
        MetodosUtil.esvaziar_tabela( tabela_desconto );
        MetodosUtil.esvaziar_tabela( tabela_abonos );
        MetodosUtil.esvaziar_tabela( jTableInjustificada );

    }

    public static void procedimento_registrar_falta( List<Date> dataSeleccionadas )
    {
        if ( dataSeleccionadas != null )
        {
            for ( Date dataSeleccionada : dataSeleccionadas )
            {
                TbFalta falta = new TbFalta();

                falta.setData( dataSeleccionada );
                falta.setHora( dataSeleccionada );
                falta.setIdFuncionarioFK( funcionario_global );
                falta.setDataJustificativa( null );
                falta.setJustificadaInjustificada( Boolean.FALSE );

                falta.setNFalta( ( Double ) jSpFalta.getValue() );
                falta.setDescricaoFalta( "" );
                try
                {
                    faltaDao.create( falta );
                }
                catch ( Exception e )
                {
                    e.printStackTrace();
                }

            }
            desenhar_tabelas_justificadas_e_injustificadas();
        }
        else
        {
            System.out.println( "Lista vazia." );
        }
    }

    public static void remover_falta( int codFalta )
    {

        try
        {
            faltaDao.destroy( codFalta );
            desenhar_tabelas_justificadas_e_injustificadas();
        }
        catch ( Exception e )
        {
        }

    }

    private static int getPeriodo()
    {
        return mesRhDao.getIdByDescricao( cmbPeriodo.getSelectedItem().toString() );
    }

    public static void desenhar_tabelas_justificadas_e_injustificadas()
    {
        try
        {
            if ( !Objects.isNull( funcionario_global ) )
            {
                System.out.println( "Cheguei aqui no ExtraSalarias do Funcionario: TABELAS INJUSTIFICADAS"  );
                Tabela tabela_injustificada = new Tabela( jTableInjustificada,
                        FaltaInjusticadaUtil.getCampos(),
                        FaltaInjusticadaUtil.getClasses(),
                        FaltaInjusticadaUtil.getColumnEditable(),
                        FaltaInjusticadaUtil.dados( fechoPeriodoDao, faltaDao, getIdAno(), getPeriodo(), conexao, funcionario_global ) );

                FaltaInjusticadaUtil.accao( jTableInjustificada );

                Tabela tabela_justificada = new Tabela( jTableJustificada,
                        FaltaJusticadaUtil.getCampos(),
                        FaltaJusticadaUtil.getClasses(),
                        FaltaJusticadaUtil.getColumnEditable(),
                        FaltaJusticadaUtil.dados( fechoPeriodoDao, faltaDao, getIdAno(), getPeriodo(), conexao, funcionario_global ) );

            }
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }
    }

    private void procedimento_chamar_calendario()
    {

        double hora = ( Double ) jSpFalta.getValue();
        if ( funcionario_global != null )
        {
            if ( hora > 0 )
            {

                new MyCalendarVisao( idUsuario ).setVisible(true);
            }
            else
            {
                showMessageUtil( "Caro usuário insira a(s) hora(s) em que o funcionário faltou.", TIPO_MENSAGEM_AVISO );
            }
        }
        else
        {
            showMessageUtil( "Caro usuário pesquisa o funcionário.", TIPO_MENSAGEM_AVISO );
        }

    }

    private static int getIdAno()
    {
        return anoDao.getIdByDescricao( cmbAno.getSelectedItem().toString() );
    }

}
