/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tesouraria.visao;

//import rh.visao.*;
import dao.ItemPermissaoDao;
import entity.TbItemPermissao;
import java.util.Vector;
import javax.persistence.EntityManagerFactory;
import javax.swing.JFrame;
import modelo.ItemPermissaoModelo;
import util.BDConexao;
import util.DVML;
import util.JPAEntityMannagerFactoryUtil;
import util.OperacaoSistemaUtil;
import visao.BancoVisao;
import visao.InformacoesEmpresaVisao;
import visao.LoginVisao;
import visao.RelatorioDepositosVisao;
import visao.RelatorioEntradasVisao;
import visao.RelatorioLevantamentosVisao;
import visao.RelatorioSaidasVisao;
//import visao.ProfessorVisao;
import visao.RootVisao;
import visao.SaldoBanco;


/**
 *
 * @author Domingos Dala Vunge
 */
public class MenuPrincipalTesourariaVisao extends javax.swing.JFrame {
    
    private EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;
    private ItemPermissaoDao itemPermissaoDao = new ItemPermissaoDao(emf);
    private OperacaoSistemaUtil osu =  new OperacaoSistemaUtil();
    private int idUser = 0;
    private int idEmpresa = 0;
    private BDConexao conexao;
    
    public MenuPrincipalTesourariaVisao(int id_user, int id_empresa, BDConexao conexao) {
        initComponents();
        this.idUser = id_user;
        this.idEmpresa = id_empresa;
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
        this.setExtendedState(this.getExtendedState()|MenuPrincipalTesourariaVisao.MAXIMIZED_BOTH  );  
        this.conexao = conexao;
        busca_permissao();
    }
    
   public void busca_permissao() {
               
        try {
             // TODO add your handling code here
             setStatusUsuario( (Vector) itemPermissaoDao.getAllPermissoesByIdUsuarioAndModulo( this.idUser ,  DVML.MODULO_RH_TESOURARIA)    );
         } catch (Exception ex) {
              ex.printStackTrace();
         }
        
     }
    
  public void setStatusUsuario(Vector<TbItemPermissao> vector) {
       
          String permissao = "";
  
          //limpa
           setPermissoes(false);
          
          for (int i = 0; i < vector.size(); i++) 
          {
  
                permissao =  vector.get(i).getIdPermissao().getDescricao();
                
                /*FICHEIROS*/
                if(permissao.equals("Saldos de Contas"))
                      jlmSaldosContas.setEnabled(true);
                else if(permissao.equals("Entrada Caixa"))
                      jlmEntradasCaixa.setEnabled(true);
                else if(permissao.equals("Saida Caixa"))
                      jlmSaidasCaixa.setEnabled(true);
                else if(permissao.equals("Deposito Bancario"))
                      jlmDepositosBancarios.setEnabled(true);
                else if(permissao.equals("Levantamento Bancario"))
                      jlmLevantamentosBancarios.setEnabled(true);
                else if(permissao.equals("Transferencias Bancarias"))
                      jlmTransferenciasBancarias.setEnabled(true);

                 /*RELATORIOS*/
                else if(permissao.equals("Extrato de Movimentos Bancarios"))
                      jlmExtratoDeMovimentosBancarios.setEnabled(true);
                else if(permissao.equals("Relatorios de Entradas no Caixa") )
                      jlmRelatoriosDeEntradasNoCaixa.setEnabled(true);
                else if (permissao.equals("Relatorios de Saidas do Caixa"))
                      jlmRelatoriosDeSaidasDoCaixa.setEnabled(true);

          }
          
   }
   
   public void setPermissoes(boolean status){
    
                      /*FICHEIROS*/
             
                      jlmSaldosContas.setEnabled(status);
                      jlmEntradasCaixa.setEnabled(status);
                      jlmSaidasCaixa.setEnabled(status);
                      jlmDepositosBancarios.setEnabled(status);
                      jlmLevantamentosBancarios.setEnabled(status);
                      jlmTransferenciasBancarias.setEnabled(status);
                      
                      /*RELATORIOS*/
             
                      jlmExtratoDeMovimentosBancarios.setEnabled(status);
                      jlmRelatoriosDeEntradasNoCaixa.setEnabled(status);
                      jlmRelatoriosDeSaidasDoCaixa.setEnabled(status);

                      
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lb_nome_software = new javax.swing.JLabel();
        lb_descricao_software = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jlmSaldosContas = new javax.swing.JMenuItem();
        jlmEntradasCaixa = new javax.swing.JMenuItem();
        jlmSaidasCaixa = new javax.swing.JMenuItem();
        jlmDepositosBancarios = new javax.swing.JMenuItem();
        jlmLevantamentosBancarios = new javax.swing.JMenuItem();
        jlmTransferenciasBancarias = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jlmRelatoriosDeEntradasNoCaixa = new javax.swing.JMenuItem();
        jlmRelatoriosDeSaidasDoCaixa = new javax.swing.JMenuItem();
        jlmRelatoriosDeEntradasNoCaixa1 = new javax.swing.JMenuItem();
        jlmRelatoriosDeEntradasNoCaixa2 = new javax.swing.JMenuItem();
        jlmExtratoDeMovimentosBancarios = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lb_nome_software.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        lb_nome_software.setText("TESOURARIA");

        lb_descricao_software.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lb_descricao_software.setText("Sistema de Gestão Comercial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_nome_software)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_descricao_software, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addComponent(lb_nome_software, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_descricao_software)
                .addGap(15, 15, 15))
        );

        jMenu7.setText("Ficheiro");

        jlmSaldosContas.setText("Saldos de Contas");
        jlmSaldosContas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jlmSaldosContasActionPerformed(evt);
            }
        });
        jMenu7.add(jlmSaldosContas);

        jlmEntradasCaixa.setText("Entrada Caixa");
        jlmEntradasCaixa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jlmEntradasCaixaActionPerformed(evt);
            }
        });
        jMenu7.add(jlmEntradasCaixa);

        jlmSaidasCaixa.setText("Saida Caixa");
        jlmSaidasCaixa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jlmSaidasCaixaActionPerformed(evt);
            }
        });
        jMenu7.add(jlmSaidasCaixa);

        jlmDepositosBancarios.setText("Deposito Bancario");
        jlmDepositosBancarios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jlmDepositosBancariosActionPerformed(evt);
            }
        });
        jMenu7.add(jlmDepositosBancarios);

        jlmLevantamentosBancarios.setText("Levantamento Bancario");
        jlmLevantamentosBancarios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jlmLevantamentosBancariosActionPerformed(evt);
            }
        });
        jMenu7.add(jlmLevantamentosBancarios);

        jlmTransferenciasBancarias.setText("Transferencias Bancarias");
        jlmTransferenciasBancarias.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jlmTransferenciasBancariasActionPerformed(evt);
            }
        });
        jMenu7.add(jlmTransferenciasBancarias);

        jMenuItem26.setText("Sair");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem26);

        jMenuItem27.setText("Terminar Sessão");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem27);

        jMenuBar1.add(jMenu7);

        jMenu10.setText("Relatórios");

        jlmRelatoriosDeEntradasNoCaixa.setText("Relatorios de Entradas no Caixa");
        jlmRelatoriosDeEntradasNoCaixa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jlmRelatoriosDeEntradasNoCaixaActionPerformed(evt);
            }
        });
        jMenu10.add(jlmRelatoriosDeEntradasNoCaixa);

        jlmRelatoriosDeSaidasDoCaixa.setText("Relatorios de Saidas do Caixa");
        jlmRelatoriosDeSaidasDoCaixa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jlmRelatoriosDeSaidasDoCaixaActionPerformed(evt);
            }
        });
        jMenu10.add(jlmRelatoriosDeSaidasDoCaixa);

        jlmRelatoriosDeEntradasNoCaixa1.setText("Relatorios de Depósitos");
        jlmRelatoriosDeEntradasNoCaixa1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jlmRelatoriosDeEntradasNoCaixa1ActionPerformed(evt);
            }
        });
        jMenu10.add(jlmRelatoriosDeEntradasNoCaixa1);

        jlmRelatoriosDeEntradasNoCaixa2.setText("Relatorios de Levantamentos");
        jlmRelatoriosDeEntradasNoCaixa2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jlmRelatoriosDeEntradasNoCaixa2ActionPerformed(evt);
            }
        });
        jMenu10.add(jlmRelatoriosDeEntradasNoCaixa2);

        jlmExtratoDeMovimentosBancarios.setText("Extrato de Movimentos Bancarios");
        jlmExtratoDeMovimentosBancarios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jlmExtratoDeMovimentosBancariosActionPerformed(evt);
            }
        });
        jMenu10.add(jlmExtratoDeMovimentosBancarios);

        jMenuItem3.setText("Mapa do Balanco");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem3);

        jMenuItem4.setText("Reimprimir Entrada de Caixa");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem4);

        jMenuItem5.setText("Reimprimir Saida de Caixa");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem5);

        jMenuItem6.setText("Reimprimir Adiantamento de Caixa");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem6);

        jMenuBar1.add(jMenu10);

        jMenu1.setText("Tabela");

        jMenuItem2.setText("Novo Banco");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Ajuda");

        jMenuItem9.setText("Sobre o Autor");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlmSaldosContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlmSaldosContasActionPerformed
        new SaldoBanco().show();
    }//GEN-LAST:event_jlmSaldosContasActionPerformed

    private void jlmEntradasCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlmEntradasCaixaActionPerformed
        new EntradaTesourariaVisao(idUser).show();
    }//GEN-LAST:event_jlmEntradasCaixaActionPerformed

    private void jlmSaidasCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlmSaidasCaixaActionPerformed
        new SaidaTesourariaVisao(idUser).show();
    }//GEN-LAST:event_jlmSaidasCaixaActionPerformed

    private void jlmDepositosBancariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlmDepositosBancariosActionPerformed
        new DepositoBancarioVisao(idUser).show();
    }//GEN-LAST:event_jlmDepositosBancariosActionPerformed

    private void jlmLevantamentosBancariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlmLevantamentosBancariosActionPerformed
        new LevantamentoBancarioVisao(idUser).show();
    }//GEN-LAST:event_jlmLevantamentosBancariosActionPerformed

    private void jlmTransferenciasBancariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlmTransferenciasBancariasActionPerformed
        new TransferenciasBancarias(idUser).show();
    }//GEN-LAST:event_jlmTransferenciasBancariasActionPerformed

    private void jlmRelatoriosDeEntradasNoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlmRelatoriosDeEntradasNoCaixaActionPerformed
        new RelatorioEntradasVisao().show();
    }//GEN-LAST:event_jlmRelatoriosDeEntradasNoCaixaActionPerformed

    private void jlmRelatoriosDeSaidasDoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlmRelatoriosDeSaidasDoCaixaActionPerformed
        new RelatorioSaidasVisao().show();
    }//GEN-LAST:event_jlmRelatoriosDeSaidasDoCaixaActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        dispose();
//        MetodosUtil.fechar_todas_janelas();
//        MetodosUtil.actualizar_status(  this.id_user  , "OFF");
//        MetodosUtil.actualizar_ip_address(this.id_user , "");
       // new LoginVisao().show();
         new RootVisao(this.idUser, this.idEmpresa, true, this.conexao).show();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        dispose();
        new LoginVisao(new BDConexao()).setVisible( true);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jlmExtratoDeMovimentosBancariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlmExtratoDeMovimentosBancariosActionPerformed
        new RelatorioExtratoVisao().show();
    }//GEN-LAST:event_jlmExtratoDeMovimentosBancariosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new BancoVisao().show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        new InformacoesEmpresaVisao().show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
       new   RelatorioBalancoVisao().show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new ReemprimirEntradaTesourariaVisao().show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new ReemprimirSaidaTesourariaVisao().show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new ReemprimirAdiantamentoVisao().show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jlmRelatoriosDeEntradasNoCaixa1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jlmRelatoriosDeEntradasNoCaixa1ActionPerformed
    {//GEN-HEADEREND:event_jlmRelatoriosDeEntradasNoCaixa1ActionPerformed
       new RelatorioDepositosVisao().show();
    }//GEN-LAST:event_jlmRelatoriosDeEntradasNoCaixa1ActionPerformed

    private void jlmRelatoriosDeEntradasNoCaixa2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jlmRelatoriosDeEntradasNoCaixa2ActionPerformed
    {//GEN-HEADEREND:event_jlmRelatoriosDeEntradasNoCaixa2ActionPerformed
        new RelatorioLevantamentosVisao().show();
    }//GEN-LAST:event_jlmRelatoriosDeEntradasNoCaixa2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTesourariaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTesourariaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTesourariaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTesourariaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalTesourariaVisao(1, 1, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jlmDepositosBancarios;
    private javax.swing.JMenuItem jlmEntradasCaixa;
    private javax.swing.JMenuItem jlmExtratoDeMovimentosBancarios;
    private javax.swing.JMenuItem jlmLevantamentosBancarios;
    private javax.swing.JMenuItem jlmRelatoriosDeEntradasNoCaixa;
    private javax.swing.JMenuItem jlmRelatoriosDeEntradasNoCaixa1;
    private javax.swing.JMenuItem jlmRelatoriosDeEntradasNoCaixa2;
    private javax.swing.JMenuItem jlmRelatoriosDeSaidasDoCaixa;
    private javax.swing.JMenuItem jlmSaidasCaixa;
    private javax.swing.JMenuItem jlmSaldosContas;
    private javax.swing.JMenuItem jlmTransferenciasBancarias;
    private javax.swing.JLabel lb_descricao_software;
    private javax.swing.JLabel lb_nome_software;
    // End of variables declaration//GEN-END:variables



}
