/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tesouraria.visao;


import java.sql.Connection;
import visao.*;
//import dao.BancoDao;
import dao.SaidaDao;
import dao.UsuarioDao;
//import entity.TbBanco;
//import static entity.PropinaMirrow_.idRecibo;
import entity.SaidasTesouraria;
import java.util.Date;
import java.util.Vector;
import javax.persistence.EntityManagerFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import lista.RelatorioSaidaCaixa;
import util.BDConexao;
import util.DVML;
import util.JPAEntityMannagerFactoryUtil;
import util.MetodosUtil;
import util.OperacaoSistemaUtil;
import util.PermitirNumeros;

/**
 *
 * @author macpro
 */
public class SaidaTesourariaVisao extends javax.swing.JFrame
{

    private EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;
    private SaidaDao saidaDao = new SaidaDao( emf );
    private SaidasTesouraria saidasTesouraria;
    private UsuarioDao usuarioDao = new UsuarioDao( emf );
//    private BancoDao bancoDao = new BancoDao(emf);
    private BDConexao conexao;
    private int idUser;
    private OperacaoSistemaUtil osu = new OperacaoSistemaUtil();

    /**
     * Creates new form EntradaTesourariaVisao
     */
    public SaidaTesourariaVisao( int idUser )
    {
        initComponents();
        this.idUser = idUser;
        setLocationRelativeTo( null );
        conexao = BDConexao.getInstancia();
        actualizar();
        txtValorSair.setDocument( new PermitirNumeros() );
        txtValorSair.setText( "0" );
    }

    private void actualizar()
    {
//       cmbBanco.setModel(   new DefaultComboBoxModel( (Vector) bancoDao.buscaTodosCaixaLocal() ) );
//       cmbBanco.setModel(   new DefaultComboBoxModel( (Vector) bancoDao.buscaTodos() ) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValorSair = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        btn_enviar = new javax.swing.JButton();
        BT_Eliminar = new javax.swing.JButton();
        BT_Sair = new javax.swing.JButton();
        cmbBanco = new javax.swing.JComboBox<>();
        status_mensagem_primaria = new javax.swing.JLabel();
        status_mensagem_secundaria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("   FORMULÁRIO  DE  SAÍDAS  DE  VALORES  DO  CAIXA");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("VALOR  A  SAÍR :");

        txtValorSair.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtValorSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorSairActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("DESCRIÇÃO :");

        taDescricao.setColumns(20);
        taDescricao.setRows(5);
        jScrollPane1.setViewportView(taDescricao);

        btn_enviar.setText("ENVIAR");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        BT_Eliminar.setText("ELIMINAR");
        BT_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EliminarActionPerformed(evt);
            }
        });

        BT_Sair.setText("SAÍR");
        BT_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SairActionPerformed(evt);
            }
        });

        cmbBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        status_mensagem_primaria.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        status_mensagem_primaria.setForeground(new java.awt.Color(204, 153, 0));
        status_mensagem_primaria.setText("sahdbvhsdva");

        status_mensagem_secundaria.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        status_mensagem_secundaria.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtValorSair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(BT_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(BT_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status_mensagem_primaria, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status_mensagem_secundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status_mensagem_primaria)
                .addGap(16, 16, 16)
                .addComponent(status_mensagem_secundaria)
                .addGap(3, 3, 3)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorSair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_EliminarActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        procedimento_salvar();
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void BT_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SairActionPerformed
        dispose();
    }//GEN-LAST:event_BT_SairActionPerformed

    private void txtValorSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorSairActionPerformed
        taDescricao.requestFocus();
    }//GEN-LAST:event_txtValorSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( SaidaTesourariaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( SaidaTesourariaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( SaidaTesourariaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( SaidaTesourariaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new SaidaTesourariaVisao( 1 ).setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Eliminar;
    private javax.swing.JButton BT_Sair;
    public static javax.swing.JButton btn_enviar;
    private javax.swing.JComboBox<String> cmbBanco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel status_mensagem_primaria;
    public static javax.swing.JLabel status_mensagem_secundaria;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextField txtValorSair;
    // End of variables declaration//GEN-END:variables

    public boolean validar_numero_menor()
    {
//        if(txtValorTranferencia.getText() != null){
        if ( Double.parseDouble( txtValorSair.getText().trim() ) == 0 )
        {
            JOptionPane.showMessageDialog( null, "Atenção\nInsira o valor a Saír do Caixa!" );
            txtValorSair.requestFocus();
            return false;
        }
        return true;

    }

    public boolean validar_descricao()
    {
//        if(txtValorTranferencia.getText() != null){
        if ( taDescricao.getText().equals( "" ) )
        {
            JOptionPane.showMessageDialog( null, "Atenção\nDigite a descrição da Saída do Valor!" );
            taDescricao.requestFocus();
            return false;
        }
        return true;

    }

    public boolean validar_valor_saldo()
    {

        if ( ( Double.parseDouble( txtValorSair.getText() ) ) > MetodosUtil.getSaldoByBanco( DVML.COD_BANCO_CAIXA ) )
        {
            JOptionPane.showMessageDialog( null, "Atenção\nO valor a Sair não pode ser superior ao saldo do Caixa!" );
            return false;
        }
        return true;
    }

    private void setarDadosSaidas()
    {

        try
        {

            saidasTesouraria = new SaidasTesouraria();
            setDadosSaidas();
            saidaDao.create( saidasTesouraria );
            MetodosUtil.subtrair_saldo_banco( saidasTesouraria.getValor(), DVML.COD_BANCO_CAIXA, conexao );
            JOptionPane.showMessageDialog( null, "Saída efectuada com sucesso!..." );
            // new RelatorioSaidaCaixa(idRecibo);
            limparDados();
        }
        catch ( Exception e )
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog( null, "Erro ao dar saída ", "ERRO", JOptionPane.ERROR_MESSAGE );
        }

    }

    private void procedimento_salvar()
    {

        if ( validar_numero_menor() )
        {

            if ( validar_descricao() )
            {

                if ( validar_valor_saldo() )
                {

                    setarDadosSaidas();
                    try
                    {
                        new RelatorioSaidaCaixa( saidaDao.getUltimaSaida() );

                    }
                    catch ( Exception e )
                    {
                    }

                }

            }

        }

//                                    if(validar_numero_menor()){
//                                        
//                                    if(validar_descricao()){
//                                        
//                                    if(validar_valor_saldo()){
//            
//                                try {
//                                    int idRecibo = saidaDao.getUltimaSaida();
//                                    saidasTesouraria = new SaidasTesouraria();
//                                    setDadosSaidas();
//                                    saidaDao.create(saidasTesouraria);
//                                    new MetodosUtil().subtrair_caixa_banco(   saidasTesouraria.getValor()  );
//                                    JOptionPane.showMessageDialog(null, "Saída efectuada com sucesso!...");
//                                    new RelatorioSaidaCaixa(idRecibo);
//                                    limparDados();
//                        } catch (Exception e) {
//                            e.printStackTrace();
//                            JOptionPane.showMessageDialog(null, "Erro ao dar saída ", "ERRO", JOptionPane.ERROR_MESSAGE);
//                        }
//                                
//                    }
//                                    
//                                    
//                }
//                                    
//                                    
//            }                        
    }

    public void setDadosSaidas()
    {

        saidasTesouraria.setValor( Double.parseDouble( txtValorSair.getText() ) );
        saidasTesouraria.setDescricao( taDescricao.getText() );
        saidasTesouraria.setDataSaida( new Date() );
        saidasTesouraria.setHoraSaida( new Date() );
//        saidasTesouraria.setFkBanco(bancoDao.findTbBanco(getIdBanco()));
        saidasTesouraria.setFkUsuario( usuarioDao.findTbUsuario( idUser ) );

    }

    private int getIdBanco()
    {
        return 0;
    }

    private void limparDados()
    {

        txtValorSair.setText( "0" );
        taDescricao.setText( "" );

    }

}
