/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tesouraria.novo.visao;

import entity.TbUsuario;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import util.BDConexao;

/**
 *
 * @author Domingos Dala Vunge
 */
public class LinhaUsuarioVisao extends javax.swing.JPanel
{

    private String pathImage = "/tesouraria/image/user_priv_1_32.png";

    private TbUsuario usuario;
    private BDConexao conexao;

    public LinhaUsuarioVisao()
    {
        initComponents();
        setStyle( lbCod, "Cod." );
        setStyle( lbUsuario, "Usuário" );
        setStyle( lbTelefone, "Telefone" );
        setStyle( lbStatus, "Status" );
        setStyle( btnPermissoes, "Permissões" );
        btnPermissoes.setVisible( false );
    }

    public LinhaUsuarioVisao( TbUsuario usuario, Color fundo, BDConexao conexao )
    {
        initComponents();
        lbCod.setText( String.valueOf( usuario.getCodigo() ) );
        lbCod.setFont( new Font( "Arial", Font.PLAIN, 14 ) );

        lbUsuario.setText( usuario.getNome() );
        lbUsuario.setFont( new Font( "Arial", Font.PLAIN, 14 ) );

        lbTelefone.setText( usuario.getTelefone() );
        lbTelefone.setFont( new Font( "Arial", Font.PLAIN, 14 ) );

        lbStatus.setText( usuario.getStatus() );
        lbStatus.setFont( new Font( "Arial", Font.PLAIN, 14 ) );

        btnPermissoes.setIcon( new javax.swing.ImageIcon( getClass().getResource( pathImage ) ) );
        this.usuario = usuario;
        this.conexao = conexao;
        setBackground( fundo );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbCod = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        btnPermissoes = new javax.swing.JButton();

        lbCod.setText("Cod.");

        lbUsuario.setText("Usuário");

        lbTelefone.setText("Telefone");

        lbStatus.setText("Status");

        btnPermissoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesouraria/image/user_priv_1_32.png"))); // NOI18N
        btnPermissoes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPermissoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCod, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(btnPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPermissoes, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(lbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPermissoesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPermissoesActionPerformed
    {//GEN-HEADEREND:event_btnPermissoesActionPerformed
        // TODO add your handling code here:
        new PermissoesVisao( usuario, conexao ).setVisible( true );
    }//GEN-LAST:event_btnPermissoesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPermissoes;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbUsuario;
    // End of variables declaration//GEN-END:variables

    private void setStyle( Object object, String name )
    {

        if ( object instanceof JLabel )
        {
            JLabel l = ( JLabel ) object;
            l.setText( name );
            l.setFont( new Font( "Arial", Font.BOLD, 14 ) );
            l.setForeground( new Color( 255, 255, 255 ) );
            l.setBackground( new Color( 0, 51, 102 ) );
            l.setOpaque( true );
        }
        else if ( object instanceof JButton )
        {

            JButton button = ( JButton ) object;
            button.setText( name );
            button.setFont( new Font( "Arial", Font.BOLD, 14 ) );
            button.setBackground( new Color( 0, 51, 102 ) );
            button.setOpaque( true );

        }
    }

}
