/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import java.sql.Connection;
import dao.AmortizacaoDao;
import dao.UsuarioDao;
import dao.VendaDao;
import entity.Amortizacao;
import dao.AnoEconomicoDao;
import entity.Documento;
import dao.DocumentoDao;
import entity.AnoEconomico;
import entity.TbUsuario;
import entity.TbVenda;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import lista.ReciboAmortizacao;
import static util.DVML.DOC_RECIBO_RC;
import util.JPAEntityMannagerFactoryUtil;
import util.MetodosUtil;
import static visao.GestaoCreditos.procedimento_limpar_dados;

/**
 *
 * @author Domingos Dala Vunge
 */
public class AmortizacaoVisao extends javax.swing.JFrame
{
    
    private EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;
    private Amortizacao amortizacao;
    private DocumentoDao documentoDao = new DocumentoDao( emf );
    private AnoEconomico anoEconomico;
//    private static VendaDao vendaDao;
//    private AnoEconomicoDao anoEconomicoDao;
    private AnoEconomicoDao anoEconomicoDao = new AnoEconomicoDao( emf );
    private AmortizacaoDao amortizacaoDao = new AmortizacaoDao( emf );
    private UsuarioDao usuarioDao = new UsuarioDao( emf );
    private TbUsuario usuario;
    private VendaDao vendaDao = new VendaDao( emf );
    private Documento documento;
    private TbVenda tbvendas;
    private static String codFactura = "";
//    private static String codFactura = "";
//    private TbVenda facturas;
    private int idUser = 0;
    private String codFact = "";
    private double total_amortizacao = 0, valor_por_pagar = 0;
    List<Amortizacao> list_amortizacoes;

    public AmortizacaoVisao( int idUser, String codFact )
    {

        initComponents();
        setLocationRelativeTo( null );
        txtValorEntregue.addKeyListener( new TratarTroco() );
        this.idUser = idUser;
        this.codFact = codFact;
        txtValorEntregue.requestFocus();
        configuracaoCampos();

        txtValorEntregue.getDocument().addDocumentListener( new DocumentListener()
        {

            @Override
            public void insertUpdate( DocumentEvent e )
            {
                habilitarBotoes();
            }

            @Override
            public void removeUpdate( DocumentEvent e )
            {
            }

            @Override
            public void changedUpdate( DocumentEvent e )
            {
            }

        } );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        form_txt_total_amortizacao = new javax.swing.JFormattedTextField();
        form_txt_valor_por_pagar = new javax.swing.JFormattedTextField();
        lbFactura = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        form_txt_total_factura = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtValorEntregue = new javax.swing.JTextField();
        form_txt_diferenca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtRefDoc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnAmortizarCompleto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnAmortizarParte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Amortização de Factura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Factura:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Total das Amortizações:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Cliente:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Valor por Pagar:");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Valor  Entregue:");

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Total da Factura:");

        form_txt_total_amortizacao.setEditable(false);
        form_txt_total_amortizacao.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        form_txt_total_amortizacao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                form_txt_total_amortizacaoActionPerformed(evt);
            }
        });

        form_txt_valor_por_pagar.setEditable(false);
        form_txt_valor_por_pagar.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        form_txt_valor_por_pagar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                form_txt_valor_por_pagarActionPerformed(evt);
            }
        });

        lbFactura.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lbFactura.setText("Factura:");

        lbCliente.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lbCliente.setText("Factura:");

        form_txt_total_factura.setEditable(false);
        form_txt_total_factura.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        form_txt_total_factura.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                form_txt_total_facturaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("Diferença:");

        txtValorEntregue.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        txtValorEntregue.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtValorEntregueActionPerformed(evt);
            }
        });

        form_txt_diferenca.setEditable(false);
        form_txt_diferenca.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        form_txt_diferenca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                form_txt_diferencaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proucura.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Referência da Factura:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(form_txt_total_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(form_txt_diferenca, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(txtValorEntregue, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(form_txt_valor_por_pagar)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(form_txt_total_amortizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(lbCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRefDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRefDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(form_txt_total_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_txt_total_amortizacao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(form_txt_valor_por_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorEntregue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_txt_diferenca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        btnAmortizarCompleto.setText("Amortizar Completo");
        btnAmortizarCompleto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAmortizarCompletoActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        btnAmortizarParte.setText("Amortizar por Parte");
        btnAmortizarParte.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAmortizarParteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAmortizarParte, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAmortizarCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAmortizarParte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnAmortizarCompleto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void form_txt_total_amortizacaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_form_txt_total_amortizacaoActionPerformed
    {//GEN-HEADEREND:event_form_txt_total_amortizacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_txt_total_amortizacaoActionPerformed

    private void form_txt_valor_por_pagarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_form_txt_valor_por_pagarActionPerformed
    {//GEN-HEADEREND:event_form_txt_valor_por_pagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_txt_valor_por_pagarActionPerformed

    private void btnAmortizarCompletoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAmortizarCompletoActionPerformed
    {//GEN-HEADEREND:event_btnAmortizarCompletoActionPerformed
        // TODO add your handling code here:
        amortizar_completo();

    }//GEN-LAST:event_btnAmortizarCompletoActionPerformed

    private void form_txt_total_facturaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_form_txt_total_facturaActionPerformed
    {//GEN-HEADEREND:event_form_txt_total_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_txt_total_facturaActionPerformed

    private void txtValorEntregueActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtValorEntregueActionPerformed
    {//GEN-HEADEREND:event_txtValorEntregueActionPerformed
        // TODO add your handling code here:
        tratar_diferenca();
    }//GEN-LAST:event_txtValorEntregueActionPerformed

    private void form_txt_diferencaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_form_txt_diferencaActionPerformed
    {//GEN-HEADEREND:event_form_txt_diferencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_txt_diferencaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAmortizarParteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAmortizarParteActionPerformed
    {//GEN-HEADEREND:event_btnAmortizarParteActionPerformed
        // TODO add your handling code here:
        amortizar_por_parte();
    }//GEN-LAST:event_btnAmortizarParteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new DetalheAmortizacaoVisao( this, rootPaneCheckingEnabled, list_amortizacoes ).setVisible( true );
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( AmortizacaoVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( AmortizacaoVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( AmortizacaoVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( AmortizacaoVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AmortizacaoVisao( 15, "" ).setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmortizarCompleto;
    private javax.swing.JButton btnAmortizarParte;
    private javax.swing.JTextField form_txt_diferenca;
    private javax.swing.JFormattedTextField form_txt_total_amortizacao;
    private javax.swing.JFormattedTextField form_txt_total_factura;
    private javax.swing.JFormattedTextField form_txt_valor_por_pagar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbFactura;
    private static javax.swing.JTextField txtRefDoc;
    private javax.swing.JTextField txtValorEntregue;
    // End of variables declaration//GEN-END:variables

    private void config_mascara( JFormattedTextField campo )
    {
        try
        {
            DecimalFormat decimalFormat = new DecimalFormat( "#,###,###.00" );
            NumberFormatter numberFormatter = new NumberFormatter( decimalFormat );
            numberFormatter.setFormat( decimalFormat );
            numberFormatter.setAllowsInvalid( false );
            JFormattedTextField ft = new JFormattedTextField();
            campo.setFormatterFactory( new DefaultFormatterFactory( numberFormatter ) );

        }
        catch ( Exception e )
        {
        }
    }

    private void configuracaoCampos()
    {
        usuario = usuarioDao.findTbUsuario( this.idUser );
        config_mascara( form_txt_total_factura );
        config_mascara( form_txt_total_amortizacao );
        config_mascara( form_txt_valor_por_pagar );
        reset();

    }

    private void reset()
    {
        mostarCamposFactura();
        mostarCamposArmortizacao();
        mostrarValorPorPagar();
        txtValorEntregue.setText( "" );
        form_txt_diferenca.setText( "" );
        txtValorEntregue.requestFocus();
    }

    private void mostarCamposFactura()
    {

        tbvendas = vendaDao.findByCodFactura( this.codFact );
//         factura = vendaDao.findByCodFact1(this.idFactura);
        lbFactura.setText( tbvendas.getCodFact() );
        lbCliente.setText( tbvendas.getNomeCliente() );
        form_txt_total_factura.setText( MetodosUtil.getValorTransformadoString( tbvendas.getTotalVenda().doubleValue() ) );

    }

    private void mostarCamposArmortizacao()
    {
        list_amortizacoes = amortizacaoDao.getAllAmortizacaoByFactura( codFact );
        total_amortizacao = 0d;
        if ( !list_amortizacoes.isEmpty() )
        {

            for ( Amortizacao amortizacao_local : list_amortizacoes )
            {
                total_amortizacao += amortizacao_local.getValor();
            }
        }
        form_txt_total_amortizacao.setText( MetodosUtil.getValorTransformadoString( total_amortizacao ) );

    }

    private void mostrarValorPorPagar()
    {
        valor_por_pagar = ( (tbvendas.getTotalVenda().doubleValue()) - ( (total_amortizacao )));
        form_txt_valor_por_pagar.setText( MetodosUtil.getValorTransformadoString( valor_por_pagar ) );
    }

    private void tratar_diferenca()
    {
        double diferenca = ( Double.parseDouble( txtValorEntregue.getText() ) - valor_por_pagar );
        form_txt_diferenca.setText( MetodosUtil.getValorTransformadoString( diferenca ) );
    }

    private boolean camposValidos()
    {

        if ( txtValorEntregue.getText().equals( "" ) )
        {
            JOptionPane.showMessageDialog( null, "Caro usuário insira o valor entregue", "Aviso", JOptionPane.WARNING_MESSAGE );
            return false;
        }

        return true;
    }

    private void amortizar_por_parte()
    {
        TbVenda venda_local = getVenda();
        int opcao = JOptionPane.showConfirmDialog( null, "Caro usuário deseja amortizar a factura ? " );

        if ( opcao == JOptionPane.YES_OPTION )
        {

            amortizacao = new Amortizacao();
            amortizacao.setData( new Date() );
            amortizacao.setHora( new Date() );
            amortizacao.setValor( Double.parseDouble( txtValorEntregue.getText() ) );
//            amortizacao.getFkVenda().getCodFact();
            amortizacao.setFkVenda( tbvendas );
            amortizacao.setFkUsuario( usuario );
            
            amortizacao.setCodFact( getProximoDoc() );
            amortizacao.setRefCodFact( tbvendas.getCodFact() );
//            notas.setRefCodFact( venda_local.getCodFact() );
//            amortizacao.setFkDocumento( getDocumento() );


            
            try
            {
                amortizacaoDao.create( amortizacao );

                JOptionPane.showMessageDialog( null, "Amortização efectuada com sucesso!..." );

                mostarCamposArmortizacao();
                mostrarValorPorPagar();

                ReciboAmortizacao reciboAmortizacao = new ReciboAmortizacao( getCodVenda(),
                        valor_por_pagar,
                        total_amortizacao,
                        getValorEntregue(),
                        getDiferenca(),
                        amortizacao.getData(),
                        amortizacao.getFkUsuario().getNome()
                );
                reset();

            }
            catch ( Exception e )
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog( null, "Falha ao amortizar a factura", "Falha", JOptionPane.ERROR_MESSAGE );
            }
        }

    }
    
    private Documento getDocumento()
    {
        return new DocumentoDao().findDocumento( DOC_RECIBO_RC );
    }
    
    public int getIdDocumento()
    {
        try
        {
            return DOC_RECIBO_RC;
        }
        catch ( Exception e )
        {
            return 0;
        }
    }
    
    public TbVenda getVenda()
    {
        codFactura = txtRefDoc.getText();
        //String codFactura = (String) cmbFactura.getSelectedItem();
        return new VendaDao( emf ).findByCodFact( codFactura );
    }
    
//    private String getCodDocActualizador()
//    {
//        try
//        {
//            this.documento = documentoDao.findDocumento( getIdDocumento() );
//            this.anoEconomico = anoEconomicoDao.findAnoEconomico( getIdAnoEconomico() );
//            // this.doc_prox_cod = documento.getCodUltimoDoc() + 1;
//            this.doc_prox_cod = vendaDao.getUltimaContagemByIdDocumentoAndAnoEconomico( getIdDocumento(), getIdAnoEconomico(), conexao ) + 1;
//            prox_doc = documento.getAbreviacao();
//            //FA Série / codigo
//            prox_doc += " " + this.anoEconomico.getSerie() + "/" + this.doc_prox_cod;
//            return prox_doc;
//        }
//        catch ( Exception e )
//        {
//            return "";
//        }
//    }
    
    private String getProximoDoc()
    {
        try
        {
            Documento documento = getDocumento();
            int doc_prox_cod = documento.getCodUltimoDoc() + 1;
            //prox_doc = " " + documento.getAbreviacao();
            String prox_doc = documento.getAbreviacao();
            //FA Série / codigo
            prox_doc += " " + getAnoEconomicoSerie().getSerie() + "/" + doc_prox_cod;

            return prox_doc;

        }
        catch ( Exception e )
        {
            return null;
        }
    }
    
//    private Documento getDocumento()
//    {
//        return new DocumentoDao().findDocumento( DOC_RECIBO_RC );
//    }
    
    private AnoEconomico getAnoEconomicoSerie()
    {
        
        //return new AnoEconomicoDao().getLastObject();
        return getAnoEconomicoActual();
    }
    
    private AnoEconomico getAnoEconomicoActual()
    {
    
        List<AnoEconomico> list_ano_economico = anoEconomicoDao.buscaTodosObject();
        return  list_ano_economico.get( 0);
        
    }

    private void amortizar_completo()
    {

        int opcao = JOptionPane.showConfirmDialog( null, "Caro usuário deseja liquidar por completo ? " );

        if ( opcao == JOptionPane.YES_OPTION )
        {
            amortizacao = new Amortizacao();
            amortizacao.setData( new Date() );
            amortizacao.setHora( new Date() );
            amortizacao.setValor( Double.parseDouble( txtValorEntregue.getText() ) );
            amortizacao.setFkVenda( tbvendas );
            amortizacao.setFkUsuario( usuario );
//            amortizacao.setCodFact( getProximoDoc() );

            try
            {
                amortizacaoDao.create( amortizacao );
//                tbvendas = vendaDao.findTbVenda( Integer.parseInt( String.valueOf( this.codFact ) ) );
                tbvendas = vendaDao.findByCodFact(this.codFact )  ;
                tbvendas.setCredito( "false" );
                tbvendas.setDataVenda( new Date() );
                vendaDao.edit( tbvendas );

                JOptionPane.showMessageDialog( null, "Dívida liquida por completo." );
                GestaoCreditos.lista_vendas.clear();
                procedimento_limpar_dados();
                GestaoCreditos.adiciona_lista_clientes();
                GestaoCreditos.mostrar_total_geral();
                GestaoCreditos.mostrar_total_geral_cliente();
                GestaoCreditos.busca_factura_por_cliente();

                mostarCamposArmortizacao();
                mostrarValorPorPagar();
                dispose();
                ReciboAmortizacao reciboAmortizacao = new ReciboAmortizacao( getCodVenda(),
                        valor_por_pagar,
                        total_amortizacao,
                        getValorEntregue(),
                        getDiferenca(),
                        amortizacao.getData(),
                        amortizacao.getFkUsuario().getNome()
                );

            }
            catch ( Exception e )
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog( null, "Falha ao amortizar a factura", "Falha", JOptionPane.ERROR_MESSAGE );
            }
        }

    }

    private void habilitarBotoes()
    {
        double valor_entregue = Double.parseDouble( txtValorEntregue.getText() );

        boolean completo = valor_entregue >= valor_por_pagar;

        btnAmortizarCompleto.setVisible( completo );
        btnAmortizarParte.setVisible( !completo );

    }

    public double getValorEntregue()
    {
        return Double.parseDouble( txtValorEntregue.getText() );
    }

    public double getDiferenca()
    {
        return Double.parseDouble( form_txt_diferenca.getText() );
    }
    
//    public static TbVenda getVenda()
//    {
//        codFactura = txtRefDoc.getText();
//        //String codFactura = (String) cmbFactura.getSelectedItem();
//        return new VendaDao( emf ).findByCodFact( codFactura );
//    }

    class TratarTroco implements KeyListener
    {

        String prefixo = "";
        double total_pagar = 0;

        public void keyPressed( KeyEvent evt )
        {

            String prefixo = "";

            if ( evt.getKeyCode() != KeyEvent.VK_BACK_SPACE )
            {
                char key = evt.getKeyChar();
                prefixo = txtValorEntregue.getText().trim() + key;
                double troco = 0;
                double valor_entregue = Double.parseDouble( prefixo );
                // double total_pagar = valor_por_pagar;
                troco = valor_entregue - valor_por_pagar;
                form_txt_diferenca.setText( String.valueOf( MetodosUtil.retirar_dizimas( troco ) ) );

            }
            else if ( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE )
            {
                char key = evt.getKeyChar();

                prefixo = txtValorEntregue.getText() + key;

                double valor_entregue_1 = 0;
                double troco = 0;

                try
                {
                    valor_entregue_1 = Double.parseDouble( prefixo.toString().trim().substring( 0, prefixo.length() - 2 ) );
//                     total_pagar = valor_por_pagar;
                    troco = valor_entregue_1 - valor_por_pagar;
                }
                catch ( Exception e )
                {
                    valor_entregue_1 = 0;
                }

                troco = valor_entregue_1 - valor_por_pagar;
                form_txt_diferenca.setText( String.valueOf( MetodosUtil.retirar_dizimas( troco ) ) );

            }

            try
            {

                habilitarBotoes();
            }
            catch ( Exception e )
            {
            }

        }

        public void keyReleased( KeyEvent evt )
        {
        }

        public void keyTyped( KeyEvent evt )
        {
        }
    }

    private String getCodVenda()
    {
        return String.valueOf( vendaDao.findByCodFactura( codFact ).getCodigo() );

    }

}
