/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controller.PagamentoVendaCreditoController;
import controller.TipoProdutoController;
import controller.EntradaController;
import dao.ArmazemDao;
import dao.ProdutoDao;
import dao.UsuarioDao;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.GregorianCalendar;
import javax.persistence.EntityManagerFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.PagamentoVendaCreditoModelo;
import modelo.TipoProdutoModelo;

import modelo.EntradaModelo;
import modelo.ItemVendaModelo;
import util.BDConexao;
import util.JPAEntityMannagerFactoryUtil;
import util.OperacaoSistemaUtil;




/**
 *
 * @author Domingos Dala Vunge
 */
public class AnulamentoEntradaVisao extends javax.swing.JDialog {

    /**
     * Creates new form UsuarioVisao
     */
    
    
   
     private EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;
    private BDConexao conexao;
    private TipoProdutoModelo tipoProdutoModelo;
    private TipoProdutoController tipoProdutoController;
    private Frame parent;
    private int codigo = 0;
    private int  codigo_entrada = 0;
    private boolean eliminar = false;
    //ARMAZEM GERAL 
    private static int id_armzem = 1;
    private OperacaoSistemaUtil osu =  new OperacaoSistemaUtil();
    
    public AnulamentoEntradaVisao(java.awt.Frame parent, boolean modal) {
        //this.parent =  parent1;
        
        super(parent, modal);
        
        this.parent = parent;
        
        
        initComponents();
        confLabel();
        setLocationRelativeTo(null);
        
        tipoProdutoModelo = new TipoProdutoModelo();
        conexao = new BDConexao();
        tipoProdutoController = new TipoProdutoController(conexao);
        txtCodigoEntrada.addKeyListener( new TratarEventoTeclado() );
        
        
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        btn_eliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbFactura = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        txtCodigoEntrada = new javax.swing.JTextField();
        txtQtdEntrada = new javax.swing.JTextField();
        lbDataVenda = new javax.swing.JLabel();
        lbTotalVenda = new javax.swing.JLabel();
        txtArmazem = new javax.swing.JTextField();
        txtDataEntrada = new javax.swing.JTextField();
        lbProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        lbUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        status_mensagem_primaria = new javax.swing.JLabel();
        status_mensagem_secundaria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("...:::::  KITANDA - ANULAMENTO DE ENTRADA ::::...");
        setIconImage(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eliminar_32x32.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_eliminarActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ANULAMENTO DE ENTRADA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 153, 0))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N

        lbFactura.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbFactura.setText("Cod. Entrada");

        lbCliente.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbCliente.setText("Qtd Entrada");

        txtQtdEntrada.setEditable(false);
        txtQtdEntrada.setCaretColor(new java.awt.Color(255, 255, 255));

        lbDataVenda.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbDataVenda.setText("Data da Entrada:");

        lbTotalVenda.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbTotalVenda.setText("Armazém:");

        txtArmazem.setEditable(false);
        txtArmazem.setCaretColor(new java.awt.Color(255, 255, 255));

        txtDataEntrada.setEditable(false);
        txtDataEntrada.setCaretColor(new java.awt.Color(255, 255, 255));

        lbProduto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbProduto.setText("Produto");

        txtProduto.setEditable(false);

        lbUsuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbUsuario.setText("Usuário:");

        txtUsuario.setEditable(false);
        txtUsuario.setCaretColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbTotalVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDataVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQtdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFactura)
                    .addComponent(txtCodigoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduto)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCliente)
                    .addComponent(txtQtdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDataVenda)
                        .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTotalVenda))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        status_mensagem_primaria.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        status_mensagem_primaria.setForeground(new java.awt.Color(204, 153, 0));
        status_mensagem_primaria.setText("sahdbvhsdva");

        status_mensagem_secundaria.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        status_mensagem_secundaria.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status_mensagem_secundaria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status_mensagem_primaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status_mensagem_primaria)
                .addGap(16, 16, 16)
                .addComponent(status_mensagem_secundaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("CANCELAMENTO DE ENTRADA");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        
        int opcao = new JOptionPane().showConfirmDialog(null, "Tens a certeza que pretendes eliminar esta entrada ? ");
        
        if(opcao == JOptionPane.YES_OPTION)
        {
                procedimento_eliminar();
            
        }else JOptionPane.showMessageDialog(null, "Entrada não eliminada", "AVISO", JOptionPane.WARNING_MESSAGE );

        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnulamentoEntradaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnulamentoEntradaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnulamentoEntradaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnulamentoEntradaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnulamentoEntradaVisao dialog = new AnulamentoEntradaVisao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    
  
   
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_eliminar;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbDataVenda;
    private javax.swing.JLabel lbFactura;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JLabel lbTotalVenda;
    private javax.swing.JLabel lbUsuario;
    public static javax.swing.JLabel status_mensagem_primaria;
    public static javax.swing.JLabel status_mensagem_secundaria;
    private javax.swing.JTextField txtArmazem;
    public static javax.swing.JTextField txtCodigoEntrada;
    private javax.swing.JTextField txtDataEntrada;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtdEntrada;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables



   private void procedimento_eliminar()
   {
       
           try {
                       int cod_entrada =  Integer.parseInt(   txtCodigoEntrada.getText() );
                       actualizar_quantidade(cod_entrada);
                       //Elimnada a entrada
                       eliminar_entrada(  new EntradaController(conexao).getEntrada( cod_entrada )      );
                       //Actualiza a tabela
                       limpar();
                       //Emite a mensagemna tela
                       JOptionPane.showMessageDialog(null, "Entrada eliminada com sucesso!");
              
            } catch (Exception e) {
                e.printStackTrace();
                
            }
             
    }
       
    public void actualizar_quantidade(int cod_entrada){
    
             EntradaModelo entradaModelo = new EntradaController(conexao).getEntrada(cod_entrada);
             ItemVendaModelo itemVendaModelo;
             int quantidade = 0;
             quantidade =   BDConexao.getQuantidade_Existente(  entradaModelo.getIdProduto() , entradaModelo.getIdArmazemFK() ) -  entradaModelo.getQuantidade();   
             conexao.executeUpdate("UPDATE tb_stock SET quantidade_existente = " + quantidade +" WHERE cod_produto_codigo = " +entradaModelo.getIdProduto()  + " AND cod_armazem = " +entradaModelo.getIdArmazemFK() );
 
    }
    

   private void eliminar_entrada(EntradaModelo entradaModelo)
   {   
       try {
            entradaModelo.setData_entrada("2015-12-01");
            new EntradaController(conexao).operacao(3, entradaModelo, false);
           
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Erro ao eliminar a entrada", "ERRO", JOptionPane.ERROR_MESSAGE);
       }
       
   }
   
    public void confLabel()
    {          
        lbFactura.setHorizontalAlignment(JLabel.RIGHT);
        lbProduto.setHorizontalAlignment(JLabel.RIGHT);
        lbCliente.setHorizontalAlignment(JLabel.RIGHT);
        lbDataVenda.setHorizontalAlignment(JLabel.RIGHT);
        lbUsuario.setHorizontalAlignment(JLabel.RIGHT);
        lbTotalVenda.setHorizontalAlignment(JLabel.RIGHT);
  
    }
    
     public void limpar()
     {   
          txtCodigoEntrada.setText("");
          txtProduto.setText("");
          txtQtdEntrada.setText("");
          txtDataEntrada.setText("");
          txtArmazem.setText("");
          txtUsuario.setText("");
     }
     
    
    //CLASSE EVENTO TECLADO 
     //----------- evento do teclado ---------------------------------------
    class TratarEventoTeclado implements KeyListener
    {
        String prefixo = null;

        public void keyPressed(KeyEvent evt)
        {
            
            EntradaModelo entradaModelo = new EntradaModelo();
            EntradaController entradaController = new EntradaController(conexao);          
            ArmazemDao armazemDao = new ArmazemDao(emf);
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                char key = evt.getKeyChar();
                prefixo = txtCodigoEntrada.getText().trim() + key;
                
              try {
                  entradaModelo = new EntradaModelo();
                  
                  entradaModelo = entradaController.getEntrada(Integer.parseInt(txtCodigoEntrada.getText().trim())  );              
                  codigo_entrada = entradaModelo.getIdEntrada();
                  txtProduto.setText(     new ProdutoDao(emf).findTbProduto( entradaModelo.getIdProduto() ).getDesignacao() );
                  txtQtdEntrada.setText(    String.valueOf( entradaModelo.getQuantidade()  ) );
                  txtDataEntrada.setText(   entradaModelo.getData_entrada() );
                  txtArmazem.setText(  armazemDao.findTbArmazem( entradaModelo.getIdArmazemFK() ).getDesignacao()      );
                  txtUsuario.setText(  new UsuarioDao(emf).findTbUsuario( entradaModelo.getIdUsuario() ).getNome()      );
                  
              }catch (Exception e){
                  limpar();
                  eliminar = false;
                  JOptionPane.showMessageDialog(null, "Esta entrada nao existe!... Ou ja foi elimnada!...", "DVML-COMERCIAL, Lda", JOptionPane.WARNING_MESSAGE);
              }
              finally{
                  
                  eliminar = true;
              }
                        
            }
        }
        
        public void keyReleased(KeyEvent evt)
        {}
        public void keyTyped(KeyEvent evt)
        {}
        
    }



}

