/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import java.sql.Connection;
import comercial.controller.CaixasController;
import comercial.controller.DadosInstituicaoController;
import comercial.controller.DocumentosController;
import comercial.controller.FormaPagamentoController;
import comercial.controller.FormaPagamentoItemController;
import comercial.controller.ItemCaixaController;
import comercial.controller.UsuariosController;
import comercial.controller.VendasController;
import dao.FormaPagamentoDao;
import entity.Caixa;
import entity.FormaPagamento;
import entity.ItemCaixa;
import entity.TbDadosInstituicao;
import entity.TbUsuario;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lista.ReconciliacaoCaixaReport;
import util.BDConexao;
import util.DVML;
import util.JPAEntityMannagerFactoryUtil;

/**
 *
 * @author Domingos Dala Vunge
 */
public class CaixaFechoVisao extends javax.swing.JFrame
{

    private static EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;
    private static DadosInstituicaoController dadosInstituicaoController;
    private static CaixasController caixa_controller;
    private static ItemCaixaController item_caixa_controller;
    private static FormaPagamentoItemController formaPagamentoItemController;
    private static FormaPagamentoController formaPagamentoController;
    private static VendasController vendasController;
    private static UsuariosController usuariosController;
    private final FormaPagamentoDao formaPagamentoDao = new FormaPagamentoDao( emf );
    private int idUser;
    private static BDConexao conexao;
    private static BDConexao conexaoTransaction;
    private boolean touch;

    public CaixaFechoVisao( int idUser, BDConexao conexao, boolean touch )
    {
        initComponents();
        setLocationRelativeTo( null );
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation( dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2 );
        this.conexao = conexao;
        this.idUser = idUser;
        this.touch = touch;
        dadosInstituicaoController = new DadosInstituicaoController( CaixaFechoVisao.conexao );
        caixa_controller = new CaixasController( CaixaFechoVisao.conexao );
        item_caixa_controller = new ItemCaixaController( CaixaFechoVisao.conexao );
        formaPagamentoItemController = new FormaPagamentoItemController( CaixaFechoVisao.conexao );
        formaPagamentoController = new FormaPagamentoController( CaixaFechoVisao.conexao );
        usuariosController = new UsuariosController( CaixaFechoVisao.conexao );
        vendasController = new VendasController( CaixaFechoVisao.conexao );
        setNumeroCaixa();
        config();
        carregar_dados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lbFechoCaixa = new javax.swing.JLabel();
        lbFechoCaixa1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_fecho_caixa = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbFechoCaixa.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lbFechoCaixa.setText("FECHO DO CAIXA");

        lbFechoCaixa1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbFechoCaixa1.setText("Reconciliação de Caixa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFechoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFechoCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFechoCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFechoCaixa1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabela_fecho_caixa.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        tabela_fecho_caixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Cod.", "Vendas", "Valor Declarado"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabela_fecho_caixa.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tabela_fecho_caixaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_fecho_caixa);
        if (tabela_fecho_caixa.getColumnModel().getColumnCount() > 0)
        {
            tabela_fecho_caixa.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens32x32/actualizar_32x32.png"))); // NOI18N
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LOGOUT - VERMELHO/Logout 32x32.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:

        procedimento_fechar_caixa();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabela_fecho_caixaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tabela_fecho_caixaMouseClicked
    {//GEN-HEADEREND:event_tabela_fecho_caixaMouseClicked
        // TODO add your handling code here:
        if ( touch )
        {
            new TecladoNumeroPOSVisao( this, true, tabela_fecho_caixa, tabela_fecho_caixa.getSelectedRow(), tabela_fecho_caixa.getSelectedColumn(), DVML.NUMERO_TECLADO_FECHO_CAIXA ).setVisible( true );
        }
    }//GEN-LAST:event_tabela_fecho_caixaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( CaixaFechoVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( CaixaFechoVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( CaixaFechoVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( CaixaFechoVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new CaixaFechoVisao( 15, BDConexao.getInstancia(), false ).setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFechoCaixa;
    private javax.swing.JLabel lbFechoCaixa1;
    public static javax.swing.JTable tabela_fecho_caixa;
    // End of variables declaration//GEN-END:variables

//    private void procedimento_fechar_caixa()
//    {
//        conexaoTransaction = BDConexao.getInstancia();
//        DocumentosController.startTransaction( conexaoTransaction );
//
//        TbDadosInstituicao dadosInstituicao = (TbDadosInstituicao) dadosInstituicaoController.findById( 1 );
//        TbUsuario usuario = (TbUsuario) usuariosController.findById( this.idUser );
//        DefaultTableModel modelo = (DefaultTableModel) tabela_fecho_caixa.getModel();
//
//        int opcao = JOptionPane.showConfirmDialog( null, "Caro usuário deseja fechar realmente o caixa?" );
//        if ( JOptionPane.YES_OPTION == opcao )
//        {
//            boolean sucesso = true;
//            //Não existe fecho
//            if ( !caixa_controller.existe_fecho( idUser ) )
//            {
//                Caixa caixa_actual = caixa_controller.caixa_actual( idUser );
//                caixa_actual.setDataFecho( new Date() );
//                System.out.println( "DATA ABERTURA: " + caixa_actual.getDataAbertura() );
////                caixa_actual.setUsuarioFecho( usuariosController.getUsuarioByCodigo( this.idUser ).getNome() );
//
//                caixa_actual.setUsuarioFecho( usuario.getNome() );
//                caixa_actual.setCodUsuarioFecho( idUser );
//                caixa_actual.setNumeroVendas( formaPagamentoItemController.getNumeroVendasDiario( conexao, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho() ) );
//                BigDecimal valor = formaPagamentoItemController
//                .getValorRealDiario(conexao, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho());
//
//                BigDecimal troco = formaPagamentoItemController
//                .getTrocoRealDiario(conexao, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho());
//
//                BigDecimal totalDesconto = formaPagamentoItemController.getTotalDesconto( conexaoTransaction, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho() );
//                BigDecimal totalIva = formaPagamentoItemController.getTotalIva( conexaoTransaction, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho() );
//                BigDecimal totalIliquido = formaPagamentoItemController.getTotalIliquido( conexaoTransaction, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho() );
//
//                caixa_actual.setTotalVendas( valor.doubleValue() );
////                caixa_actual.setTotalVendas( valor - troco );
//
//                caixa_actual.setTotalDesconto( totalDesconto );
//                caixa_actual.setTotalIva( totalIva );
//                caixa_actual.setTotaIIliquido( totalIliquido );
//
//                try
//                {
//                    caixa_controller.actualizar( caixa_actual );
//
//                    System.out.println( "Data do fecho actualizada." );
//
//                    for ( int i = 0; i < tabela_fecho_caixa.getRowCount(); i++ )
//                    {
//                        Integer idFormaPagamento = Integer.parseInt( modelo.getValueAt( i, 0 ).toString() );
//                        Double valor_declarado = Double.parseDouble( modelo.getValueAt( i, 2 ).toString() );
//                        BigDecimal valor_real = formaPagamentoItemController
//                        .getValorRealDiarioByFormaPagamento(idUser, idFormaPagamento,
//                        caixa_actual.getDataAbertura(), caixa_actual.getDataFecho(), conexao);
//
//                        Double troco_real = formaPagamentoItemController.getTrocoRealDiario( idUser, idFormaPagamento,
//                                caixa_actual.getDataAbertura(),
//                                caixa_actual.getDataFecho(), conexao );
//
//                        ItemCaixa itemCaixa = new ItemCaixa();
//                        itemCaixa.setValorDeclarado( valor_declarado );
//                        itemCaixa.setValorReal( valor_real.doubleValue() );
////                        itemCaixa.setValorReal( valor_real - troco_real );
//                        itemCaixa.setFkFormaPagamento( formaPagamentoController.findByCodigo( idFormaPagamento ) );
//                        itemCaixa.setFkCaixa( caixa_actual );
//
//                        try
//                        {
//                            item_caixa_controller.salvar( itemCaixa );
//
//                        }
//                        catch ( Exception e )
//                        {
//                            sucesso = false;
//                            System.out.println( "Erro: " + e.getLocalizedMessage() );
//                        }
//
//                    }
//
//                }
//                catch ( Exception e )
//                {
//                }
//
//                if ( sucesso )
//                {
//                    modelo.setRowCount( 0 );
//                    JOptionPane.showMessageDialog( null, "Fecho realizado com sucesso" );
//                    DocumentosController.commitTransaction( conexaoTransaction );
//                    dispose();
//
////                    if ( ( dadosInstituicao.getMenuPrincipalByNegocio().equals( "Lavandaria" ) ) && ( usuario.getIdTipoUsuario().getIdTipoUsuario() == DVML.COD_TIPO_USUARIO_SUB_ADMINISTRADOR ) )
//                    if ( dadosInstituicao.getNegocio().equals( "Lavandaria" ) )
//                    {
////                        JanelaFrontOfficeLavandariaVisao.alterar_status_botao();
//                    }
//                    else
//                    {
//
//                        RootVisao.alterar_status_botao();
//
//                    }
////                    RootVisao.alterar_status_botao();
//                    try
//                    {
//
//                        /**
//                         * ENVIAR EMAIL
//                         */
//                        ReconciliacaoCaixaReport rb = new ReconciliacaoCaixaReport( caixa_actual.getPkCaixa(), conexaoTransaction );
////                        NLExporToPdfForSandEmailReport exporToPdfForSandEmailReport = new NLExporToPdfForSandEmailReport();
//
//                    }
//                    catch ( Exception e )
//                    {
//
//                        JOptionPane.showMessageDialog( null, "Falha ao processar os relatórios.\nFalha: " + e.getLocalizedMessage(),
//                                "Falha", JOptionPane.ERROR_MESSAGE );
//                        DocumentosController.rollback( conexaoTransaction );
//                        conexaoTransaction.close();
//                    }
//
//                }
//            }
//            else
//            {
//                System.out.println( "Nao fiz nada" );
//            }
//        }
//    }

    
    private void procedimento_fechar_caixa()
{
    conexaoTransaction = BDConexao.getInstancia();
    DocumentosController.start(conexaoTransaction);

    TbDadosInstituicao dadosInstituicao = (TbDadosInstituicao) dadosInstituicaoController.findById(1);
    TbUsuario usuario = (TbUsuario) usuariosController.findById(this.idUser);
    DefaultTableModel modelo = (DefaultTableModel) tabela_fecho_caixa.getModel();

    int opcao = JOptionPane.showConfirmDialog(null, "Caro usuário deseja fechar realmente o caixa?");
    if (JOptionPane.YES_OPTION == opcao)
    {
        boolean sucesso = true;

        if (!caixa_controller.existe_fecho(idUser))
        {
            Caixa caixa_actual = caixa_controller.caixa_actual(idUser);
            caixa_actual.setDataFecho(new Date());
            caixa_actual.setUsuarioFecho(usuario.getNome());
            caixa_actual.setCodUsuarioFecho(idUser);

            caixa_actual.setNumeroVendas(
                formaPagamentoItemController.getNumeroVendasDiario(conexao, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho())
            );

            BigDecimal valor = formaPagamentoItemController.getValorRealDiario(conexao, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho());
            BigDecimal troco = formaPagamentoItemController.getTrocoRealDiario(conexao, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho());
            BigDecimal totalDesconto = formaPagamentoItemController.getTotalDesconto(conexaoTransaction, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho());
            BigDecimal totalIva = formaPagamentoItemController.getTotalIva(conexaoTransaction, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho());
            BigDecimal totalIliquido = formaPagamentoItemController.getTotalIliquido(conexaoTransaction, idUser, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho());

            caixa_actual.setTotalVendas(valor.subtract(troco).doubleValue());
            caixa_actual.setTotalDesconto(totalDesconto);
            caixa_actual.setTotalIva(totalIva);
            caixa_actual.setTotaIIliquido(totalIliquido);

            try
            {
                caixa_controller.actualizar(caixa_actual);
                System.out.println("Caixa actualizado com sucesso. ID: " + caixa_actual.getPkCaixa());

                for (int i = 0; i < tabela_fecho_caixa.getRowCount(); i++)
                {
                    Integer idFormaPagamento = Integer.parseInt(modelo.getValueAt(i, 0).toString());

                    boolean existeVenda = formaPagamentoItemController.existeVendaDiarioByFormaPagamento(
                        idUser, idFormaPagamento,
                        caixa_actual.getDataAbertura(),
                        caixa_actual.getDataFecho(), conexaoTransaction
                    );

                    if (!existeVenda) {
                        System.out.println("Nenhuma venda encontrada para forma de pagamento ID: " + idFormaPagamento);
                        continue;
                    }

                    Double valor_declarado = Double.parseDouble(modelo.getValueAt(i, 2).toString());
                    BigDecimal valor_real = formaPagamentoItemController.getValorRealDiarioByFormaPagamento(
                        idUser, idFormaPagamento, caixa_actual.getDataAbertura(), caixa_actual.getDataFecho(), conexao
                    );

                    ItemCaixa itemCaixa = new ItemCaixa();
                    itemCaixa.setValorDeclarado(valor_declarado);
                    itemCaixa.setValorReal(valor_real.doubleValue());
                    itemCaixa.setFkFormaPagamento(formaPagamentoController.findByCodigo(idFormaPagamento));
                    itemCaixa.setFkCaixa(caixa_actual);

                    try
                    {
                        item_caixa_controller.salvar(itemCaixa);
                        System.out.println("ItemCaixa salvo com sucesso para forma de pagamento ID: " + idFormaPagamento);
                    }
                    catch (Exception e)
                    {
                        sucesso = false;
                        System.err.println("Erro ao salvar ItemCaixa: " + e.getMessage());
                        e.printStackTrace();
                    }
                }

            }
            catch (Exception e)
            {
                sucesso = false;
                e.printStackTrace();
            }

            if (sucesso)
            {
                modelo.setRowCount(0);
                JOptionPane.showMessageDialog(null, "Fecho realizado com sucesso!");
                DocumentosController.commit(conexaoTransaction);
                dispose();

                if (dadosInstituicao.getNegocio().equals("Lavandaria"))
                {
                    // JanelaFrontOfficeLavandariaVisao.alterar_status_botao();
                }
                else
                {
                    RootVisao.alterar_status_botao();
                }

                try
                {
                    ReconciliacaoCaixaReport rb = new ReconciliacaoCaixaReport(caixa_actual.getPkCaixa(), conexaoTransaction);
                    // NLExporToPdfForSandEmailReport exporToPdfForSandEmailReport = new NLExporToPdfForSandEmailReport();
                }
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Falha ao processar os relatórios.\nFalha: " + e.getLocalizedMessage(),
                            "Falha", JOptionPane.ERROR_MESSAGE);
                    DocumentosController.rollback(conexaoTransaction);
                    conexaoTransaction.close();
                }

            }
            else
            {
                DocumentosController.rollback(conexaoTransaction);
                JOptionPane.showMessageDialog(null, "Falha ao realizar o fecho de caixa!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            System.out.println("Fecho já existe. Nada foi feito.");
        }
    }
}

    
    
    private void config()
    {
        tabela_fecho_caixa.setRowHeight( 50 );
        tabela_fecho_caixa.setShowGrid( true );
        tabela_fecho_caixa.getTableHeader().setReorderingAllowed( false );

    }
//    VIZUALIZAR FORMA PAGAMENTO

    private void carregar_dados()
    {
        Caixa caixa_actual = caixa_controller.caixa_actual();
//        List<TbBanco> bancos = vendaDao.getAllBancos( caixa_actual.getDataAbertura(), caixa_actual.getDataFecho() );
        List<FormaPagamento> bancos = formaPagamentoDao.findFormaPagamentoEntities();
        DefaultTableModel modelo = (DefaultTableModel) tabela_fecho_caixa.getModel();
        modelo.setRowCount( 0 );
        for ( FormaPagamento banco : bancos )
        {
            modelo.addRow( new Object[]
            {
                banco.getPkFormaPagamento(),
                banco.getDesignacao(),
                0d
            } );
        }
    }

    private void setNumeroCaixa()
    {
        Caixa caixa_actual = caixa_controller.caixa_actual();
        lbFechoCaixa.setText( "FECHO DE CAIXA Nº " + ( caixa_actual.getPkCaixa() ) );
    }

}
