/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import comercial.controller.ClientesController;
import comercial.controller.ConfiguracaoMesComecoController;
import comercial.controller.DocumentosController;
import comercial.controller.FamiliasController;
import comercial.controller.MesRhController;
import comercial.controller.ProdutosController;
import comercial.controller.TipoProdutosController;
import controller.TipoClienteController;
import entity.ConfiguracaoMesComeco;
import entity.TbCliente;
import entity.TbProduto;
import entity.TbTipoProduto;
import java.awt.Color;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import static kitanda.util.CfMethodsSwing.resizeJButtonIcon;
import modelo.TipoClienteModelo;
import util.BDConexao;
import util.DVML;
import util.MetodosUtil;
import static util.MetodosUtil.normalizarEndereco;
import static util.MetodosUtil.normalizarNif;

/**
 *
 * @author DMartinho Luis
 */
public class ClienteVisao extends javax.swing.JDialog
{

    /**
     * Creates new form UsuarioVisao
     */
    private BDConexao conexao;
    private TipoClienteModelo tipoClienteModelo;
    private TipoClienteController tipoClienteController;
    private ClientesController clientesController;
    private TipoProdutosController tipoProdutoController;
    private FamiliasController familiaController;
    private static ConfiguracaoMesComecoController configuracaoMesComecoController;
    private static ProdutosController produtosController;
    private static MesRhController mesRhController;
    private static TbCliente clienteGlobal;
    private Frame parent;
    private int codigo = 0;

    public ClienteVisao( java.awt.Frame parent, boolean modal, BDConexao conexao )
    {
        //this.parent =  parent1;

        super( parent, modal );

        this.parent = parent;
        this.conexao = conexao;
        tipoClienteController = new TipoClienteController( conexao );
        clientesController = new ClientesController( conexao );
        produtosController = new ProdutosController( conexao );
        tipoProdutoController = new TipoProdutosController( conexao );
        mesRhController = new MesRhController( conexao.getConnectionAtiva() );
        familiaController = new FamiliasController( conexao );
        configuracaoMesComecoController = new ConfiguracaoMesComecoController( conexao.getConnectionAtiva() );
//        tipoClienteController = new ProdutosController( conexao );

        initComponents();
        postInitComponents();
        confLabel();
        setLocationRelativeTo( null );
//        txtInicias.addKeyListener( new TratarEvento() );

        cmbFamilia.setModel( new DefaultComboBoxModel( familiaController.getVector() ) );
        cmbFamilia.setSelectedIndex( 1 );
        cmbFamilia.setEnabled( false );
        cmbSubFamilia.setModel( new DefaultComboBoxModel( tipoProdutoController.getVector() ) );
        cmbProduto.setModel( new DefaultComboBoxModel( produtosController.getVector() ) );
        cmbMesComeco.setModel( new DefaultComboBoxModel( ( Vector ) mesRhController.getVector() ) );

        try
        {
            cmbSubFamilia.setModel( new DefaultComboBoxModel( tipoProdutoController.getVectorByIdFamilia( getIdFamilia() ) ) );
            cmbProduto.setModel( new DefaultComboBoxModel( ( produtosController.getVectorByIdTipoProduto( getIdTipoProduto() ) ) ) );
        }
        catch ( Exception e )
        {
        }

        txtNomeCliente.requestFocus();

    }

    public void confLabel()
    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbTipoProduto = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtContactos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNif = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cmbFamilia = new javax.swing.JComboBox<>();
        cmbSubFamilia = new javax.swing.JComboBox();
        cmbProduto = new javax.swing.JComboBox();
        lbProduto = new javax.swing.JLabel();
        lbCategoria1 = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        lbProduto1 = new javax.swing.JLabel();
        cmbMesComeco = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServicoMensalidade = new javax.swing.JTable();
        lbProduto2 = new javax.swing.JLabel();
        cmbDuracao = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbTipoProduto2 = new javax.swing.JLabel();
        txtProcNIF = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        lbTipoProduto3 = new javax.swing.JLabel();
        txtNomeCliente2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("...::::: DVML-CLIENTES::::...");
        setIconImage(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar_16x16.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setAlignmentX(0.5F);
        btnSalvar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_16x16.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setAlignmentX(0.5F);
        btnAlterar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAlterarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logout 32x32.png"))); // NOI18N
        btnCancelar.setText("Sair");
        btnCancelar.setAlignmentX(0.5F);
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eliminar_16x16.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setAlignmentX(0.5F);
        btnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_add_64px.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setAlignmentX(0.5F);
        btnNovo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 153, 0))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N

        lbTipoProduto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbTipoProduto.setText("Nome do Cliente:");

        txtNomeCliente.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNomeCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNomeClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        jLabel1.setText("Endereço:");

        txtEndereco.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEndereco.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtEnderecoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        jLabel2.setText("Tel:");

        txtContactos.setCaretColor(new java.awt.Color(255, 255, 255));
        txtContactos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtContactosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        jLabel3.setText("Nif:");

        txtNif.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNif.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNifActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        jLabel4.setText("Email:");

        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEmail.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbTipoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNif, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNomeCliente)
                            .addComponent(txtEndereco)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeCliente)
                    .addComponent(lbTipoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtContactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ficha do Cliente", jPanel3);

        cmbFamilia.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cmbFamilia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbFamiliaActionPerformed(evt);
            }
        });

        cmbSubFamilia.setBackground(new java.awt.Color(0, 255, 255));
        cmbSubFamilia.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cmbSubFamilia.setForeground(new java.awt.Color(0, 0, 51));
        cmbSubFamilia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSubFamilia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbSubFamiliaActionPerformed(evt);
            }
        });

        cmbProduto.setBackground(new java.awt.Color(0, 255, 255));
        cmbProduto.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cmbProduto.setForeground(new java.awt.Color(0, 0, 51));
        cmbProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProduto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbProdutoActionPerformed(evt);
            }
        });

        lbProduto.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbProduto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbProduto.setText("Serviço:");

        lbCategoria1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbCategoria1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCategoria1.setText("Sub Família:");

        lbCategoria.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCategoria.setText("Família:");

        lbProduto1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbProduto1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbProduto1.setText("Mês de Começo:");

        cmbMesComeco.setBackground(new java.awt.Color(0, 255, 255));
        cmbMesComeco.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cmbMesComeco.setForeground(new java.awt.Color(0, 0, 51));
        cmbMesComeco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccione--" }));
        cmbMesComeco.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbMesComecoActionPerformed(evt);
            }
        });

        tabelaServicoMensalidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Cod", "Servico", "Mes Começo", "Duração"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabelaServicoMensalidade.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tabelaServicoMensalidadeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaServicoMensalidade);
        if (tabelaServicoMensalidade.getColumnModel().getColumnCount() > 0)
        {
            tabelaServicoMensalidade.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        lbProduto2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbProduto2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbProduto2.setText("Duração:");

        cmbDuracao.setBackground(new java.awt.Color(0, 255, 255));
        cmbDuracao.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cmbDuracao.setForeground(new java.awt.Color(0, 0, 51));
        cmbDuracao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--seleccione--", "01 Mês", "02 Meses", "03 Meses", "04 Meses", "05 Meses", "06 Meses", "07 Meses", "8 Meses", "9 Meses", "10 Meses", "11 Meses", "12 Meses" }));
        cmbDuracao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbDuracaoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Button-Add-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbCategoria1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(lbCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbSubFamilia, 0, 366, Short.MAX_VALUE)
                                    .addComponent(cmbFamilia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(455, 455, 455))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDuracao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbMesComeco, 0, 237, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(412, 412, 412))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(cmbFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSubFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbMesComeco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inscrição de Serviços de  Mensalidades", jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbTipoProduto2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbTipoProduto2.setText("Cod.:");

        txtProcNIF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtProcNIFActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proucura.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        lbTipoProduto3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbTipoProduto3.setText("NIF:");

        txtNomeCliente2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNomeCliente2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbTipoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProcNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lbTipoProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lbTipoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtProcNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNomeCliente2)
                        .addComponent(lbTipoProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        procedimento_salvar();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        procedimento_alterar();

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        procedimento_eliminar();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        novo_cliente();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtNomeClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNomeClienteActionPerformed
    {//GEN-HEADEREND:event_txtNomeClienteActionPerformed
        txtEndereco.requestFocus();
    }//GEN-LAST:event_txtNomeClienteActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtEnderecoActionPerformed
    {//GEN-HEADEREND:event_txtEnderecoActionPerformed
        txtNif.requestFocus();
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtNifActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNifActionPerformed
    {//GEN-HEADEREND:event_txtNifActionPerformed
        txtContactos.requestFocus();
    }//GEN-LAST:event_txtNifActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtEmailActionPerformed
    {//GEN-HEADEREND:event_txtEmailActionPerformed
        procedimento_salvar();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtContactosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtContactosActionPerformed
    {//GEN-HEADEREND:event_txtContactosActionPerformed
        txtEmail.requestFocus();
    }//GEN-LAST:event_txtContactosActionPerformed

    private void cmbFamiliaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbFamiliaActionPerformed
    {//GEN-HEADEREND:event_cmbFamiliaActionPerformed

        cmbSubFamilia.setModel( new DefaultComboBoxModel( tipoProdutoController.getVectorByIdFamilia( getIdFamilia() ) ) );
        cmbProduto.setModel( new DefaultComboBoxModel( ( produtosController.getVectorByIdTipoProduto( getIdTipoProduto() ) ) ) );
    }//GEN-LAST:event_cmbFamiliaActionPerformed

    private void cmbSubFamiliaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbSubFamiliaActionPerformed
    {//GEN-HEADEREND:event_cmbSubFamiliaActionPerformed

        cmbProduto.setModel( new DefaultComboBoxModel( ( produtosController.getVectorByIdTipoProduto( getIdTipoProduto() ) ) ) );
    }//GEN-LAST:event_cmbSubFamiliaActionPerformed

    private void cmbProdutoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbProdutoActionPerformed
    {//GEN-HEADEREND:event_cmbProdutoActionPerformed
        // TODO add your handling code here:
        try
        {
            //  adicionar_preco_quantidade();
        }
        catch ( Exception e )
        {
        }
    }//GEN-LAST:event_cmbProdutoActionPerformed

    private void cmbMesComecoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbMesComecoActionPerformed
    {//GEN-HEADEREND:event_cmbMesComecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMesComecoActionPerformed

    private void txtProcNIFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtProcNIFActionPerformed
    {//GEN-HEADEREND:event_txtProcNIFActionPerformed
        // TODO add your handling code here:
        try
        {
            int cod = Integer.parseInt( txtProcNIF.getText() );
            clienteGlobal = clientesController.findByCodigo( cod );
            importarDados( clienteGlobal );
        }
        catch ( Exception e )
        {
            limparDadosForm();
        }

    }//GEN-LAST:event_txtProcNIFActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed

        try
        {
            new BuscaClienteVisao( parent, rootPaneCheckingEnabled, clientesController, conexao ).setVisible( true );
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNomeCliente2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNomeCliente2ActionPerformed
    {//GEN-HEADEREND:event_txtNomeCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCliente2ActionPerformed

    private void cmbDuracaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbDuracaoActionPerformed
    {//GEN-HEADEREND:event_cmbDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDuracaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        procedimentoAdicionarServico();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaServicoMensalidadeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tabelaServicoMensalidadeMouseClicked
    {//GEN-HEADEREND:event_tabelaServicoMensalidadeMouseClicked
        // TODO add your handling code here:
        setDadosForm();
    }//GEN-LAST:event_tabelaServicoMensalidadeMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        removerServicoMensalidade();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( ClienteVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( ClienteVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( ClienteVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( ClienteVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                ClienteVisao dialog = new ClienteVisao( new javax.swing.JFrame(), true, BDConexao.getInstancia() );
                dialog.addWindowListener( new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing( java.awt.event.WindowEvent e )
                    {
                        System.exit( 0 );
                    }
                } );
                dialog.setVisible( true );
            }
        } );
    }

    /* CRIACAO DO GETS  */
    public String getTipoCliente()
    {
        return txtNomeCliente.getText();
    }

    public String getMorada()
    {
        return txtEndereco.getText();
    }

    public String getTelefone()
    {
        return txtContactos.getText();
    }

    /*
     *   lbNome.setHorizontalAlignment(JLabel.RIGHT);
        lbSobreNome.setHorizontalAlignment(JLabel.RIGHT);
        lbUserName.setHorizontalAlignment(JLabel.RIGHT);
        lbSenha.setHorizontalAlignment(JLabel.RIGHT);
        lbConfirSenha.setHorizontalAlignment(JLabel.RIGHT);
        lbDataNascimento.setHorizontalAlignment(JLabel.RIGHT);
        lbTelefone.setHorizontalAlignment(JLabel.RIGHT);
        lbEmail.setHorizontalAlignment(JLabel.RIGHT);
        lbEndereco.setHorizontalAlignment(JLabel.RIGHT);
     
     */
 /*VALIDACOES */
    public void limpar()
    {

        txtNomeCliente.setText( "" );
        txtEndereco.setText( "" );
        txtContactos.setText( "" );
        txtNif.setText( "" );
        txtEmail.setText( "" );

//        txtInicias.setText( "" );
    }

    public boolean campos_invalidos()
    {
        Color backGround = Color.WHITE;
        Color foreGround = Color.BLACK;
        Color caretColor = Color.BLACK;

        if ( getTipoCliente().equals( "" ) )
        {
            txtNomeCliente.setBackground( backGround );
            txtNomeCliente.setForeground( foreGround );
            txtNomeCliente.setCaretColor( caretColor );
            JOptionPane.showMessageDialog( null, "Pf. Preêncha o campo Nome: " );
            return true;
        }
        else if ( getMorada().equals( "" ) )
        {

            txtEndereco.setBackground( backGround );
            txtEndereco.setForeground( foreGround );
            txtEndereco.setCaretColor( caretColor );
            JOptionPane.showMessageDialog( null, "Pf. Preêncha o campo Morada: " );
            return true;

        }
        else if ( getTelefone().equals( "" ) )
        {

            txtContactos.setBackground( backGround );
            txtContactos.setForeground( foreGround );
            txtContactos.setCaretColor( caretColor );
            JOptionPane.showMessageDialog( null, "Pf. Preêncha o campo Telefone: " );
            return true;

        }

        return false;
    }

//    int codigo, String nome, String morada, String telefone
    public void operacao( int operacao, String nomeCerto, String nomeErro ) throws SQLException
    {
        //(int codigo, String nome, String telefone, String email, String site, String enderreco)
        tipoClienteModelo = new TipoClienteModelo( codigo, getTipoCliente(), getMorada(), getTelefone() );
        if ( operacao != 3 )
        {

            if ( tipoClienteController.operacao( operacao, tipoClienteModelo ) )
            {
                JOptionPane.showMessageDialog( null, "DADOS   " + nomeCerto + " COM SUCESSO NA BD!..." );
                limpar();
            }
            else
            {
                JOptionPane.showMessageDialog( null, "ERRO AO " + nomeErro + "NA BD!...", "ERRO", JOptionPane.ERROR_MESSAGE );
            }

        }
        else
        {
            if ( tipoClienteController.operacao( operacao, tipoClienteModelo ) )
            {
                JOptionPane.showMessageDialog( null, "DADOS   " + nomeCerto + " COM SUCESSO NA BD!..." );
                limpar();
            }
            else
            {
                JOptionPane.showMessageDialog( null, "ERRO AO " + nomeErro + "NA BD!...", "ERRO", JOptionPane.ERROR_MESSAGE );
            }
        }

    }

    //CLASSE EVENTO TECLADO 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    public static javax.swing.JComboBox cmbDuracao;
    public static javax.swing.JComboBox<String> cmbFamilia;
    public static javax.swing.JComboBox cmbMesComeco;
    public static javax.swing.JComboBox cmbProduto;
    public static javax.swing.JComboBox cmbSubFamilia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCategoria1;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JLabel lbProduto1;
    private javax.swing.JLabel lbProduto2;
    private javax.swing.JLabel lbTipoProduto;
    private javax.swing.JLabel lbTipoProduto2;
    private javax.swing.JLabel lbTipoProduto3;
    private static javax.swing.JTable tabelaServicoMensalidade;
    public static javax.swing.JTextField txtContactos;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtEndereco;
    public static javax.swing.JTextField txtNif;
    public static javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeCliente2;
    private javax.swing.JTextField txtProcNIF;
    // End of variables declaration//GEN-END:variables

    private void procedimento_salvar()
    {

        BDConexao conexaoTransaction = BDConexao.getInstancia();
        DocumentosController.start( conexaoTransaction );
        clientesController = new ClientesController( conexaoTransaction );
        try
        {
            if ( validar() )
            {

                if ( !clientesController.existeClienteNome( txtNomeCliente.getText(), BDConexao.getConexao() ) )
                {

                    if ( !clientesController.existeClienteNIF( txtNif.getText(), BDConexao.getConexao() ) )
                    {
                        this.clienteGlobal = new TbCliente();
                        setDados();
                        try
                        {
                            clientesController.salvar( clienteGlobal );
                            DocumentosController.commit( conexaoTransaction );
                            limpar();
                            scrolltable();
                            btnNovo.setEnabled( true );
                            JOptionPane.showMessageDialog( null, "Cliente salvo com sucesso!...", DVML.DVML_COMERCIAL, JOptionPane.INFORMATION_MESSAGE );
                            txtNomeCliente.requestFocus();

                            if ( !Objects.isNull( NovaGestaoPedidosVisao.cmbCliente ) )
                            {
                                NovaGestaoPedidosVisao.cmbCliente.setModel( new DefaultComboBoxModel( clientesController.getVector() ) );
                                NovaGestaoPedidosVisao.cmbCliente.setSelectedItem( clienteGlobal.getNome() );
                                dispose();
                            }
                            if ( !Objects.isNull( FormVendaResponsivaVisaoTop.cmbCliente ) )
                            {
                                FormVendaResponsivaVisaoTop.cmbCliente.setModel( new DefaultComboBoxModel( clientesController.getVector() ) );
                                FormVendaResponsivaVisaoTop.cmbCliente.setSelectedItem( clienteGlobal.getNome() );
                                dispose();
                            }
                            if ( !Objects.isNull( RecolhaPedidosVisao.cmbCliente ) )
                            {
                                RecolhaPedidosVisao.cmbCliente.setModel( new DefaultComboBoxModel( clientesController.getVector() ) );
                                RecolhaPedidosVisao.cmbCliente.setSelectedItem( clienteGlobal.getNome() );
                                dispose();
                            }
                            if ( !Objects.isNull( VendaPOSVisao.cmbCliente ) )
                            {
                                VendaPOSVisao.cmbCliente.setModel( new DefaultComboBoxModel( clientesController.getVector() ) );
                                VendaPOSVisao.cmbCliente.setSelectedItem( clienteGlobal.getNome() );
                                dispose();
                            }
                            if ( !Objects.isNull( VendasPraticasVisao.cmbCliente ) )
                            {
                                VendasPraticasVisao.cmbCliente.setModel( new DefaultComboBoxModel( clientesController.getVector() ) );
                                VendasPraticasVisao.cmbCliente.setSelectedItem( clienteGlobal.getNome() );
                                dispose();
                            }

                        }
                        catch ( Exception e )
                        {
                            e.printStackTrace();
                            JOptionPane.showMessageDialog( null, "Erro ao salvar o cliente", DVML.DVML_COMERCIAL, JOptionPane.ERROR_MESSAGE );
                        }

                    }
                    else
                    {
                        JOptionPane.showMessageDialog( null, "Este NIF já existe.", DVML.DVML_COMERCIAL, JOptionPane.WARNING_MESSAGE );
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog( null, "Este Cliente já existe.", DVML.DVML_COMERCIAL, JOptionPane.WARNING_MESSAGE );
                }

            }
        }
        catch ( SQLException ex )
        {
            Logger.getLogger( ClienteVisao.class.getName() ).log( Level.SEVERE, null, ex );
        }
        
        conexaoTransaction.close();

    }

    public boolean validar()
    {

        if ( txtNomeCliente.getText().equalsIgnoreCase( "" ) )
        {
            JOptionPane.showMessageDialog( null, "Introduza o nome do Cliente!..." );
            return false;
        }
        if ( txtEndereco.getText().equalsIgnoreCase( "" ) )
        {
            JOptionPane.showMessageDialog( null, "Introduza o endereço do Cliente!..." );
            return false;
        }
        if ( txtNif.getText().equalsIgnoreCase( "" ) )
        {
            JOptionPane.showMessageDialog( null, "Introduza o NIF do Cliente!..." );
            return false;
        }
        return true;
    }

    private boolean valido()
    {

        if ( txtNomeCliente.getText().isEmpty() )
        {
            txtNomeCliente.requestFocus();
            JOptionPane.showMessageDialog( null, "Pf. digite o nome do cliente", DVML.DVML_COMERCIAL, JOptionPane.WARNING_MESSAGE );
            return false;
        }
//        else if( !clienteDao.nif_existente(txtNif.getText(), conexao)){
//            JOptionPane.showMessageDialog(null,"Impossivel alterar os dados porque não existe cliente cadastro com este nif.", "AVISO", JOptionPane.WARNING_MESSAGE);
//            return false;
//        }
        return true;

    }

    private void setDados()
    {

        String nomeMorada = normalizarEndereco( txtEndereco.getText() );
        String nif = normalizarNif( txtNif.getText() );

        clienteGlobal.setNome( txtNomeCliente.getText() );
        clienteGlobal.setMorada( nomeMorada );
        clienteGlobal.setNif( nif );
        this.clienteGlobal.setTelefone( txtContactos.getText() );
        this.clienteGlobal.setEmail( txtEmail.getText().trim() );

    }

    private void procedimento_alterar()
    {
        if ( valido() )
        {

            String nif = MetodosUtil.normalizarCampo( txtNif.getText() );;
            String nome = MetodosUtil.normalizarCampo( txtNomeCliente.getText() );

            if ( !clientesController.existeClienteNomeParaOutroCliente( nome,
                    clienteGlobal.getCodigo(),
                    BDConexao.getConnection() ) )
            {
                if ( !clientesController.existeClienteNIFParaOutroCliente( nif,
                        clienteGlobal.getCodigo(),
                        BDConexao.getConnection() ) )
                {
                    setDados();
                    try
                    {
                        clientesController.actualizar( clienteGlobal );
                        limpar();
                        JOptionPane.showMessageDialog( null, "Dados alterados com sucesso!...", DVML.DVML_COMERCIAL, JOptionPane.INFORMATION_MESSAGE );
                    }
                    catch ( Exception e )
                    {
                        JOptionPane.showMessageDialog( null, "Erro ao alteraer os dados", DVML.DVML_COMERCIAL, JOptionPane.ERROR_MESSAGE );
                    }

                }
                else
                {
                    JOptionPane.showMessageDialog( null,
                            "Já existe um cliente com este NIF na base de dados",
                            "Aviso",
                            JOptionPane.INFORMATION_MESSAGE );
                }
            }
            else
            {
                JOptionPane.showMessageDialog( null,
                        "Já existe um cliente com este nome na base de dados",
                        "Aviso",
                        JOptionPane.INFORMATION_MESSAGE );
            }

        }
    }

    private void procedimento_eliminar()
    {
        int opcao = JOptionPane.showConfirmDialog( null,
                "Tens a plena certeza que pretendes eliminar essa categria?" );
        if ( opcao == JOptionPane.YES_OPTION )
        {
            try
            {
                clientesController.eliminar( codigo );
                limpar();
                JOptionPane.showMessageDialog( null,
                        "Cliente eliminado com sucesso!...",
                        DVML.DVML_COMERCIAL,
                        JOptionPane.INFORMATION_MESSAGE );
            }
            catch ( Exception e )
            {

                e.printStackTrace();
                JOptionPane.showMessageDialog( null, "Erro ao eliminar este Cliente.\nPossivelmente já esta realcionado com algumas vendas.", DVML.DVML_COMERCIAL, JOptionPane.ERROR_MESSAGE );
            }
        }
    }

    private void novo_cliente()
    {
        habilitar_campos( true );
        limpar();
        txtNomeCliente.requestFocus();
        btnNovo.setEnabled( false );
    }

    private void proteger_campos_excepto_nif()
    {

        txtNomeCliente.setEnabled( false );
        txtEndereco.setEnabled( false );
        txtNif.setEnabled( true );
        txtContactos.setEnabled( false );
        txtEmail.setEnabled( false );
    }

    private void habilitar_campos( boolean status )
    {

        txtNomeCliente.setEnabled( status );
        txtEndereco.setEnabled( status );
        txtNif.setEnabled( status );
        txtContactos.setEnabled( status );
        txtEmail.setEnabled( status );
    }

    private void proteger_campos( boolean status )
    {

        txtNomeCliente.setEnabled( !status );
        txtEndereco.setEnabled( status );
        txtNif.setEnabled( status );
        txtContactos.setEnabled( status );
        txtEmail.setEnabled( status );

    }

    private void postInitComponents()
    {

        int tamanho = 20;
        resizeJButtonIcon( tamanho, tamanho, getClass().getResource( "/imagens/icons8_add_64px.png" ), btnNovo );
        DocumentListener listener = new DocumentListener()
        {

            @Override
            public void insertUpdate( DocumentEvent e )
            {
                actualizar_formulario();
            }

            @Override
            public void removeUpdate( DocumentEvent e )
            {
                actualizar_formulario();
            }

            @Override
            public void changedUpdate( DocumentEvent e )
            {
            }

        };
        btnSalvar.setEnabled( false );
        txtNomeCliente.getDocument().addDocumentListener( listener );
    }

    public void actualizar_formulario()
    {
        btnSalvar.setEnabled( validar_campos() );

    }

    private boolean validar_campos()
    {

        boolean nomeNaoVazio = !txtNomeCliente.getText().isEmpty();
        return nomeNaoVazio;
    }

    public void scrolltable()
    {

//        tabela_cliente.scrollRectToVisible( tabela_cliente.getCellRect( tabela_cliente.getRowCount() - 1, tabela_cliente.getColumnCount(), true ) );
    }

    private int getIdFamilia()
    {
        try
        {
            return familiaController.getFamiliaByDesignacao( String.valueOf( cmbFamilia.getSelectedItem() ) ).getPkFamilia();
        }
        catch ( Exception e )
        {
            return 0;
        }
    }

    private int getIdTipoProduto()
    {
        try
        {
            return tipoProdutoController.getTipoFamiliaByDesignacao( String.valueOf( cmbSubFamilia.getSelectedItem() ) ).getCodigo();
        }
        catch ( Exception e )
        {
            return 0;
        }

    }

    public static void importarDados( TbCliente cliente )
    {
        clienteGlobal = cliente;
        txtNomeCliente.setText( clienteGlobal.getNome() );
        txtEndereco.setText( clienteGlobal.getMorada() );
        txtNif.setText( clienteGlobal.getNif() );
        txtContactos.setText( clienteGlobal.getTelefone() );
        txtEmail.setText( clienteGlobal.getEmail() );
        adicionarServicos();
    }

    public static void limparDadosForm()
    {
        txtNomeCliente.setText( "" );
        txtEndereco.setText( "" );
        txtNif.setText( "" );
        txtContactos.setText( "" );
        txtEmail.setText( "" );
        clienteGlobal = null;
    }

    private void procedimentoAdicionarServico()
    {
        String servicoSelecionado = cmbProduto.getSelectedItem().toString().trim();

        DefaultTableModel model = ( DefaultTableModel ) tabelaServicoMensalidade.getModel();

        // Verifica se o serviço já foi adicionado
        for ( int i = 0; i < model.getRowCount(); i++ )
        {
            String servicoExistente = model.getValueAt( i, 1 ).toString().trim(); // coluna 1 = Serviço

            if ( servicoExistente.equalsIgnoreCase( servicoSelecionado ) )
            {
                JOptionPane.showMessageDialog( null,
                        "Este serviço já foi adicionado!",
                        "Aviso", JOptionPane.WARNING_MESSAGE );
                return; // Cancela o procedimento
            }
        }

        // Se não houver duplicação, continua normalmente
        ConfiguracaoMesComeco cmc = new ConfiguracaoMesComeco();
        cmc.setDataCadastro( new Date() );
        cmc.setMesId( cmbMesComeco.getSelectedIndex() + 1 );
        cmc.setProdutoId( getCodigoProduto() );
        cmc.setUsuarioId( 0 );
        cmc.setDuracao( cmbDuracao.getSelectedIndex() );
        cmc.setClienteId( clienteGlobal.getCodigo() );

        if ( configuracaoMesComecoController.salvar( cmc ) )
        {
            adicionarServicos();
            JOptionPane.showMessageDialog( null, "Serviço configurado com sucesso!" );
        }
        else
        {
            JOptionPane.showMessageDialog( null, "Erro ao configurar o serviço",
                    "Falha", JOptionPane.ERROR_MESSAGE );
        }
    }

    private void setDadosForm()
    {
        DefaultTableModel modelo = ( DefaultTableModel ) tabelaServicoMensalidade.getModel();
        int linhaSelecionada = tabelaServicoMensalidade.getSelectedRow();

        String cod = modelo.getValueAt( linhaSelecionada, 0 ).toString();
        String mes = modelo.getValueAt( linhaSelecionada, 2 ).toString();
        String duracao = modelo.getValueAt( linhaSelecionada, 3 ).toString();
        ConfiguracaoMesComeco item = configuracaoMesComecoController.buscarPorId( Integer.parseInt( cod ) );

        TbProduto produto = produtosController.findByCod( item.getProdutoId() );
        int idSubFamilia = produto.getCodTipoProduto().getCodigo();
        TbTipoProduto tipoProduto = ( TbTipoProduto ) tipoProdutoController.findById( idSubFamilia );
        cmbSubFamilia.setSelectedItem( tipoProduto.getDesignacao() );
        cmbProduto.setSelectedItem( produto.getDesignacao() );

        cmbDuracao.setSelectedItem( duracao );
        cmbMesComeco.setSelectedItem( mes );

    }

    private static void adicionarServicos()
    {

        if ( Objects.nonNull( clienteGlobal ) )
        {
            DefaultTableModel modelo = ( DefaultTableModel ) tabelaServicoMensalidade.getModel();
            modelo.setRowCount( 0 );
            List<ConfiguracaoMesComeco> listarTodos = configuracaoMesComecoController.listarTodos( clienteGlobal.getCodigo() );

            for ( ConfiguracaoMesComeco item : listarTodos )
            {

                String servico = produtosController.findByCod( item.getProdutoId() ).getDesignacao();
                String mesComeco = mesRhController.getDescricaoByIdMes( item.getMesId() );

                modelo.addRow( new Object[]
                {
                    item.getId(),
                    servico,
                    mesComeco,
                    MetodosUtil.getNumeroFormatado( item.getDuracao() )
                    + " " + getMesDesignacao( item.getDuracao() )
                } );
            }

        }

    }

    private static String getMesDesignacao( int id )
    {
        return ( id > 1 ) ? "Meses" : "Mês";
    }

    public int getCodigoProduto()
    {
        return produtosController.findByDesignacao(
                cmbProduto.getSelectedItem().toString() ).getCodigo();
    }

    private void removerServicoMensalidade()
    {
        try
        {
            DefaultTableModel modelo = ( DefaultTableModel ) tabelaServicoMensalidade.getModel();
            int selectedRow = tabelaServicoMensalidade.getSelectedRow();
            int id = Integer.parseInt( modelo.getValueAt( selectedRow, 0 ).toString() );
            boolean deletar = configuracaoMesComecoController.deletar( id );
            if ( deletar )
            {
                MetodosUtil.remover_item_tabela( tabelaServicoMensalidade, selectedRow );
            }
        }
        catch ( Exception e )
        {
            JOptionPane.showMessageDialog( null, "Falha ao remover o serviço!" );
        }

    }

}
