/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import comercial.controller.FamiliasController;
import comercial.controller.MultaServicoController;
import comercial.controller.ProdutosController;
import comercial.controller.TipoProdutosController;
import comercial.controller.UsuariosController;
import entity.MultaServico;
import entity.TbProduto;
import entity.TbUsuario;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.BDConexao;
import util.DVML;
import util.MetodosUtil;

/**
 *
 * @author Domingos Dala Vunge
 */
public class ConfiguracaoMultasVisao extends javax.swing.JDialog
{

    private int idUser;
    private BDConexao conexao;
    private static ProdutosController produtosController;
    private static MultaServicoController multaServicoController;
    private static UsuariosController usuarioController;
    private static TipoProdutosController tipoProdutosController;
    private static FamiliasController familiasController;
    private static int codProduto;
    private int codArmazem;
    private Map<Integer, String> produtosMap = new HashMap<>();
    private MultaServico multa;
    private TbUsuario usuario;

    private int size_old = 0;

    public ConfiguracaoMultasVisao( int idUser, int codProduto, int codArmazem, BDConexao conexao )
    {
        initComponents();
        setLocationRelativeTo( null );
        this.conexao = conexao;
        this.idUser = idUser;
        this.codProduto = codProduto;
        this.codArmazem = codArmazem;
        produtosController = new ProdutosController( conexao );
        multaServicoController = new MultaServicoController( conexao );
        usuarioController = new UsuariosController( conexao );
        tipoProdutosController = new TipoProdutosController( conexao );
        produtosController = new ProdutosController( conexao );
        familiasController = new FamiliasController( conexao );
        try
        {

            cmbFamilia.setModel( new DefaultComboBoxModel( familiasController.getVector() ) );
            cmbFamilia.setSelectedIndex( 1 );
            cmbSubFamilia.setModel( new DefaultComboBoxModel( tipoProdutosController.getVectorByIdFamilia( getIdFamilia() ) ) );
            cmbProduto.setModel( new DefaultComboBoxModel( ( produtosController.getVectorByIdTipoProduto( getIdTipoProduto() ) ) ) );
        }
        catch ( Exception e )
        {
        }

        try
        {
            procedimento_adcionar_dados_tabela();
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lbProduto = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMulta = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbSubFamilia = new javax.swing.JComboBox();
        cmbProduto = new javax.swing.JComboBox();
        cmbFamilia = new javax.swing.JComboBox<>();
        lbCategoria = new javax.swing.JLabel();
        lbCategoria1 = new javax.swing.JLabel();
        lbCategoria2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MULTAS");

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbProduto.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbProduto.setForeground(new java.awt.Color(255, 255, 255));
        lbProduto.setText("GESTÃO DE MULTA DE SERVIÇOS");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOUT - VERMELHO/Logout 32x32.png"))); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lbProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTableMulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "cod", "dayStart", "dayEnd", "Valor"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMulta);
        if (jTableMulta.getColumnModel().getColumnCount() > 0)
        {
            jTableMulta.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Button-Add-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/actualizar_1_32x32.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        cmbSubFamilia.setBackground(new java.awt.Color(0, 255, 255));
        cmbSubFamilia.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cmbSubFamilia.setForeground(new java.awt.Color(0, 0, 51));
        cmbSubFamilia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSubFamilia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbSubFamiliaActionPerformed(evt);
            }
        });

        cmbProduto.setBackground(new java.awt.Color(0, 255, 255));
        cmbProduto.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cmbProduto.setForeground(new java.awt.Color(0, 0, 51));
        cmbProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProduto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbProdutoActionPerformed(evt);
            }
        });

        cmbFamilia.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cmbFamilia.setEnabled(false);
        cmbFamilia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbFamiliaActionPerformed(evt);
            }
        });

        lbCategoria.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCategoria.setText("Família:");

        lbCategoria1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbCategoria1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCategoria1.setText("Sub Família:");

        lbCategoria2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbCategoria2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCategoria2.setText("Serviço:");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSubFamilia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSubFamilia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        actualizar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        try
        {
            int ultimoDia = getUltimoDia();
            int dayStart = ultimoDia;
            int dayEnd = ultimoDia + 9;
            if ( dayEnd <= 31 )
            {
                salvarLinhaMulta( dayStart, dayEnd, BigDecimal.ZERO );

                procedimento_adcionar_dados_tabela();
            }
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private void cmbSubFamiliaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbSubFamiliaActionPerformed
    {//GEN-HEADEREND:event_cmbSubFamiliaActionPerformed

        //        cmbProduto.setModel( new DefaultComboBoxModel( ( produtosController.getVectorByIdTipoProduto( getIdTipoProduto() ) ) ) );
    }//GEN-LAST:event_cmbSubFamiliaActionPerformed

    private void cmbProdutoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbProdutoActionPerformed
    {//GEN-HEADEREND:event_cmbProdutoActionPerformed
        // TODO add your handling code here:
        procedimento_adcionar_dados_tabela();

    }//GEN-LAST:event_cmbProdutoActionPerformed

    private void cmbFamiliaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbFamiliaActionPerformed
    {//GEN-HEADEREND:event_cmbFamiliaActionPerformed

        cmbSubFamilia.setModel( new DefaultComboBoxModel( tipoProdutosController.getVectorByIdFamilia( getIdFamilia() ) ) );
        cmbProduto.setModel( new DefaultComboBoxModel( ( produtosController.getVectorByIdTipoProduto( getIdTipoProduto() ) ) ) );
    }//GEN-LAST:event_cmbFamiliaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        // TODO add your handling code here:
        procedimento_eliminar();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( ConfiguracaoMultasVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//            java.util.logging.Logger.getLogger( AssociacaoServicoVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( ConfiguracaoMultasVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( ConfiguracaoMultasVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( ConfiguracaoMultasVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            @Override
            public void run()
            {
                new ConfiguracaoMultasVisao( 15, 1, 1, BDConexao.getInstancia() ).setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cmbFamilia;
    public static javax.swing.JComboBox cmbProduto;
    public static javax.swing.JComboBox cmbSubFamilia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTableMulta;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCategoria1;
    private javax.swing.JLabel lbCategoria2;
    private static javax.swing.JLabel lbProduto;
    // End of variables declaration//GEN-END:variables

    private void procedimento_adcionar_dados_tabela()
    {
        try
        {
            if ( multaServicoController.existMulta() )
            {
                System.out.println( "Multa adicionada. ID " + getIdProduto() );
                adicionar_dados_tabela( multaServicoController.buscaTodos( getIdProduto() ) );
            }
            else
            {
                MetodosUtil.esvaziar_tabela( jTableMulta );
            }
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }

    }

    public void adicionar_dados_tabela( List<MultaServico> vector )
    {

        DefaultTableModel modelo = ( DefaultTableModel ) jTableMulta.getModel();

        this.size_old = vector.size();
        modelo.setRowCount( 0 );

        for ( int i = 0; i < vector.size(); i++ )
        {
            MultaServico multaLocal = vector.get( i );
            modelo.addRow( new Object[]
            {
                multaLocal.getId(),
                multaLocal.getDayStart(),
                multaLocal.getDayEnd(),
                multaLocal.getValor(),
            } );
        }

    }

    private void carregarProdutos()
    {
        try
        {
            List<TbProduto> listaProdutos = produtosController.listarTodos(); // pega todos os produtos
            produtosMap.clear(); // limpa antes de carregar
            for ( TbProduto p : listaProdutos )
            {
                produtosMap.put( p.getCodigo(), p.getDesignacao() );
            }
        }
        catch ( Exception e )
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog( this, "Erro ao carregar produtos", "Erro", JOptionPane.ERROR_MESSAGE );
        }
    }

    public static void adicionar_dados( int codigo )
    {

        TbProduto produto_local = ( TbProduto ) produtosController.findById( codigo );

        if ( !Objects.isNull( produto_local ) )
        {
            lbProduto.setText( produto_local.getDesignacao() );
        }
        else
        {
            JOptionPane.showMessageDialog( null, "O Produto não existe. ", DVML.DVML_COMERCIAL, JOptionPane.INFORMATION_MESSAGE );

        }

    }

    private void procedimento_eliminar()
    {

        int linhaSeleccionada = jTableMulta.getSelectedRow();

        long idReferencia = Long.parseLong( jTableMulta.getModel().getValueAt( linhaSeleccionada, 0 ).toString() );

        int opcao = JOptionPane.showConfirmDialog( null, "Tens a plena certeza que pretendes eliminar essa referencia?" );

        if ( opcao == JOptionPane.YES_OPTION )
        {

            try
            {
                multaServicoController.delete( ( int ) idReferencia );
                procedimento_adcionar_dados_tabela();
                JOptionPane.showMessageDialog( null, "Referencia eliminada com sucesso!...", DVML.DVML_COMERCIAL, JOptionPane.INFORMATION_MESSAGE );

            }
            catch ( Exception e )
            {

                e.printStackTrace();
                JOptionPane.showMessageDialog( null, "Erro ao eliminar essa referencia.\nPossivelmente já esta realcionada", DVML.DVML_COMERCIAL, JOptionPane.ERROR_MESSAGE );
            }

        }
        else
        {
            JOptionPane.showMessageDialog( null, "Referencia não eliminada", DVML.DVML_COMERCIAL, JOptionPane.INFORMATION_MESSAGE );
        }

    }

    private int getIdFamilia()
    {
        try
        {
            return familiasController.getFamiliaByDesignacao( String.valueOf( cmbFamilia.getSelectedItem() ) ).getPkFamilia();
        }
        catch ( Exception e )
        {
            return 0;
        }
    }

    private int getIdTipoProduto()
    {
        try
        {
            return tipoProdutosController.getTipoFamiliaByDesignacao( String.valueOf( cmbSubFamilia.getSelectedItem() ) ).getCodigo();
        }
        catch ( Exception e )
        {
            return 0;
        }

    }

    private TbUsuario getUsuarioById( int idUser ) throws SQLException
    {
        // Supondo que você tenha um controller para usuários
        return usuarioController.getUsuarioByCodigo( idUser ); // ou o método equivalente no seu projeto
    }

    private void salvarLinhaMulta( int dayStart, int dayEnd, BigDecimal valor )
    {
        try
        {
            MultaServico multa = new MultaServico();
            multa.setDayStart( dayStart );
            multa.setDayEnd( dayEnd );
            multa.setValor( valor );
            multa.setDataRegistro( new Date() );
            multa.setUsuarioId( this.idUser ); // 🔹 Aqui o usuário não será null
            multa.setProdutoId( getIdProduto() );
            multaServicoController.create( multa );
        }
        catch ( Exception e )
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog( this, "Erro ao salvar multa: " + e.getMessage() );
        }
    }

    private int getUltimoDia()
    {
        int numeroLinhas = jTableMulta.getRowCount();

        int ultimoDia = 0;

        try
        {
            String valor = jTableMulta.getModel().getValueAt( numeroLinhas - 1, 2 ).toString();
            ultimoDia = Integer.parseInt( valor ) + 1;
        }
        catch ( Exception e )
        {
            ultimoDia = 1;
        }

        return ultimoDia;
    }

    public void actualizar()
    {
        DefaultTableModel modelo = ( DefaultTableModel ) jTableMulta.getModel();

        try
        {
            for ( int i = 0; i < modelo.getRowCount(); i++ )
            {
                int idMulta = Integer.parseInt( modelo.getValueAt( i, 0 ).toString() );

                MultaServico multaServico = multaServicoController.findMulta( idMulta );

                if ( multaServico != null )
                {
                    multaServico.setDayStart(
                            Integer.parseInt( modelo.getValueAt( i, 1 ).toString() ) );

                    multaServico.setDayEnd(
                            Integer.parseInt( modelo.getValueAt( i, 2 ).toString() ) );

                    multaServico.setValor(
                            new BigDecimal( modelo.getValueAt( i, 3 ).toString().replace( ",", "." ) ) );

                    multaServicoController.alterar( multaServico );

                }
            }

            procedimento_adcionar_dados_tabela();

            JOptionPane.showMessageDialog(
                    null,
                    "Multa actualizada com sucesso!",
                    DVML.DVML_COMERCIAL_LDA,
                    JOptionPane.INFORMATION_MESSAGE
            );

        }
        catch ( Exception e )
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    null,
                    "Erro ao actualizar a multa",
                    DVML.DVML_COMERCIAL_LDA,
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private int getIdProduto()
    {
        String desigancao = cmbProduto.getSelectedItem().toString();
        return produtosController.findByDesignacao( desigancao ).getCodigo();
    }

}
