/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visao;

import comercial.controller.ItemPedidosController;
import comercial.controller.PedidosController;
import comercial.controller.ProdutosController;
import entity.TbItemPedidos;
import entity.TbPedido;
import entity.TbProduto;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import util.BDConexao;
import util.MetodosUtil;
import static visao.FormVendaResponsivaVisaoTop.table;

/**
 *
 * @author hp
 */
public class FacturasPendentesVisao extends javax.swing.JDialog
{

    private static PedidosController pedidosController;
    private static ItemPedidosController itemPedidosController;
    private static ProdutosController produtosController;
    private BDConexao conexao;
    private int idPedido;

    public FacturasPendentesVisao( java.awt.Frame parent, boolean modal, BDConexao conexao )
    {
        super( parent, modal );
        initComponents();
        setLocationRelativeTo( null );
        this.conexao = conexao;
        pedidosController = new PedidosController( conexao.getConnectionAtiva() );
        itemPedidosController = new ItemPedidosController( conexao.getConnectionAtiva() );
        produtosController = new ProdutosController( conexao );

        adicionarPedidos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaItemPedidos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("FACTURAS PENDENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "ID", "Data"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabelaPedidos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tabelaPedidosMouseClicked(evt);
            }
        });
        tabelaPedidos.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                tabelaPedidosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPedidos);

        tabelaItemPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String []
            {
                "Id", "Item", "Qtd", "Preço", "Total"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaItemPedidos);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/actualizar_1_32x32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logout 32x32.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelaPedidosMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tabelaPedidosMouseClicked
    {//GEN-HEADEREND:event_tabelaPedidosMouseClicked
        // TODO add your handling code here:
        visualizarItensPedidos();
    }//GEN-LAST:event_tabelaPedidosMouseClicked

    private void tabelaPedidosKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tabelaPedidosKeyReleased
    {//GEN-HEADEREND:event_tabelaPedidosKeyReleased
        // TODO add your handling code here:
        visualizarItensPedidos();
    }//GEN-LAST:event_tabelaPedidosKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        exportarItens();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( FacturasPendentesVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( FacturasPendentesVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( FacturasPendentesVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( FacturasPendentesVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                FacturasPendentesVisao dialog = new FacturasPendentesVisao(
                        new javax.swing.JFrame(),
                        true,
                        new BDConexao()
                );
                dialog.addWindowListener( new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing( java.awt.event.WindowEvent e )
                    {
                        System.exit( 0 );
                    }
                } );
                dialog.setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaItemPedidos;
    private javax.swing.JTable tabelaPedidos;
    // End of variables declaration//GEN-END:variables

    private void adicionarPedidos()
    {
        try
        {
            List<TbPedido> lista = pedidosController.findAll();

            DefaultTableModel model = ( DefaultTableModel ) tabelaPedidos.getModel();
            model.setRowCount( 0 ); // limpa a tabela antes de preencher

            for ( TbPedido p : lista )
            {
                model.addRow( new Object[]
                {
                    p.getPkPedido(),
                    p.getDataPedido() + " " + p.getHoraPedido(),

                } );
            }
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }
    }

    private void visualizarItensPedidos()
    {

        DefaultTableModel modeloPedidos = ( DefaultTableModel ) tabelaPedidos.getModel();
        idPedido = Integer.parseInt( modeloPedidos.getValueAt( tabelaPedidos.getSelectedRow(), 0 ).toString() );
        System.out.println( "ID PEDIDO: " + idPedido );
        try
        {
            List<TbItemPedidos> findByPedido = itemPedidosController.findByPedido( idPedido );
            DefaultTableModel modelo = ( DefaultTableModel ) tabelaItemPedidos.getModel();
            modelo.setRowCount( 0 );
            for ( TbItemPedidos item : findByPedido )
            {
                TbProduto produto = produtosController.findByCod( item.getFkProdutos().getCodigo() );
                modelo.addRow( new Object[]
                {
                    item.getFkProdutos().getCodigo(),
                    produto.getDesignacao(),
                    item.getQtd(),
                    item.getPreco(),
                    item.getTotalItem()
                } );

            }

        }
        catch ( SQLException e )
        {
            e.printStackTrace();
        }

    }

    private void exportarItens()
    {

        DefaultTableModel modelo = ( DefaultTableModel ) tabelaItemPedidos.getModel();
        for ( int i = 0; i < modelo.getRowCount(); i++ )
        {
            int idItem = Integer.parseInt( modelo.getValueAt( i, 0 ).toString() );
            try
            {
                FormVendaResponsivaVisaoTop.accao_codigo_interno_enter_busca_exterior( idItem );
            }
            catch ( Exception e )
            {
                e.printStackTrace();
            }

        }

        try
        {
            itemPedidosController.deleteByIdPedido( idPedido );
            pedidosController.delete( idPedido );
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }

        dispose();

    }

}
