/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import java.sql.Connection;
import controller.FornecedorController;
import controller.UsuarioController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelo.FornecedorModelo;
import modelo.UsuarioModelo;
import util.BDConexao;




/**
 *
 * @author Domingos Dala Vunge
 */
public class FornecedorVisao extends javax.swing.JDialog {

    /**
     * Creates new form UsuarioVisao
     */
    
    
   
    private BDConexao conexao;
    private FornecedorModelo fornecedorModelo;
    private FornecedorController fornecedorController;
    private Frame parent;
    private int codigo = 0;
    
    public FornecedorVisao(java.awt.Frame parent, boolean modal) {
        //this.parent =  parent1;
        
        super(parent, modal);
        
        this.parent = parent;
        
        
        initComponents();
       // confLabel();
        setLocationRelativeTo(null);
        
        fornecedorModelo = new FornecedorModelo();
        conexao = BDConexao.getInstancia();
        fornecedorController = new FornecedorController(conexao);
        cmbFornecedores.setModel( new DefaultComboBoxModel( conexao.getElementos("tb_fornecedor", "nome", false)   ) );
        txtInicias.addKeyListener( new TratarEventoTeclado() );
        
        
        
    }

    
    
    public void confLabel()
    {
                
        lbNome.setHorizontalAlignment(JLabel.RIGHT);
       
      
        lbTelefone.setHorizontalAlignment(JLabel.RIGHT);
        lbEmail.setHorizontalAlignment(JLabel.RIGHT);
        lbSite.setHorizontalAlignment(JLabel.RIGHT);
        lbEndereco.setHorizontalAlignment(JLabel.RIGHT);
       
        //lbNomes.setHorizontalAlignment(JLabel.RIGHT);
        lbInicaisNome1.setHorizontalAlignment(JLabel.RIGHT);
    
    
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbSite = new javax.swing.JLabel();
        txtSite = new javax.swing.JTextField();
        lbEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lbInicaisNome1 = new javax.swing.JLabel();
        txtInicias = new javax.swing.JTextField();
        cmbFornecedores = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("...:::::  KITANDA - CADASTRO DE FORNECEDOR ::::...");
        setIconImage(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar_16x16.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setAlignmentX(0.5F);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_16x16.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setAlignmentX(0.5F);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eliminar_16x16.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setAlignmentX(0.5F);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Sair");
        btnCancelar.setAlignmentX(0.5F);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbNome.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbNome.setText("Nome:");

        txtNome.setBackground(new java.awt.Color(51, 153, 0));
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setCaretColor(new java.awt.Color(255, 255, 255));

        lbTelefone.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbTelefone.setText("Telefone:");

        txtTelefone.setBackground(new java.awt.Color(51, 153, 0));
        txtTelefone.setForeground(new java.awt.Color(255, 255, 255));

        lbEmail.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbEmail.setText("Email:");

        txtEmail.setBackground(new java.awt.Color(51, 153, 0));
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));

        lbSite.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbSite.setText("Site:");

        txtSite.setBackground(new java.awt.Color(51, 153, 0));
        txtSite.setForeground(new java.awt.Color(255, 255, 255));

        lbEndereco.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbEndereco.setText("Endereco:");

        txtEndereco.setBackground(new java.awt.Color(51, 153, 0));
        txtEndereco.setForeground(new java.awt.Color(255, 255, 255));

        lbInicaisNome1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbInicaisNome1.setText("Inicias Fornecedor:");

        txtInicias.setBackground(new java.awt.Color(51, 153, 0));
        txtInicias.setForeground(new java.awt.Color(255, 255, 255));
        txtInicias.setCaretColor(new java.awt.Color(255, 255, 255));

        cmbFornecedores.setBackground(new java.awt.Color(51, 153, 0));
        cmbFornecedores.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cmbFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFornecedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(txtTelefone)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEmail)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSite)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbSite, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEndereco)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 271, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbInicaisNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFornecedores, 0, 189, Short.MAX_VALUE)
                            .addComponent(txtInicias))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbInicaisNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInicias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lbNome)
                .addGap(3, 3, 3)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lbTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSite, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            // TODO add your handling code here:

            operacao(1,"SALVOS", "SALVAR");
            
        } catch (SQLException ex) {
            Logger.getLogger(FornecedorVisao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            // TODO add your handling code here:

            operacao(2,"ALTERADO", "ALTERAR");
        } catch (SQLException ex) {
            Logger.getLogger(FornecedorVisao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
         try {
            
                int resposta = JOptionPane.showConfirmDialog(null, "TENS A CERTEZA QUE PRETENDES ELIMINAR ESTE O USUARIO: " +getNome());

                if (resposta == JOptionPane.YES_OPTION)
                          operacao(3,"ELIMNADO", "ELIMINAR");
             
        } catch (SQLException ex) {
            Logger.getLogger(FornecedorVisao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFornecedoresActionPerformed
        // TODO add your handling code here:
        setDadosFornecedores();
    }//GEN-LAST:event_cmbFornecedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornecedorVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornecedorVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornecedorVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedorVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FornecedorVisao dialog = new FornecedorVisao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    
    /* CRIACAO DO GETS  */
    public String getNome()
    {
        return txtNome.getText();
    }
    
    
     public String getEndereco()
    {
        return txtEndereco.getText();
    }
    
  
    /*
     *   lbNome.setHorizontalAlignment(JLabel.RIGHT);
        lbSobreNome.setHorizontalAlignment(JLabel.RIGHT);
        lbUserName.setHorizontalAlignment(JLabel.RIGHT);
        lbSenha.setHorizontalAlignment(JLabel.RIGHT);
        lbConfirSenha.setHorizontalAlignment(JLabel.RIGHT);
        lbDataNascimento.setHorizontalAlignment(JLabel.RIGHT);
        lbTelefone.setHorizontalAlignment(JLabel.RIGHT);
        lbEmail.setHorizontalAlignment(JLabel.RIGHT);
        lbEndereco.setHorizontalAlignment(JLabel.RIGHT);
     
     
     */
    
   
    
    
  
    
    
   
     public String getTelefone()
     {
         return txtTelefone.getText();
     }
     
     public String getEmail()
     {
         return txtEmail.getText();
     }
          
     
     
     public String getSite()
     {
         return txtSite.getText();
     }
     
    
     /*VALIDACOES */  
     
   
    
     
     public void limpar()
     {
         
             
          txtNome.setText("");
          txtInicias.setText("");
        
          txtEmail.setText("");
          txtTelefone.setText("");
          txtSite.setText("");
         
          cmbFornecedores.setSelectedIndex(-1);
     
     }
     
     
    public boolean campos_invalidos()
    {     
        Color backGround = Color.WHITE;
        Color foreGround = Color.BLACK;
        Color caretColor = Color.BLACK;
            
        if (getNome().equals(""))
        {
            txtNome.setBackground(backGround);
            txtNome.setForeground(foreGround);
            txtNome.setCaretColor(caretColor);
            JOptionPane.showMessageDialog(null, "Pf. Preêncha o campo Nome: ");
            return true;
        }
        else if (getTelefone().equals("")){
            
            txtTelefone.setBackground(backGround);
            txtTelefone.setForeground(foreGround);
            txtTelefone.setCaretColor(caretColor);
            JOptionPane.showMessageDialog(null, "Pf. Preêncha o Campo Sobre Telefone: "); 
            return true;    
        }   
        else if (getEmail().equals("")){
            
            txtEmail.setBackground(backGround);
            txtEmail.setForeground(foreGround);
            txtEmail.setCaretColor(caretColor);
            JOptionPane.showMessageDialog(null, "Pf. Preêncha o Campo Sobre Email: "); 
            return true;
            
        }
      
       
        
        return false;
    }
            
    
    public void operacao(int operacao , String descricaoCerto, String descricaoErro) throws SQLException
    {
        //(int codigo, String nome, String telefone, String email, String site, String enderreco)
           fornecedorModelo = new FornecedorModelo(codigo,getNome(), 
                                              getTelefone(), getEmail(), getSite(), 
                                             getEndereco());  
           if(operacao!=3)
           {
                 if(!campos_invalidos())  
                 {
                     
                           if(fornecedorController.operacao(operacao, fornecedorModelo))
                           {
                                JOptionPane.showMessageDialog(null, "DADOS   " + descricaoCerto + " COM SUCESSO NA BD!...");
                                limpar();
                           }
                           else JOptionPane.showMessageDialog(null, "ERRO AO " + descricaoErro + "NA BD!...", "ERRO", JOptionPane.ERROR_MESSAGE);
                     
                 }
           }else{
                 if(fornecedorController.operacao(operacao, fornecedorModelo))
                           {
                                JOptionPane.showMessageDialog(null, "DADOS   " + descricaoCerto + " COM SUCESSO NA BD!...");
                                limpar();
                           }
                           else JOptionPane.showMessageDialog(null, "ERRO AO " + descricaoErro + "NA BD!...", "ERRO", JOptionPane.ERROR_MESSAGE);
           }

    }
    
    
    
    //CLASSE EVENTO TECLADO 
    
     //----------- evento do teclado ---------------------------------------
    class TratarEventoTeclado implements KeyListener
    {
        String prefixo = "";

        public void keyPressed(KeyEvent evt)
        {
            
            FornecedorModelo fornecedorModelo = new FornecedorModelo();

            if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_ENTER)
            {
                char key = evt.getKeyChar();
                prefixo = txtInicias.getText().trim() + key;
                
                cmbFornecedores.setModel(new DefaultComboBoxModel(conexao.getElementosLike("tb_fornecedor", "nome", prefixo) ) );
                
               
                try {
                    codigo = fornecedorController.getCodigo( String.valueOf(cmbFornecedores.getSelectedItem()));
                    fornecedorModelo = fornecedorController.getFornecedor(codigo);
                } catch (SQLException ex) {
                    Logger.getLogger(FornecedorVisao.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                txtNome.setText(fornecedorModelo.getNome());
               
                txtTelefone.setText( fornecedorModelo.getTelefone()     );
                txtEmail.setText( fornecedorModelo.getEmail()     );
                txtSite.setText( fornecedorModelo.getSite()    );
                txtEndereco.setText( fornecedorModelo.getEndereco()    );
               
                
                
                

            }
        }

        public void keyReleased(KeyEvent evt)
        {}
        public void keyTyped(KeyEvent evt)
        {}
    }

  
    
    public void setDadosFornecedores(){
    
          
                try {
                    codigo = fornecedorController.getCodigo( String.valueOf(cmbFornecedores.getSelectedItem()));
                    fornecedorModelo = fornecedorController.getFornecedor(codigo);
                } catch (SQLException ex) {
                    Logger.getLogger(FornecedorVisao.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                txtNome.setText(fornecedorModelo.getNome());
               
                txtTelefone.setText( fornecedorModelo.getTelefone()     );
                txtEmail.setText( fornecedorModelo.getEmail()     );
                txtSite.setText( fornecedorModelo.getSite()    );
                txtEndereco.setText( fornecedorModelo.getEndereco()    );
    
    
    }
    
    
    

    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbFornecedores;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbInicaisNome1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSite;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtInicias;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}

