/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import java.sql.Connection;
import dao.AccessoArmazemDao;
import dao.ArmazemDao;
import dao.ItemPedidosDao;
import dao.PedidoDao;
import dao.TurnoDao;
import dao.UsuarioDao;
import entity.TbPedido;
import dao.CaixaDao;
import dao.DadosInstituicaoDao;
import dao.MesasDao;
import entity.TbItemPedidos;
import entity.Turno;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import util.BDConexao;
import util.DVML;
import util.JPAEntityMannagerFactoryUtil;

/**
 *
 * @author MartinhoLuis e Domingos Dala Vunge
 */
public class MesasTranferenciasVisao extends javax.swing.JFrame {

    private TbPedido pedidos = new TbPedido();
    private static EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;
    private static AccessoArmazemDao accessoArmazemDao;
    private static ArmazemDao armazemDao;
    private static PedidoDao pedidoDao = new PedidoDao(emf);
    private static MesasDao mesasDao = new MesasDao(emf);
    private static ItemPedidosDao itemPedidosDao = new ItemPedidosDao(emf);
    private UsuarioDao usuarioDao = new UsuarioDao(emf);
    private DadosInstituicaoDao dadosInstituicaoDao = new DadosInstituicaoDao(emf);
    private TurnoDao turnoDao = new TurnoDao(emf);
    private Turno turno;
    private static CaixaDao caixaDao;
    private int id_turno = 0;
    private BDConexao conexao;
    private Thread t;
    private int idUser = 0;
    private int id_armazem;
    private String lugar = "";
    private List<TbItemPedidos> itemPedidosClasseLocal;
    private String mesaSelecionada;

    public MesasTranferenciasVisao(int idUser, String lugar, int id_armazem, BDConexao conexao, List<TbItemPedidos> listaPedidos) {
        initComponents();
        //this.setExtendedState(   this.getExtendedState()|PrincipalPedidosVisao.MAXIMIZED_BOTH  );
        setLocationRelativeTo(null);
//        t = new Thread(this);
//        t.start();

        this.id_armazem = id_armazem;
        this.lugar = lugar;

        this.conexao = conexao;
        this.itemPedidosClasseLocal = listaPedidos;
        this.idUser = idUser;
        armazemDao = new ArmazemDao(emf);
        accessoArmazemDao = new AccessoArmazemDao(emf);
        mostrarListaPedidos();
//        cmbArmazem.setModel(new DefaultComboBoxModel(accessoArmazemDao.getAllArmazemByIdUSuario(idUser)));
        procedimento_mesas_livre();
//        controlo_turno();
//        procedimento_abrir_mesas();
        caixaDao = new CaixaDao(emf);
//        verificarCaixa();
//        mostrar_armazem();
        try {
//            configurar_armazens();
        } catch (Exception e) {
            e.printStackTrace();
        }
//        setArmazem( dadosInstituicaoDao.findTbDadosInstituicao( 1 ).getConfigArmazens() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        btn_mesa_1 = new javax.swing.JButton();
        btn_mesa_2 = new javax.swing.JButton();
        btn_mesa_3 = new javax.swing.JButton();
        btn_mesa_4 = new javax.swing.JButton();
        btn_mesa_5 = new javax.swing.JButton();
        btn_mesa_6 = new javax.swing.JButton();
        btn_mesa_7 = new javax.swing.JButton();
        btn_mesa_9 = new javax.swing.JButton();
        btn_mesa_8 = new javax.swing.JButton();
        btn_mesa_10 = new javax.swing.JButton();
        btn_mesa_11 = new javax.swing.JButton();
        btn_mesa_12 = new javax.swing.JButton();
        btn_mesa_13 = new javax.swing.JButton();
        btn_mesa_14 = new javax.swing.JButton();
        btn_mesa_16 = new javax.swing.JButton();
        lb_mesa_05 = new javax.swing.JLabel();
        lb_mesa_02 = new javax.swing.JLabel();
        lb_mesa_04 = new javax.swing.JLabel();
        lb_mesa_03 = new javax.swing.JLabel();
        lb_mesa_01 = new javax.swing.JLabel();
        lb_mesa_06 = new javax.swing.JLabel();
        lb_mesa_07 = new javax.swing.JLabel();
        lb_mesa_08 = new javax.swing.JLabel();
        lb_mesa_09 = new javax.swing.JLabel();
        lb_mesa_10 = new javax.swing.JLabel();
        lb_mesa_11 = new javax.swing.JLabel();
        lb_mesa_12 = new javax.swing.JLabel();
        lb_mesa_13 = new javax.swing.JLabel();
        lb_mesa_14 = new javax.swing.JLabel();
        lb_mesa_15 = new javax.swing.JLabel();
        lb_mesa_16 = new javax.swing.JLabel();
        btn_mesa_15 = new javax.swing.JButton();
        btn_mesa_32 = new javax.swing.JButton();
        lb_mesa_32 = new javax.swing.JLabel();
        btn_mesa_24 = new javax.swing.JButton();
        lb_mesa_24 = new javax.swing.JLabel();
        lb_mesa_23 = new javax.swing.JLabel();
        btn_mesa_23 = new javax.swing.JButton();
        btn_mesa_31 = new javax.swing.JButton();
        lb_mesa_31 = new javax.swing.JLabel();
        lb_mesa_30 = new javax.swing.JLabel();
        btn_mesa_30 = new javax.swing.JButton();
        btn_mesa_22 = new javax.swing.JButton();
        lb_mesa_22 = new javax.swing.JLabel();
        lb_mesa_21 = new javax.swing.JLabel();
        btn_mesa_21 = new javax.swing.JButton();
        btn_mesa_29 = new javax.swing.JButton();
        lb_mesa_29 = new javax.swing.JLabel();
        lb_mesa_28 = new javax.swing.JLabel();
        btn_mesa_28 = new javax.swing.JButton();
        btn_mesa_20 = new javax.swing.JButton();
        lb_mesa_20 = new javax.swing.JLabel();
        btn_mesa_19 = new javax.swing.JButton();
        lb_mesa_19 = new javax.swing.JLabel();
        btn_mesa_27 = new javax.swing.JButton();
        lb_mesa_27 = new javax.swing.JLabel();
        lb_mesa_26 = new javax.swing.JLabel();
        btn_mesa_26 = new javax.swing.JButton();
        btn_mesa_18 = new javax.swing.JButton();
        lb_mesa_18 = new javax.swing.JLabel();
        btn_mesa_17 = new javax.swing.JButton();
        btn_mesa_25 = new javax.swing.JButton();
        lb_mesa_17 = new javax.swing.JLabel();
        lb_mesa_25 = new javax.swing.JLabel();
        btn_mesa_33 = new javax.swing.JButton();
        btn_mesa_34 = new javax.swing.JButton();
        lb_mesa_33 = new javax.swing.JLabel();
        lb_mesa_34 = new javax.swing.JLabel();
        btn_mesa_35 = new javax.swing.JButton();
        lb_mesa_35 = new javax.swing.JLabel();
        btn_mesa_36 = new javax.swing.JButton();
        lb_mesa_36 = new javax.swing.JLabel();
        btn_mesa_37 = new javax.swing.JButton();
        lb_mesa_37 = new javax.swing.JLabel();
        btn_mesa_38 = new javax.swing.JButton();
        lb_mesa_38 = new javax.swing.JLabel();
        btn_mesa_39 = new javax.swing.JButton();
        lb_mesa_39 = new javax.swing.JLabel();
        btn_mesa_40 = new javax.swing.JButton();
        lb_mesa_40 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_mesa_1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/mesa_teste.jpg"))); // NOI18N
        btn_mesa_1.setText("1");
        btn_mesa_1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 80));

        btn_mesa_2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_2.setText("2");
        btn_mesa_2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 60, 80));

        btn_mesa_3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_3.setText("3");
        btn_mesa_3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 60, 80));

        btn_mesa_4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_4.setText("4");
        btn_mesa_4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 70, 80));

        btn_mesa_5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_5.setText("5");
        btn_mesa_5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 70, 80));

        btn_mesa_6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_6.setText("6");
        btn_mesa_6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 70, 80));

        btn_mesa_7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_7.setText("7");
        btn_mesa_7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 70, 80));

        btn_mesa_9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_9.setText("9");
        btn_mesa_9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 80));

        btn_mesa_8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_8.setText("8");
        btn_mesa_8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 70, 80));

        btn_mesa_10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_10.setText("10");
        btn_mesa_10.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_10ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 60, 80));

        btn_mesa_11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_11.setText("11");
        btn_mesa_11.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_11ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 70, 80));

        btn_mesa_12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_12.setText("12");
        btn_mesa_12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_12ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 70, 80));

        btn_mesa_13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_13.setText("13");
        btn_mesa_13.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_13ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 70, 80));

        btn_mesa_14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_14.setText("14");
        btn_mesa_14.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_14ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 70, 80));

        btn_mesa_16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_16.setText("16");
        btn_mesa_16.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_16ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 70, 80));

        lb_mesa_05.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_05.setText("05");
        jPanel2.add(lb_mesa_05, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 80));

        lb_mesa_02.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_02.setText("02");
        jPanel2.add(lb_mesa_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 40, 80));

        lb_mesa_04.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_04.setText("04");
        jPanel2.add(lb_mesa_04, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 80));

        lb_mesa_03.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_03.setText("03");
        jPanel2.add(lb_mesa_03, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 80));

        lb_mesa_01.setBackground(new java.awt.Color(51, 153, 0));
        lb_mesa_01.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_01.setText("01");
        lb_mesa_01.setOpaque(true);
        jPanel2.add(lb_mesa_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 80));

        lb_mesa_06.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_06.setText("06");
        jPanel2.add(lb_mesa_06, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 40, 80));

        lb_mesa_07.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_07.setText("07");
        jPanel2.add(lb_mesa_07, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, 80));

        lb_mesa_08.setBackground(new java.awt.Color(255, 153, 51));
        lb_mesa_08.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_08.setText("08");
        jPanel2.add(lb_mesa_08, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 40, 80));

        lb_mesa_09.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_09.setText("09");
        jPanel2.add(lb_mesa_09, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 80));

        lb_mesa_10.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_10.setText("10");
        jPanel2.add(lb_mesa_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 40, 80));

        lb_mesa_11.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_11.setText("11");
        jPanel2.add(lb_mesa_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 80));

        lb_mesa_12.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_12.setText("12");
        jPanel2.add(lb_mesa_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 80));

        lb_mesa_13.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_13.setText("13");
        jPanel2.add(lb_mesa_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, 80));

        lb_mesa_14.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_14.setText("14");
        jPanel2.add(lb_mesa_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 40, 80));

        lb_mesa_15.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_15.setText("15");
        jPanel2.add(lb_mesa_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, -1, 80));

        lb_mesa_16.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_16.setText("16");
        jPanel2.add(lb_mesa_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, -1, 80));

        btn_mesa_15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_15.setText("15");
        btn_mesa_15.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_15ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 70, 80));

        btn_mesa_32.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_32.setText("32");
        btn_mesa_32.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_32ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 70, 80));

        lb_mesa_32.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_32.setText("32");
        jPanel2.add(lb_mesa_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, -1, 80));

        btn_mesa_24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_24.setText("24");
        btn_mesa_24.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_24ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 70, 80));

        lb_mesa_24.setBackground(new java.awt.Color(255, 153, 51));
        lb_mesa_24.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_24.setText("24");
        jPanel2.add(lb_mesa_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 40, 80));

        lb_mesa_23.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_23.setText("23");
        jPanel2.add(lb_mesa_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, -1, 80));

        btn_mesa_23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_23.setText("23");
        btn_mesa_23.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_23ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 70, 80));

        btn_mesa_31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_31.setText("31");
        btn_mesa_31.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_31ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 70, 80));

        lb_mesa_31.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_31.setText("31");
        jPanel2.add(lb_mesa_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, -1, 80));

        lb_mesa_30.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_30.setText("30");
        jPanel2.add(lb_mesa_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 40, 80));

        btn_mesa_30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_30.setText("30");
        btn_mesa_30.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_30ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 70, 80));

        btn_mesa_22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_22.setText("22");
        btn_mesa_22.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_22ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 70, 80));

        lb_mesa_22.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_22.setText("22");
        jPanel2.add(lb_mesa_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 40, 80));

        lb_mesa_21.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_21.setText("21");
        jPanel2.add(lb_mesa_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, 80));

        btn_mesa_21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_21.setText("21");
        btn_mesa_21.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_21ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 70, 80));

        btn_mesa_29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_29.setText("29");
        btn_mesa_29.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_29ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 70, 80));

        lb_mesa_29.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_29.setText("29");
        jPanel2.add(lb_mesa_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, 80));

        lb_mesa_28.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_28.setText("28");
        jPanel2.add(lb_mesa_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 80));

        btn_mesa_28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_28.setText("28");
        btn_mesa_28.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_28ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 70, 80));

        btn_mesa_20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_20.setText("20");
        btn_mesa_20.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_20ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 70, 80));

        lb_mesa_20.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_20.setText("20");
        jPanel2.add(lb_mesa_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, 80));

        btn_mesa_19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_19.setText("19");
        btn_mesa_19.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_19ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 70, 80));

        lb_mesa_19.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_19.setText("19");
        jPanel2.add(lb_mesa_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, 80));

        btn_mesa_27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_27.setText("27");
        btn_mesa_27.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_27ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 70, 80));

        lb_mesa_27.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_27.setText("27");
        jPanel2.add(lb_mesa_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, 80));

        lb_mesa_26.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_26.setText("26");
        jPanel2.add(lb_mesa_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 40, 80));

        btn_mesa_26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_26.setText("26");
        btn_mesa_26.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_26ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 70, 80));

        btn_mesa_18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_18.setText("18");
        btn_mesa_18.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_18ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, 80));

        lb_mesa_18.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_18.setText("18");
        jPanel2.add(lb_mesa_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 40, 80));

        btn_mesa_17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/mesa_teste.jpg"))); // NOI18N
        btn_mesa_17.setText("17");
        btn_mesa_17.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_17ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 80));

        btn_mesa_25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_25.setText("25");
        btn_mesa_25.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_25ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 80));

        lb_mesa_17.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_17.setText("17");
        jPanel2.add(lb_mesa_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 80));

        lb_mesa_25.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_25.setText("25");
        jPanel2.add(lb_mesa_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, 80));

        btn_mesa_33.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_33.setText("33");
        btn_mesa_33.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_33ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 70, 80));

        btn_mesa_34.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_34.setText("34");
        btn_mesa_34.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_34ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 70, 80));

        lb_mesa_33.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_33.setText("33");
        jPanel2.add(lb_mesa_33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 80));

        lb_mesa_34.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_34.setText("34");
        jPanel2.add(lb_mesa_34, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 40, 80));

        btn_mesa_35.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_35.setText("35");
        btn_mesa_35.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_35ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_35, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 70, 80));

        lb_mesa_35.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_35.setText("35");
        jPanel2.add(lb_mesa_35, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, 80));

        btn_mesa_36.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_36.setText("36");
        btn_mesa_36.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_36ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_36, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 70, 80));

        lb_mesa_36.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_36.setText("36");
        jPanel2.add(lb_mesa_36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, 80));

        btn_mesa_37.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_37.setText("37");
        btn_mesa_37.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_37ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_37, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 70, 80));

        lb_mesa_37.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_37.setText("37");
        jPanel2.add(lb_mesa_37, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, 80));

        btn_mesa_38.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_38.setText("38");
        btn_mesa_38.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_38ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_38, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 70, 80));

        lb_mesa_38.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_38.setText("38");
        jPanel2.add(lb_mesa_38, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 40, 80));

        btn_mesa_39.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_39.setText("39");
        btn_mesa_39.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_39ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_39, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 70, 80));

        lb_mesa_39.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_39.setText("39");
        jPanel2.add(lb_mesa_39, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, -1, 80));

        btn_mesa_40.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_40.setText("40");
        btn_mesa_40.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_40ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_40, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, 70, 80));

        lb_mesa_40.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_40.setText("40");
        jPanel2.add(lb_mesa_40, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, -1, 80));

        jScrollPane1.setViewportView(jPanel2);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOUT - VERMELHO/Logout 32x32.png"))); // NOI18N
        jButton17.setText("SAIR");
        jButton17.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton17ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens32x32/actualizar_32x32.png"))); // NOI18N
        jButton2.setText("TRANSFERÊNCIA DE MESA COMPLETA");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton17, jButton2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void btn_mesa_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_1ActionPerformed
        activar_button_mesa(false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_1ActionPerformed

    private void btn_mesa_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_2ActionPerformed
        // TODO add your handling code here:
        activar_button_mesa(true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_2ActionPerformed

    private void btn_mesa_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_3ActionPerformed
        // TODO add your handling code here:
        activar_button_mesa(true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_3ActionPerformed

    private void btn_mesa_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_4ActionPerformed
        activar_button_mesa(true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_4ActionPerformed

    private void btn_mesa_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_10ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_10ActionPerformed

    private void btn_mesa_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_5ActionPerformed
        activar_button_mesa(true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_5ActionPerformed

    private void btn_mesa_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_6ActionPerformed
        activar_button_mesa(true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_6ActionPerformed

    private void btn_mesa_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_7ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_7ActionPerformed

    private void btn_mesa_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_9ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_9ActionPerformed

    private void btn_mesa_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_8ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_8ActionPerformed

    private void btn_mesa_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_11ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_11ActionPerformed

    private void btn_mesa_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_12ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_12ActionPerformed

    private void btn_mesa_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_13ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_13ActionPerformed

    private void btn_mesa_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_14ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_14ActionPerformed

    private void btn_mesa_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_16ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_16ActionPerformed

    private void btn_mesa_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_15ActionPerformed
        // TODO add your handling code here:
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_15ActionPerformed

    private void btn_mesa_32ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_32ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_32ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_32ActionPerformed

    private void btn_mesa_24ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_24ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_24ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_24ActionPerformed

    private void btn_mesa_23ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_23ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_23ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_23ActionPerformed

    private void btn_mesa_31ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_31ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_31ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_31ActionPerformed

    private void btn_mesa_30ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_30ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_30ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_30ActionPerformed

    private void btn_mesa_22ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_22ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_22ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_22ActionPerformed

    private void btn_mesa_21ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_21ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_21ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_21ActionPerformed

    private void btn_mesa_29ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_29ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_29ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_29ActionPerformed

    private void btn_mesa_28ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_28ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_28ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_28ActionPerformed

    private void btn_mesa_20ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_20ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_20ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_20ActionPerformed

    private void btn_mesa_19ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_19ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_19ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_19ActionPerformed

    private void btn_mesa_27ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_27ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_27ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_27ActionPerformed

    private void btn_mesa_26ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_26ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_26ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_26ActionPerformed

    private void btn_mesa_18ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_18ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_18ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_18ActionPerformed

    private void btn_mesa_17ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_17ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_17ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_17ActionPerformed

    private void btn_mesa_25ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_25ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_25ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_25ActionPerformed

    private void btn_mesa_33ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_33ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_33ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_33ActionPerformed

    private void btn_mesa_34ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_34ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_34ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_34ActionPerformed

    private void btn_mesa_35ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_35ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_35ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_35ActionPerformed

    private void btn_mesa_36ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_36ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_36ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_36ActionPerformed

    private void btn_mesa_37ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_37ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_37ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true
        );
    }//GEN-LAST:event_btn_mesa_37ActionPerformed

    private void btn_mesa_38ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_38ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_38ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true
        );
    }//GEN-LAST:event_btn_mesa_38ActionPerformed

    private void btn_mesa_39ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_39ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_39ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true
        );
    }//GEN-LAST:event_btn_mesa_39ActionPerformed

    private void btn_mesa_40ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_40ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_40ActionPerformed
        activar_button_mesa(true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false
        );
    }//GEN-LAST:event_btn_mesa_40ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        transferir_mesas();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesasTranferenciasVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesasTranferenciasVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesasTranferenciasVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesasTranferenciasVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MesasTranferenciasVisao(15, "", 1, BDConexao.getInstancia(), null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mesa_1;
    private javax.swing.JButton btn_mesa_10;
    private javax.swing.JButton btn_mesa_11;
    private javax.swing.JButton btn_mesa_12;
    private javax.swing.JButton btn_mesa_13;
    private javax.swing.JButton btn_mesa_14;
    private javax.swing.JButton btn_mesa_15;
    private javax.swing.JButton btn_mesa_16;
    private javax.swing.JButton btn_mesa_17;
    private javax.swing.JButton btn_mesa_18;
    private javax.swing.JButton btn_mesa_19;
    private javax.swing.JButton btn_mesa_2;
    private javax.swing.JButton btn_mesa_20;
    private javax.swing.JButton btn_mesa_21;
    private javax.swing.JButton btn_mesa_22;
    private javax.swing.JButton btn_mesa_23;
    private javax.swing.JButton btn_mesa_24;
    private javax.swing.JButton btn_mesa_25;
    private javax.swing.JButton btn_mesa_26;
    private javax.swing.JButton btn_mesa_27;
    private javax.swing.JButton btn_mesa_28;
    private javax.swing.JButton btn_mesa_29;
    private javax.swing.JButton btn_mesa_3;
    private javax.swing.JButton btn_mesa_30;
    private javax.swing.JButton btn_mesa_31;
    private javax.swing.JButton btn_mesa_32;
    private javax.swing.JButton btn_mesa_33;
    private javax.swing.JButton btn_mesa_34;
    private javax.swing.JButton btn_mesa_35;
    private javax.swing.JButton btn_mesa_36;
    private javax.swing.JButton btn_mesa_37;
    private javax.swing.JButton btn_mesa_38;
    private javax.swing.JButton btn_mesa_39;
    private javax.swing.JButton btn_mesa_4;
    private javax.swing.JButton btn_mesa_40;
    private javax.swing.JButton btn_mesa_5;
    private javax.swing.JButton btn_mesa_6;
    private javax.swing.JButton btn_mesa_7;
    private javax.swing.JButton btn_mesa_8;
    private javax.swing.JButton btn_mesa_9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lb_mesa_01;
    public static javax.swing.JLabel lb_mesa_02;
    public static javax.swing.JLabel lb_mesa_03;
    public static javax.swing.JLabel lb_mesa_04;
    public static javax.swing.JLabel lb_mesa_05;
    public static javax.swing.JLabel lb_mesa_06;
    public static javax.swing.JLabel lb_mesa_07;
    public static javax.swing.JLabel lb_mesa_08;
    public static javax.swing.JLabel lb_mesa_09;
    public static javax.swing.JLabel lb_mesa_10;
    public static javax.swing.JLabel lb_mesa_11;
    public static javax.swing.JLabel lb_mesa_12;
    public static javax.swing.JLabel lb_mesa_13;
    public static javax.swing.JLabel lb_mesa_14;
    public static javax.swing.JLabel lb_mesa_15;
    public static javax.swing.JLabel lb_mesa_16;
    public static javax.swing.JLabel lb_mesa_17;
    public static javax.swing.JLabel lb_mesa_18;
    public static javax.swing.JLabel lb_mesa_19;
    public static javax.swing.JLabel lb_mesa_20;
    public static javax.swing.JLabel lb_mesa_21;
    public static javax.swing.JLabel lb_mesa_22;
    public static javax.swing.JLabel lb_mesa_23;
    public static javax.swing.JLabel lb_mesa_24;
    public static javax.swing.JLabel lb_mesa_25;
    public static javax.swing.JLabel lb_mesa_26;
    public static javax.swing.JLabel lb_mesa_27;
    public static javax.swing.JLabel lb_mesa_28;
    public static javax.swing.JLabel lb_mesa_29;
    public static javax.swing.JLabel lb_mesa_30;
    public static javax.swing.JLabel lb_mesa_31;
    public static javax.swing.JLabel lb_mesa_32;
    public static javax.swing.JLabel lb_mesa_33;
    public static javax.swing.JLabel lb_mesa_34;
    public static javax.swing.JLabel lb_mesa_35;
    public static javax.swing.JLabel lb_mesa_36;
    public static javax.swing.JLabel lb_mesa_37;
    public static javax.swing.JLabel lb_mesa_38;
    public static javax.swing.JLabel lb_mesa_39;
    public static javax.swing.JLabel lb_mesa_40;
    // End of variables declaration//GEN-END:variables

//    public static void pintar_mesas(JLabel label_mesa, String mesa) {
//
//        //0 - oucupado - amarelo, 1 - livre - verde 
//        try {
//            System.out.println("QTD lugares oucupados: " + itemPedidosDao.getQtdItensByIdPedido(pedidoDao.getLastPedidoByMesa(mesa)));
//
//            long numero_lugares_oucupado = itemPedidosDao.getQtdItensByIdPedido(pedidoDao.getLastPedidoByMesa(mesa));
//
//            //Mesa Oucupada
//            if (numero_lugares_oucupado > 0) {
//                label_mesa.setBackground(new Color(255, 153, 51));
//                label_mesa.setOpaque(true);
//            }
//        } catch (Exception e) {
//        }
//
//    }
    public static void pintar_mesas(JLabel label_mesa, String mesa) {

        //0 - oucupado - amarelo, 1 - livre - verde 
        try {
            System.out.println("QTD lugares oucupados: " + itemPedidosDao.getQtdItensByIdPedido(pedidoDao.getLastPedidoByMesa(mesa)));

            long numero_lugares_oucupado = itemPedidosDao.getQtdItensByIdPedido(pedidoDao.getLastPedidoByMesa(mesa));

            //Mesa Oucupada
            if (numero_lugares_oucupado > 0) {
                label_mesa.setBackground(new Color(255, 153, 51));
                label_mesa.setOpaque(true);
            }
        } catch (Exception e) {
        }

    }

    public static void mesas_livres(JLabel label_mesa) {
        label_mesa.setBackground(new Color(51, 153, 0));
        label_mesa.setOpaque(true);
    }

    private void procedimento_mesas_livre() {

        lb_mesa_01.setBackground(new Color(51, 153, 0));
        lb_mesa_01.setOpaque(true);
        pintar_mesas(lb_mesa_01, "MESA 1");

        lb_mesa_02.setBackground(new Color(51, 153, 0));
        lb_mesa_02.setOpaque(true);
        pintar_mesas(lb_mesa_02, "MESA 2");

        lb_mesa_03.setBackground(new Color(51, 153, 0));
        lb_mesa_03.setOpaque(true);
        pintar_mesas(lb_mesa_03, "MESA 3");

        lb_mesa_04.setBackground(new Color(51, 153, 0));
        lb_mesa_04.setOpaque(true);
        pintar_mesas(lb_mesa_04, "MESA 4");

        lb_mesa_05.setBackground(new Color(51, 153, 0));
        lb_mesa_05.setOpaque(true);
        pintar_mesas(lb_mesa_05, "MESA 5");

        lb_mesa_06.setBackground(new Color(51, 153, 0));
        lb_mesa_06.setOpaque(true);
        pintar_mesas(lb_mesa_06, "MESA 6");

        lb_mesa_07.setBackground(new Color(51, 153, 0));
        lb_mesa_07.setOpaque(true);
        pintar_mesas(lb_mesa_07, "MESA 7");

        lb_mesa_08.setBackground(new Color(51, 153, 0));
        lb_mesa_08.setOpaque(true);
        pintar_mesas(lb_mesa_08, "MESA 8");

        lb_mesa_09.setBackground(new Color(51, 153, 0));
        lb_mesa_09.setOpaque(true);
        pintar_mesas(lb_mesa_09, "MESA 9");

        lb_mesa_10.setBackground(new Color(51, 153, 0));
        lb_mesa_10.setOpaque(true);
        pintar_mesas(lb_mesa_10, "MESA 10");

        lb_mesa_11.setBackground(new Color(51, 153, 0));
        lb_mesa_11.setOpaque(true);
        pintar_mesas(lb_mesa_11, "MESA 11");

        lb_mesa_12.setBackground(new Color(51, 153, 0));
        lb_mesa_12.setOpaque(true);
        pintar_mesas(lb_mesa_12, "MESA 12");

        lb_mesa_13.setBackground(new Color(51, 153, 0));
        lb_mesa_13.setOpaque(true);
        pintar_mesas(lb_mesa_13, "MESA 13");

        lb_mesa_14.setBackground(new Color(51, 153, 0));
        lb_mesa_14.setOpaque(true);
        pintar_mesas(lb_mesa_14, "MESA 14");

        lb_mesa_15.setBackground(new Color(51, 153, 0));
        lb_mesa_15.setOpaque(true);
        pintar_mesas(lb_mesa_15, "MESA 15");

        lb_mesa_16.setBackground(new Color(51, 153, 0));
        lb_mesa_16.setOpaque(true);
        pintar_mesas(lb_mesa_16, "MESA 16");

        lb_mesa_17.setBackground(new Color(51, 153, 0));
        lb_mesa_17.setOpaque(true);
        pintar_mesas(lb_mesa_17, "MESA 17");

        lb_mesa_18.setBackground(new Color(51, 153, 0));
        lb_mesa_18.setOpaque(true);
        pintar_mesas(lb_mesa_18, "MESA 18");

        lb_mesa_19.setBackground(new Color(51, 153, 0));
        lb_mesa_19.setOpaque(true);
        pintar_mesas(lb_mesa_19, "MESA 19");

        lb_mesa_20.setBackground(new Color(51, 153, 0));
        lb_mesa_20.setOpaque(true);
        pintar_mesas(lb_mesa_20, "MESA 20");

        lb_mesa_21.setBackground(new Color(51, 153, 0));
        lb_mesa_21.setOpaque(true);
        pintar_mesas(lb_mesa_21, "MESA 21");

        lb_mesa_22.setBackground(new Color(51, 153, 0));
        lb_mesa_22.setOpaque(true);
        pintar_mesas(lb_mesa_22, "MESA 22");

        lb_mesa_23.setBackground(new Color(51, 153, 0));
        lb_mesa_23.setOpaque(true);
        pintar_mesas(lb_mesa_23, "MESA 23");

        lb_mesa_24.setBackground(new Color(51, 153, 0));
        lb_mesa_24.setOpaque(true);
        pintar_mesas(lb_mesa_24, "MESA 24");

        lb_mesa_25.setBackground(new Color(51, 153, 0));
        lb_mesa_25.setOpaque(true);
        pintar_mesas(lb_mesa_25, "MESA 25");

        lb_mesa_26.setBackground(new Color(51, 153, 0));
        lb_mesa_26.setOpaque(true);
        pintar_mesas(lb_mesa_26, "MESA 26");

        lb_mesa_27.setBackground(new Color(51, 153, 0));
        lb_mesa_27.setOpaque(true);
        pintar_mesas(lb_mesa_27, "MESA 27");

        lb_mesa_28.setBackground(new Color(51, 153, 0));
        lb_mesa_28.setOpaque(true);
        pintar_mesas(lb_mesa_28, "MESA 28");

        lb_mesa_29.setBackground(new Color(51, 153, 0));
        lb_mesa_29.setOpaque(true);
        pintar_mesas(lb_mesa_29, "MESA 29");

        lb_mesa_30.setBackground(new Color(51, 153, 0));
        lb_mesa_30.setOpaque(true);
        pintar_mesas(lb_mesa_30, "MESA 30");

        lb_mesa_31.setBackground(new Color(51, 153, 0));
        lb_mesa_31.setOpaque(true);
        pintar_mesas(lb_mesa_31, "MESA 31");

        lb_mesa_32.setBackground(new Color(51, 153, 0));
        lb_mesa_32.setOpaque(true);
        pintar_mesas(lb_mesa_32, "MESA 32");

        lb_mesa_33.setBackground(new Color(51, 153, 0));
        lb_mesa_33.setOpaque(true);
        pintar_mesas(lb_mesa_33, "MESA 33");

        lb_mesa_34.setBackground(new Color(51, 153, 0));
        lb_mesa_34.setOpaque(true);
        pintar_mesas(lb_mesa_34, "MESA 34");

        lb_mesa_35.setBackground(new Color(51, 153, 0));
        lb_mesa_35.setOpaque(true);
        pintar_mesas(lb_mesa_35, "MESA 35");

        lb_mesa_36.setBackground(new Color(51, 153, 0));
        lb_mesa_36.setOpaque(true);
        pintar_mesas(lb_mesa_36, "MESA 36");

        lb_mesa_37.setBackground(new Color(51, 153, 0));
        lb_mesa_37.setOpaque(true);
        pintar_mesas(lb_mesa_37, "MESA 37");

        lb_mesa_38.setBackground(new Color(51, 153, 0));
        lb_mesa_38.setOpaque(true);
        pintar_mesas(lb_mesa_38, "MESA 38");

        lb_mesa_39.setBackground(new Color(51, 153, 0));
        lb_mesa_39.setOpaque(true);
        pintar_mesas(lb_mesa_39, "MESA 39");

        lb_mesa_40.setBackground(new Color(51, 153, 0));
        lb_mesa_40.setOpaque(true);
        pintar_mesas(lb_mesa_40, "MESA 40");
    }

    private void abertura_primeiro_turno() {

        this.turno = new Turno();
        this.turno.setData(new Date());
        this.turno.setHoraAbertura(new Date());
        this.turno.setHoraFecho(null);
        this.turno.setTurno(DVML.PRIMEIRO_TURNO);
        this.turno.setFkUsuario(usuarioDao.findTbUsuario(this.idUser));

        try {
            turnoDao.create(this.turno);
//            controlo_turno();
            procedimento_abrir_mesas();
            JOptionPane.showMessageDialog(null, "Abertura efectuada com sucesso!...");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Falha na abertura do 1º turno!...", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void abertura_segundo_turno() {

        if (turnoDao.existe_fecho_by_data(new Date(), DVML.PRIMEIRO_TURNO)) {

            this.turno = new Turno();
            this.turno.setData(new Date());
            this.turno.setHoraAbertura(new Date());
            this.turno.setHoraFecho(null);
            this.turno.setTurno(DVML.SEGUNDO_TURNO);
            this.turno.setFkUsuario(usuarioDao.findTbUsuario(this.idUser));

            try {
                turnoDao.create(this.turno);
//                controlo_turno();
                procedimento_abrir_mesas();
                JOptionPane.showMessageDialog(null, "Abertura efectuada com sucesso!...");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Falha na abertura do 2º turno!...", "ERRO", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Impossivel abrir o 2º turno sem fechar o 1º turno!...", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void enable_mesas(boolean status) {

        btn_mesa_1.setEnabled(status);
        btn_mesa_2.setEnabled(status);
        btn_mesa_3.setEnabled(status);
        btn_mesa_4.setEnabled(status);
        btn_mesa_5.setEnabled(status);
        btn_mesa_6.setEnabled(status);
        btn_mesa_7.setEnabled(status);
        btn_mesa_8.setEnabled(status);
        btn_mesa_9.setEnabled(status);
        btn_mesa_10.setEnabled(status);
        btn_mesa_11.setEnabled(status);
        btn_mesa_12.setEnabled(status);
        btn_mesa_13.setEnabled(status);
        btn_mesa_14.setEnabled(status);
        btn_mesa_15.setEnabled(status);
        btn_mesa_16.setEnabled(status);
        btn_mesa_17.setEnabled(status);
        btn_mesa_18.setEnabled(status);
        btn_mesa_19.setEnabled(status);
        btn_mesa_20.setEnabled(status);
        btn_mesa_21.setEnabled(status);
        btn_mesa_22.setEnabled(status);
        btn_mesa_23.setEnabled(status);
        btn_mesa_24.setEnabled(status);
        btn_mesa_25.setEnabled(status);
        btn_mesa_26.setEnabled(status);
        btn_mesa_27.setEnabled(status);
        btn_mesa_28.setEnabled(status);
        btn_mesa_29.setEnabled(status);
        btn_mesa_30.setEnabled(status);
        btn_mesa_31.setEnabled(status);
        btn_mesa_32.setEnabled(status);
        btn_mesa_33.setEnabled(status);
        btn_mesa_34.setEnabled(status);
        btn_mesa_35.setEnabled(status);
        btn_mesa_36.setEnabled(status);
        btn_mesa_37.setEnabled(status);
        btn_mesa_38.setEnabled(status);
        btn_mesa_39.setEnabled(status);
        btn_mesa_40.setEnabled(status);
//        btn_vendas_pontuais.setEnabled(status);

    }

    private void procedimento_abrir_mesas() {

        if (turnoDao.existe_abertura_by_data(new Date(), DVML.PRIMEIRO_TURNO) && !turnoDao.existe_fecho_by_data(new Date(), DVML.PRIMEIRO_TURNO)) {
            enable_mesas(true);
        } else if (turnoDao.existe_fecho_by_data(new Date(), DVML.PRIMEIRO_TURNO)
                && turnoDao.existe_abertura_by_data(new Date(), DVML.SEGUNDO_TURNO)
                && !turnoDao.existe_fecho_by_data(new Date(), DVML.SEGUNDO_TURNO)) {
            enable_mesas(true);
        } else {
            enable_mesas(false);
        }

    }

//    @Override
//    public void run() {
//
//        while (true) {
//
//            try {
//                Thread.sleep(6000);
//                procedimento_mesas_livre();
//                System.out.println("cheguei aqui dallas");
//            } catch (InterruptedException ex) {
//                Logger.getLogger(MesasTranferenciasVisao.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//        }
//
//    }

    private void activar_button_mesa(boolean bt1, boolean bt2, boolean bt3, boolean bt4, boolean bt5, boolean bt6,
            boolean bt7, boolean bt8, boolean bt9, boolean bt10, boolean bt11, boolean bt12,
            boolean bt13, boolean bt14, boolean bt15, boolean bt16, boolean bt17, boolean bt18,
            boolean bt19, boolean bt20, boolean bt21, boolean bt22, boolean bt23, boolean bt24,
            boolean bt25, boolean bt26, boolean bt27, boolean bt28, boolean bt29, boolean bt30,
            boolean bt31, boolean bt32, boolean bt33, boolean bt34, boolean bt35, boolean bt36,
            boolean bt37, boolean bt38, boolean bt39, boolean bt40) {

        status_button_lugar(true);
        btn_mesa_1.setEnabled(bt1);
        btn_mesa_2.setEnabled(bt2);
        btn_mesa_3.setEnabled(bt3);
        btn_mesa_4.setEnabled(bt4);
        btn_mesa_5.setEnabled(bt5);
        btn_mesa_6.setEnabled(bt6);
        btn_mesa_7.setEnabled(bt7);
        btn_mesa_8.setEnabled(bt8);
        btn_mesa_9.setEnabled(bt9);
        btn_mesa_10.setEnabled(bt10);
        btn_mesa_11.setEnabled(bt11);
        btn_mesa_12.setEnabled(bt12);
        btn_mesa_13.setEnabled(bt13);
        btn_mesa_14.setEnabled(bt14);
        btn_mesa_15.setEnabled(bt15);
        btn_mesa_16.setEnabled(bt16);
        btn_mesa_17.setEnabled(bt17);
        btn_mesa_18.setEnabled(bt18);
        btn_mesa_19.setEnabled(bt19);
        btn_mesa_20.setEnabled(bt20);
        btn_mesa_21.setEnabled(bt21);
        btn_mesa_22.setEnabled(bt22);
        btn_mesa_23.setEnabled(bt23);
        btn_mesa_24.setEnabled(bt24);
        btn_mesa_25.setEnabled(bt25);
        btn_mesa_26.setEnabled(bt26);
        btn_mesa_27.setEnabled(bt27);
        btn_mesa_28.setEnabled(bt28);
        btn_mesa_29.setEnabled(bt29);
        btn_mesa_30.setEnabled(bt30);
        btn_mesa_31.setEnabled(bt31);
        btn_mesa_32.setEnabled(bt32);
        btn_mesa_33.setEnabled(bt33);
        btn_mesa_34.setEnabled(bt34);
        btn_mesa_35.setEnabled(bt35);
        btn_mesa_36.setEnabled(bt36);
        btn_mesa_37.setEnabled(bt37);
        btn_mesa_38.setEnabled(bt38);
        btn_mesa_39.setEnabled(bt39);
        btn_mesa_40.setEnabled(bt40);

        mesaSelecionada = getDescricaoMesa();

    }

    private void status_button_lugar(boolean status) {
        btn_mesa_1.setEnabled(status);
        btn_mesa_2.setEnabled(status);
        btn_mesa_3.setEnabled(status);
        btn_mesa_4.setEnabled(status);
        btn_mesa_5.setEnabled(status);
        btn_mesa_6.setEnabled(status);
        btn_mesa_7.setEnabled(status);
        btn_mesa_8.setEnabled(status);
        btn_mesa_9.setEnabled(status);
        btn_mesa_10.setEnabled(status);
        btn_mesa_11.setEnabled(status);
        btn_mesa_12.setEnabled(status);
        btn_mesa_13.setEnabled(status);
        btn_mesa_14.setEnabled(status);
        btn_mesa_15.setEnabled(status);
        btn_mesa_16.setEnabled(status);
        btn_mesa_17.setEnabled(status);
        btn_mesa_18.setEnabled(status);
        btn_mesa_19.setEnabled(status);
        btn_mesa_20.setEnabled(status);
        btn_mesa_21.setEnabled(status);
        btn_mesa_22.setEnabled(status);
        btn_mesa_23.setEnabled(status);
        btn_mesa_24.setEnabled(status);
        btn_mesa_25.setEnabled(status);
        btn_mesa_26.setEnabled(status);
        btn_mesa_27.setEnabled(status);
        btn_mesa_28.setEnabled(status);
        btn_mesa_29.setEnabled(status);
        btn_mesa_30.setEnabled(status);
        btn_mesa_31.setEnabled(status);
        btn_mesa_32.setEnabled(status);
        btn_mesa_33.setEnabled(status);
        btn_mesa_34.setEnabled(status);
        btn_mesa_35.setEnabled(status);
        btn_mesa_36.setEnabled(status);
        btn_mesa_37.setEnabled(status);
        btn_mesa_38.setEnabled(status);
        btn_mesa_39.setEnabled(status);
        btn_mesa_40.setEnabled(status);

    }

    private String getDescricaoMesa() {

        if (!btn_mesa_1.isEnabled()) {
            return "MESA 1";
        } else if (!btn_mesa_2.isEnabled()) {
            return "MESA 2";
        } else if (!btn_mesa_3.isEnabled()) {
            return "MESA 3";
        } else if (!btn_mesa_4.isEnabled()) {
            return "MESA 4";
        } else if (!btn_mesa_5.isEnabled()) {
            return "MESA 5";
        } else if (!btn_mesa_6.isEnabled()) {
            return "MESA 6";
        } else if (!btn_mesa_7.isEnabled()) {
            return "MESA 7";
        } else if (!btn_mesa_8.isEnabled()) {
            return "MESA 8";
        } else if (!btn_mesa_9.isEnabled()) {
            return "MESA 9";
        } else if (!btn_mesa_10.isEnabled()) {
            return "MESA 10";
        } else if (!btn_mesa_11.isEnabled()) {
            return "MESA 11";
        } else if (!btn_mesa_12.isEnabled()) {
            return "MESA 12";
        } else if (!btn_mesa_13.isEnabled()) {
            return "MESA 13";
        } else if (!btn_mesa_14.isEnabled()) {
            return "MESA 14";
        } else if (!btn_mesa_15.isEnabled()) {
            return "MESA 15";
        } else if (!btn_mesa_16.isEnabled()) {
            return "MESA 16";
        } else if (!btn_mesa_17.isEnabled()) {
            return "MESA 17";
        } else if (!btn_mesa_18.isEnabled()) {
            return "MESA 18";
        } else if (!btn_mesa_19.isEnabled()) {
            return "MESA 19";
        } else if (!btn_mesa_20.isEnabled()) {
            return "MESA 20";
        } else if (!btn_mesa_21.isEnabled()) {
            return "MESA 21";
        } else if (!btn_mesa_22.isEnabled()) {
            return "MESA 22";
        } else if (!btn_mesa_23.isEnabled()) {
            return "MESA 23";
        } else if (!btn_mesa_24.isEnabled()) {
            return "MESA 24";
        } else if (!btn_mesa_25.isEnabled()) {
            return "MESA 25";
        } else if (!btn_mesa_26.isEnabled()) {
            return "MESA 26";
        } else if (!btn_mesa_27.isEnabled()) {
            return "MESA 27";
        } else if (!btn_mesa_28.isEnabled()) {
            return "MESA 28";
        } else if (!btn_mesa_29.isEnabled()) {
            return "MESA 29";
        } else if (!btn_mesa_30.isEnabled()) {
            return "MESA 30";
        } else if (!btn_mesa_31.isEnabled()) {
            return "MESA 31";
        } else if (!btn_mesa_32.isEnabled()) {
            return "MESA 32";
        } else if (!btn_mesa_33.isEnabled()) {
            return "MESA 33";
        } else if (!btn_mesa_34.isEnabled()) {
            return "MESA 34";
        } else if (!btn_mesa_35.isEnabled()) {
            return "MESA 35";
        } else if (!btn_mesa_36.isEnabled()) {
            return "MESA 36";
        } else if (!btn_mesa_37.isEnabled()) {
            return "MESA 37";
        } else if (!btn_mesa_38.isEnabled()) {
            return "MESA 38";
        } else if (!btn_mesa_39.isEnabled()) {
            return "MESA 39";
        } else if (!btn_mesa_40.isEnabled()) {
            return "MESA 40";
        }

        return "";
    }

    private int getIdPedidoMesaOrigem() {
        return itemPedidosClasseLocal.get(0).getFkPedidos().getPkPedido();

    }

    private void transferir_mesas() {
        System.err.println("Tranferencia de Mesas a acontecer ");
        int idPedidoOrigemMesa = getIdPedidoMesaOrigem();
        System.err.println("Mesa selecionda: " + mesaSelecionada);
        int idPedidoDestino = pedidoDao.getLastPedidoByDefignacaoMesaSemStatus(mesaSelecionada);

        if (idPedidoDestino == 0) {
            int idPedido = criar_pedido_transferencia();
            System.err.println("NOVO PEDIDO ID : " + idPedido);
            criar_item_pedido_transferencia(idPedido);
            PedidoDao.eliminarPedido(pedidoDao.findTbPedido(idPedidoOrigemMesa), conexao);
            JOptionPane.showMessageDialog(null, "Transferencia efectuada com sucesso.");
            dispose();

//            new PrincipalPedidosVisao(idUser, lugar, id_armazem, BDConexao.getInstancia()).setVisible(true);
        } else {
            criar_item_pedido_transferencia(idPedidoDestino);
            PedidoDao.eliminarPedido(pedidoDao.findTbPedido(idPedidoOrigemMesa), conexao);
            JOptionPane.showMessageDialog(null, "Transferencia efectuada com sucesso.");

        }

        dispose();
        PrincipalPedidosVisao.procedimento_mesas_livre();
    }

    private int criar_pedido_transferencia() {

        TbPedido pedido_local = new TbPedido();
        pedido_local.setStatusPedido(true);
        pedido_local.setDataPedido(new Date());
        pedido_local.setHoraPedido(new Date());
        pedido_local.setStatusPedido(false);
        pedido_local.setFkMesas(mesasDao.findTbMesas(mesasDao.getIdByDescricao(mesaSelecionada)));
        Integer idLastPedido = pedidoDao.criarComProcedimentos(pedido_local, conexao);
        return idLastPedido;

    }

    private void criar_item_pedido_transferencia(int idPedido) {

        for (int i = 0; i < itemPedidosClasseLocal.size(); i++) {
            TbItemPedidos item = itemPedidosClasseLocal.get(i);
            item.setFkPedidos(pedidoDao.findTbPedido(idPedido));
            try {
                itemPedidosDao.alterar_item_pedidos(item, conexao);
            } catch (Exception e) {
            }
        }
    }

//    private void transferir_mesas(){
//        
//        
//        
//    }
//    private void transferir_mesas()
//    {
//        TbItemPedidos itemPedidosLocal = new TbItemPedidos();
//        TbPedido pedidosLocal = new TbPedido();
//        pedidosLocal.setFkMesas(mesasDao.findTbMesas(mesasDao.getIdByDescricao( getDescricaoMesa() ) ) );
//        int cod_pedido = ( pedidoDao.getLastPedidoByDefignacaoMesaFALSE( mesa ) );
//        this.pedido = pedidoDao.findTbPedido( cod_pedido );
//        itemPedidosLocal.setFkLugares( lugarDao.findTbLugares( lugarDao.getIdByDescricao( getDescricaoLugar() ) ) );
//        itemPedidosLocal.setFkProdutos( produtoDao.findTbProduto( produtoDao.getIdByDescricao( designacao_produto ) ) );
//        itemPedidosLocal.setQtd( 1 );
//        itemPedidosLocal.setStatusConvertido( false );
//        /*Envia para a área da cozinha*/
//        //para enviar  da cozinha
//        itemPedidosLocal.setStatusEnviado( true );
//        //para saber se o prato ja foi feito 
//        itemPedidosLocal.setStatusEfectuado( false );
//
//        double total = itemPedidosLocal.getQtd() * precoDao.findTbPreco( precoDao.getUltimoIdPrecoByIdProduto( itemPedidosLocal.getFkProdutos().getCodigo() ) ).getPrecoVenda().doubleValue();
//        itemPedidosLocal.setTotalItem( total );
//        itemPedidosLocal.setFkPedidos( this.pedido );
//
//
//    }
//    
    private void mostrarListaPedidos() {
        for (int i = 0; i < itemPedidosClasseLocal.size(); i++) {
            TbItemPedidos get = itemPedidosClasseLocal.get(i);
            System.out.println("Lista de Pedidos " + get.getPkItemPedidos());

        }

    }
}
