/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import comercial.controller.ClientesController;
import comercial.controller.MesRhController;
import dao.MesRhDao;
import entity.TbCliente;
import java.util.Vector;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.BDConexao;
import util.JPAEntityMannagerFactoryUtil;

/**
 *
 * @author Domingos Dala Vunge
 */
public class MesesPagoClienteVisao extends javax.swing.JDialog
{

    private Vector<TbCliente> fonte_dados = null;
    private static EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;
    private static MesRhDao mesRhDao = new MesRhDao( emf );
    private static MesRhController mesRhController;
    private int clienteId, produtoId;

    public MesesPagoClienteVisao( java.awt.Frame parent, boolean modal, int clienteId, int produtoId, BDConexao conexao )
    {
        super( parent, modal );
        initComponents();
        setLocationRelativeTo( null );

        mesRhController = new MesRhController( conexao.getConnectionAtiva() );
        this.clienteId = clienteId;
        this.produtoId = produtoId;

        mesRhController.carregarMesesPagosEPorPagar( conexao.getConnectionAtiva(),
                clienteId,
                produtoId,
                tabela_meses_pagos, cmbMesPagar );

        // Ao clicar em btnAdicionar
        btnAdicionar.addActionListener( e ->
        {
            if ( cmbMesPagar.getItemCount() > 0 )
            {

                String mes = (String) cmbMesPagar.getItemAt( 0 ); // pega o primeiro mês
                ( (DefaultTableModel) tabela_mes_por_enviar.getModel() ).addRow( new Object[]
                {
                    mes
                } );
                cmbMesPagar.removeItemAt( 0 ); // remove da combobox

                cmbMesPagar.setSelectedIndex( 0 );
            }
        } );

    }

    public MesesPagoClienteVisao( java.awt.Frame parent, ClientesController clientesController, BDConexao conexao )
    {
        super( parent, true );
        initComponents();
        setLocationRelativeTo( null );

        mesRhController.carregarMesesPagosEPorPagar( conexao.getConnectionAtiva(),
                2,
                1, tabela_meses_pagos, cmbMesPagar );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_mes_por_enviar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_meses_pagos = new javax.swing.JTable();
        lbProduto1 = new javax.swing.JLabel();
        cmbMesPagar = new javax.swing.JComboBox();
        lbProduto2 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tabela_mes_por_enviar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tabela_mes_por_enviar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Designação"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabela_mes_por_enviar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tabela_mes_por_enviarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_mes_por_enviar);
        if (tabela_mes_por_enviar.getColumnModel().getColumnCount() > 0)
        {
            tabela_mes_por_enviar.getColumnModel().getColumn(0).setPreferredWidth(200);
        }

        tabela_meses_pagos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tabela_meses_pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Cod.", "Meses"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabela_meses_pagos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tabela_meses_pagosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela_meses_pagos);
        if (tabela_meses_pagos.getColumnModel().getColumnCount() > 0)
        {
            tabela_meses_pagos.getColumnModel().getColumn(0).setPreferredWidth(15);
            tabela_meses_pagos.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        lbProduto1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbProduto1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbProduto1.setText("Mês Pagos:");

        cmbMesPagar.setBackground(new java.awt.Color(0, 255, 255));
        cmbMesPagar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cmbMesPagar.setForeground(new java.awt.Color(0, 0, 51));
        cmbMesPagar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccione--" }));
        cmbMesPagar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbMesPagarActionPerformed(evt);
            }
        });

        lbProduto2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbProduto2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbProduto2.setText("Mês por pagar:");

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Button-Add-icon.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAdicionarActionPerformed(evt);
            }
        });

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        btnRemover.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbMesPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbMesPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOUT - VERMELHO/Logout 32x32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabela_mes_por_enviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_mes_por_enviarMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_tabela_mes_por_enviarMouseClicked


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabela_meses_pagosMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tabela_meses_pagosMouseClicked
    {//GEN-HEADEREND:event_tabela_meses_pagosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabela_meses_pagosMouseClicked

    private void cmbMesPagarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbMesPagarActionPerformed
    {//GEN-HEADEREND:event_cmbMesPagarActionPerformed


    }//GEN-LAST:event_cmbMesPagarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAdicionarActionPerformed
    {//GEN-HEADEREND:event_btnAdicionarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoverActionPerformed
    {//GEN-HEADEREND:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        remover_mes();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:

        procedimentoEnviar();


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( MesesPagoClienteVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( MesesPagoClienteVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( MesesPagoClienteVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( MesesPagoClienteVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
//                MesesPagoClienteVisao dialog = new MesesPagoClienteVisao( new javax.swing.JFrame(), true, 2, 1, new ClientesController( BDConexao.getInstancia() ), BDConexao.getInstancia() );
//                dialog.addWindowListener( new java.awt.event.WindowAdapter()
//                {
//                    @Override
//                    public void windowClosing( java.awt.event.WindowEvent e )
//                    {
//                        System.exit( 0 );
//                    }
//                } );
//                dialog.setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnRemover;
    public static javax.swing.JComboBox cmbMesPagar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbProduto1;
    private javax.swing.JLabel lbProduto2;
    private javax.swing.JTable tabela_mes_por_enviar;
    private javax.swing.JTable tabela_meses_pagos;
    // End of variables declaration//GEN-END:variables

// Função auxiliar para pegar índice do mês na lista original
    private int mesIndex( String mes )
    {
        String[] meses =
        {
            "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
            "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
        };
        for ( int i = 0; i < meses.length; i++ )
        {
            if ( meses[ i ].equals( mes ) )
            {
                return i;
            }
        }
        return -1;
    }

    private void remover_mes()
    {
        DefaultTableModel modelo = (DefaultTableModel) tabela_mes_por_enviar.getModel();
        String mes;
        if ( tabela_mes_por_enviar.getRowCount() - 1 >= 0 )
        {
            mes = modelo.getValueAt( tabela_mes_por_enviar.getRowCount() - 1, 0 ).toString();
            cmbMesPagar.insertItemAt( mes, 0 );
            cmbMesPagar.setSelectedIndex( 0 );
            modelo.removeRow( tabela_mes_por_enviar.getRowCount() - 1 );

        }
        else
        {
            JOptionPane.showMessageDialog( null, "Impossivel remover , tabela vazia", "ERRO", JOptionPane.ERROR_MESSAGE );
        }

    }

    private void procedimentoEnviar()
    {
        DefaultTableModel modelo = (DefaultTableModel) tabela_mes_por_enviar.getModel();

        for ( int i = 0; i < modelo.getRowCount(); i++ )
        {
            String mes = modelo.getValueAt( i, 0 ).toString();
            VendaUsuarioVisao.accao_codigo_interno_enter_busca_exterior_2(
                    produtoId, mes );
        }

        dispose();

    }

}
