/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import java.sql.Connection;
import dao.ItemPedidosDao;
import dao.PedidoDao;
import dao.TurnoDao;
import dao.UsuarioDao;
import entity.TbPedido;
import dao.CaixaDao;
import entity.Turno;
import java.awt.Color;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import util.BDConexao;
import util.DVML;
import util.JPAEntityMannagerFactoryUtil;

/**
 *
 * @author MartinhoLuis e Domingos Dala Vunge
 */
public class PrincipalLavandariaVisao extends javax.swing.JFrame implements Runnable
{

    private TbPedido pedidos = new TbPedido();
    private static EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;
    private static PedidoDao pedidoDao = new PedidoDao( emf );
    private static ItemPedidosDao itemPedidosDao = new ItemPedidosDao( emf );
    private UsuarioDao usuarioDao = new UsuarioDao( emf );
    private TurnoDao turnoDao = new TurnoDao( emf );
    private Turno turno;
    private static CaixaDao caixaDao;
    private int id_turno = 0;
    private BDConexao conexao;
    private Thread t;
    private int idUser = 0;
    private int id_armazem;

    public PrincipalLavandariaVisao( int idUser, int id_armazem, BDConexao conexao )
    {
        initComponents();
        //this.setExtendedState(   this.getExtendedState()|PrincipalPedidosVisao.MAXIMIZED_BOTH  );
        setLocationRelativeTo( null );
        t = new Thread( this );
        t.start();
        this.id_armazem = id_armazem;
        this.conexao = conexao;
        this.idUser = idUser;
        procedimento_mesas_livre();
        controlo_turno();
        procedimento_abrir_mesas();
        caixaDao = new CaixaDao( emf );
        verificarCaixa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_abertura_primeiro_turno = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_abertura_segundo_turno = new javax.swing.JButton();
        status_mensagem_primaria = new javax.swing.JLabel();
        status_mensagem_secundaria = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        btn_mesa_1 = new javax.swing.JButton();
        btn_mesa_2 = new javax.swing.JButton();
        btn_mesa_3 = new javax.swing.JButton();
        btn_mesa_4 = new javax.swing.JButton();
        btn_mesa_5 = new javax.swing.JButton();
        btn_mesa_6 = new javax.swing.JButton();
        btn_mesa_7 = new javax.swing.JButton();
        btn_mesa_9 = new javax.swing.JButton();
        btn_mesa_8 = new javax.swing.JButton();
        btn_mesa_10 = new javax.swing.JButton();
        btn_mesa_11 = new javax.swing.JButton();
        btn_mesa_12 = new javax.swing.JButton();
        btn_mesa_13 = new javax.swing.JButton();
        btn_mesa_14 = new javax.swing.JButton();
        btn_mesa_16 = new javax.swing.JButton();
        lb_mesa_05 = new javax.swing.JLabel();
        lb_mesa_02 = new javax.swing.JLabel();
        lb_mesa_04 = new javax.swing.JLabel();
        lb_mesa_03 = new javax.swing.JLabel();
        lb_mesa_01 = new javax.swing.JLabel();
        lb_mesa_06 = new javax.swing.JLabel();
        lb_mesa_07 = new javax.swing.JLabel();
        lb_mesa_08 = new javax.swing.JLabel();
        lb_mesa_09 = new javax.swing.JLabel();
        lb_mesa_10 = new javax.swing.JLabel();
        lb_mesa_11 = new javax.swing.JLabel();
        lb_mesa_12 = new javax.swing.JLabel();
        lb_mesa_13 = new javax.swing.JLabel();
        lb_mesa_14 = new javax.swing.JLabel();
        lb_mesa_15 = new javax.swing.JLabel();
        lb_mesa_16 = new javax.swing.JLabel();
        btn_mesa_15 = new javax.swing.JButton();
        btn_mesa_32 = new javax.swing.JButton();
        lb_mesa_32 = new javax.swing.JLabel();
        btn_mesa_24 = new javax.swing.JButton();
        lb_mesa_24 = new javax.swing.JLabel();
        lb_mesa_23 = new javax.swing.JLabel();
        btn_mesa_23 = new javax.swing.JButton();
        btn_mesa_31 = new javax.swing.JButton();
        lb_mesa_31 = new javax.swing.JLabel();
        lb_mesa_30 = new javax.swing.JLabel();
        btn_mesa_30 = new javax.swing.JButton();
        btn_mesa_22 = new javax.swing.JButton();
        lb_mesa_22 = new javax.swing.JLabel();
        lb_mesa_21 = new javax.swing.JLabel();
        btn_mesa_21 = new javax.swing.JButton();
        btn_mesa_29 = new javax.swing.JButton();
        lb_mesa_29 = new javax.swing.JLabel();
        lb_mesa_28 = new javax.swing.JLabel();
        btn_mesa_28 = new javax.swing.JButton();
        btn_mesa_20 = new javax.swing.JButton();
        lb_mesa_20 = new javax.swing.JLabel();
        btn_mesa_19 = new javax.swing.JButton();
        lb_mesa_19 = new javax.swing.JLabel();
        btn_mesa_27 = new javax.swing.JButton();
        lb_mesa_27 = new javax.swing.JLabel();
        lb_mesa_26 = new javax.swing.JLabel();
        btn_mesa_26 = new javax.swing.JButton();
        btn_mesa_18 = new javax.swing.JButton();
        lb_mesa_18 = new javax.swing.JLabel();
        btn_mesa_17 = new javax.swing.JButton();
        btn_mesa_25 = new javax.swing.JButton();
        lb_mesa_17 = new javax.swing.JLabel();
        lb_mesa_25 = new javax.swing.JLabel();
        btn_mesa_33 = new javax.swing.JButton();
        btn_mesa_34 = new javax.swing.JButton();
        lb_mesa_33 = new javax.swing.JLabel();
        lb_mesa_34 = new javax.swing.JLabel();
        btn_mesa_35 = new javax.swing.JButton();
        lb_mesa_35 = new javax.swing.JLabel();
        btn_mesa_36 = new javax.swing.JButton();
        lb_mesa_36 = new javax.swing.JLabel();
        btn_mesa_37 = new javax.swing.JButton();
        lb_mesa_37 = new javax.swing.JLabel();
        btn_mesa_38 = new javax.swing.JButton();
        lb_mesa_38 = new javax.swing.JLabel();
        btn_mesa_39 = new javax.swing.JButton();
        lb_mesa_39 = new javax.swing.JLabel();
        btn_mesa_40 = new javax.swing.JButton();
        lb_mesa_40 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("GESTÃO  DE  MESAS");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("1º Turno"));

        btn_abertura_primeiro_turno.setText("Abertura");
        btn_abertura_primeiro_turno.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_abertura_primeiro_turnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_abertura_primeiro_turno, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_abertura_primeiro_turno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("2º Turno"));

        btn_abertura_segundo_turno.setText("Abertura");
        btn_abertura_segundo_turno.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_abertura_segundo_turnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_abertura_segundo_turno, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_abertura_segundo_turno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        status_mensagem_primaria.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        status_mensagem_primaria.setForeground(new java.awt.Color(255, 0, 51));
        status_mensagem_primaria.setText("sahdbvhsdva");

        status_mensagem_secundaria.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        status_mensagem_secundaria.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(status_mensagem_secundaria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(status_mensagem_primaria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status_mensagem_primaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(status_mensagem_secundaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOUT - VERMELHO/Logout 32x32.png"))); // NOI18N
        jButton17.setText("SAIR");
        jButton17.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton17ActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_mesa_1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/mesa_teste.jpg"))); // NOI18N
        btn_mesa_1.setText("1");
        btn_mesa_1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 80));

        btn_mesa_2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_2.setText("2");
        btn_mesa_2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 60, 80));

        btn_mesa_3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_3.setText("3");
        btn_mesa_3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 60, 80));

        btn_mesa_4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_4.setText("4");
        btn_mesa_4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 70, 80));

        btn_mesa_5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_5.setText("5");
        btn_mesa_5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 70, 80));

        btn_mesa_6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_6.setText("6");
        btn_mesa_6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 70, 80));

        btn_mesa_7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_7.setText("7");
        btn_mesa_7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 70, 80));

        btn_mesa_9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_9.setText("9");
        btn_mesa_9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 80));

        btn_mesa_8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_8.setText("8");
        btn_mesa_8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 70, 80));

        btn_mesa_10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_10.setText("10");
        btn_mesa_10.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_10ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 60, 80));

        btn_mesa_11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_11.setText("11");
        btn_mesa_11.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_11ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 70, 80));

        btn_mesa_12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_12.setText("12");
        btn_mesa_12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_12ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 70, 80));

        btn_mesa_13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_13.setText("13");
        btn_mesa_13.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_13ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 70, 80));

        btn_mesa_14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_14.setText("14");
        btn_mesa_14.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_14ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 70, 80));

        btn_mesa_16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_16.setText("16");
        btn_mesa_16.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_16ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 70, 80));

        lb_mesa_05.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_05.setText("05");
        jPanel2.add(lb_mesa_05, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 80));

        lb_mesa_02.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_02.setText("02");
        jPanel2.add(lb_mesa_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 40, 80));

        lb_mesa_04.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_04.setText("04");
        jPanel2.add(lb_mesa_04, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 80));

        lb_mesa_03.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_03.setText("03");
        jPanel2.add(lb_mesa_03, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 80));

        lb_mesa_01.setBackground(new java.awt.Color(51, 153, 0));
        lb_mesa_01.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_01.setText("01");
        lb_mesa_01.setOpaque(true);
        jPanel2.add(lb_mesa_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 80));

        lb_mesa_06.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_06.setText("06");
        jPanel2.add(lb_mesa_06, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 40, 80));

        lb_mesa_07.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_07.setText("07");
        jPanel2.add(lb_mesa_07, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, 80));

        lb_mesa_08.setBackground(new java.awt.Color(255, 153, 51));
        lb_mesa_08.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_08.setText("08");
        jPanel2.add(lb_mesa_08, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 40, 80));

        lb_mesa_09.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_09.setText("09");
        jPanel2.add(lb_mesa_09, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 80));

        lb_mesa_10.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_10.setText("10");
        jPanel2.add(lb_mesa_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 40, 80));

        lb_mesa_11.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_11.setText("11");
        jPanel2.add(lb_mesa_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 80));

        lb_mesa_12.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_12.setText("12");
        jPanel2.add(lb_mesa_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 80));

        lb_mesa_13.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_13.setText("13");
        jPanel2.add(lb_mesa_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, 80));

        lb_mesa_14.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_14.setText("14");
        jPanel2.add(lb_mesa_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 40, 80));

        lb_mesa_15.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_15.setText("15");
        jPanel2.add(lb_mesa_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, -1, 80));

        lb_mesa_16.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_16.setText("16");
        jPanel2.add(lb_mesa_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, -1, 80));

        btn_mesa_15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_15.setText("15");
        btn_mesa_15.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_15ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 70, 80));

        btn_mesa_32.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_32.setText("32");
        btn_mesa_32.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_32ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 70, 80));

        lb_mesa_32.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_32.setText("32");
        jPanel2.add(lb_mesa_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, -1, 80));

        btn_mesa_24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_24.setText("24");
        btn_mesa_24.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_24ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 70, 80));

        lb_mesa_24.setBackground(new java.awt.Color(255, 153, 51));
        lb_mesa_24.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_24.setText("24");
        jPanel2.add(lb_mesa_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 40, 80));

        lb_mesa_23.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_23.setText("23");
        jPanel2.add(lb_mesa_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, -1, 80));

        btn_mesa_23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_23.setText("23");
        btn_mesa_23.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_23ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 70, 80));

        btn_mesa_31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_31.setText("31");
        btn_mesa_31.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_31ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 70, 80));

        lb_mesa_31.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_31.setText("31");
        jPanel2.add(lb_mesa_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, -1, 80));

        lb_mesa_30.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_30.setText("30");
        jPanel2.add(lb_mesa_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 40, 80));

        btn_mesa_30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_30.setText("30");
        btn_mesa_30.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_30ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 70, 80));

        btn_mesa_22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_22.setText("22");
        btn_mesa_22.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_22ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 70, 80));

        lb_mesa_22.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_22.setText("22");
        jPanel2.add(lb_mesa_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 40, 80));

        lb_mesa_21.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_21.setText("21");
        jPanel2.add(lb_mesa_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, 80));

        btn_mesa_21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_21.setText("21");
        btn_mesa_21.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_21ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 70, 80));

        btn_mesa_29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_29.setText("29");
        btn_mesa_29.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_29ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 70, 80));

        lb_mesa_29.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_29.setText("29");
        jPanel2.add(lb_mesa_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, 80));

        lb_mesa_28.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_28.setText("28");
        jPanel2.add(lb_mesa_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 80));

        btn_mesa_28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_28.setText("28");
        btn_mesa_28.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_28ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 70, 80));

        btn_mesa_20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_20.setText("20");
        btn_mesa_20.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_20ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 70, 80));

        lb_mesa_20.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_20.setText("20");
        jPanel2.add(lb_mesa_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, 80));

        btn_mesa_19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_19.setText("19");
        btn_mesa_19.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_19ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 70, 80));

        lb_mesa_19.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_19.setText("19");
        jPanel2.add(lb_mesa_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, 80));

        btn_mesa_27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_27.setText("27");
        btn_mesa_27.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_27ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 70, 80));

        lb_mesa_27.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_27.setText("27");
        jPanel2.add(lb_mesa_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, 80));

        lb_mesa_26.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_26.setText("26");
        jPanel2.add(lb_mesa_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 40, 80));

        btn_mesa_26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_26.setText("26");
        btn_mesa_26.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_26ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 70, 80));

        btn_mesa_18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_18.setText("18");
        btn_mesa_18.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_18ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, 80));

        lb_mesa_18.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_18.setText("18");
        jPanel2.add(lb_mesa_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 40, 80));

        btn_mesa_17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/mesa_teste.jpg"))); // NOI18N
        btn_mesa_17.setText("17");
        btn_mesa_17.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_17ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 80));

        btn_mesa_25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_25.setText("25");
        btn_mesa_25.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_25ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 80));

        lb_mesa_17.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_17.setText("17");
        jPanel2.add(lb_mesa_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 80));

        lb_mesa_25.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_25.setText("25");
        jPanel2.add(lb_mesa_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, 80));

        btn_mesa_33.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_33.setText("33");
        btn_mesa_33.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_33ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 70, 80));

        btn_mesa_34.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_34.setText("34");
        btn_mesa_34.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_34ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 70, 80));

        lb_mesa_33.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_33.setText("33");
        jPanel2.add(lb_mesa_33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 80));

        lb_mesa_34.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_34.setText("34");
        jPanel2.add(lb_mesa_34, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 40, 80));

        btn_mesa_35.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_35.setText("35");
        btn_mesa_35.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_35ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_35, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 70, 80));

        lb_mesa_35.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_35.setText("35");
        jPanel2.add(lb_mesa_35, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, 80));

        btn_mesa_36.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_36.setText("36");
        btn_mesa_36.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_36ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_36, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 70, 80));

        lb_mesa_36.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_36.setText("36");
        jPanel2.add(lb_mesa_36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, 80));

        btn_mesa_37.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_37.setText("37");
        btn_mesa_37.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_37ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_37, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 70, 80));

        lb_mesa_37.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_37.setText("37");
        jPanel2.add(lb_mesa_37, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, 80));

        btn_mesa_38.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_38.setText("38");
        btn_mesa_38.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_38ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_38, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 70, 80));

        lb_mesa_38.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_38.setText("38");
        jPanel2.add(lb_mesa_38, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 40, 80));

        btn_mesa_39.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_39.setText("39");
        btn_mesa_39.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_39ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_39, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 70, 80));

        lb_mesa_39.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_39.setText("39");
        jPanel2.add(lb_mesa_39, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, -1, 80));

        btn_mesa_40.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_mesa_40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_mesas/mesa_teste.jpg"))); // NOI18N
        btn_mesa_40.setText("40");
        btn_mesa_40.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_mesa_40ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mesa_40, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, 70, 80));

        lb_mesa_40.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lb_mesa_40.setText("40");
        jPanel2.add(lb_mesa_40, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, -1, 80));

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1-50", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("51-100", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("101-150", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("151-200", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("201-250", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("251-300", jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("301-350", jPanel11);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("351-400", jPanel12);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("401-450", jPanel13);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("451-500", jPanel14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(716, 716, 716)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void btn_mesa_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_1ActionPerformed
        new GestaoPedidosVisao( btn_mesa_1.getText(), "", this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_1ActionPerformed

    private void btn_mesa_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_2ActionPerformed
        // TODO add your handling code here:
        new GestaoPedidosVisao( btn_mesa_2.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_2ActionPerformed

    private void btn_mesa_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_3ActionPerformed
        // TODO add your handling code here:
        new GestaoPedidosVisao( btn_mesa_3.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_3ActionPerformed

    private void btn_mesa_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_4ActionPerformed
        new GestaoPedidosVisao( btn_mesa_4.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_4ActionPerformed

    private void btn_mesa_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_10ActionPerformed
        new GestaoPedidosVisao( btn_mesa_10.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_10ActionPerformed

    private void btn_mesa_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_5ActionPerformed
        new GestaoPedidosVisao( btn_mesa_5.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_5ActionPerformed

    private void btn_mesa_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_6ActionPerformed
        new GestaoPedidosVisao( btn_mesa_6.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_6ActionPerformed

    private void btn_mesa_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_7ActionPerformed
        new GestaoPedidosVisao( btn_mesa_7.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_7ActionPerformed

    private void btn_mesa_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_9ActionPerformed
        new GestaoPedidosVisao( btn_mesa_9.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_9ActionPerformed

    private void btn_mesa_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_8ActionPerformed
        new GestaoPedidosVisao( btn_mesa_8.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_8ActionPerformed

    private void btn_mesa_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_11ActionPerformed
        new GestaoPedidosVisao( btn_mesa_11.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_11ActionPerformed

    private void btn_mesa_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_12ActionPerformed
        new GestaoPedidosVisao( btn_mesa_12.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_12ActionPerformed

    private void btn_mesa_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_13ActionPerformed
        new GestaoPedidosVisao( btn_mesa_13.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_13ActionPerformed

    private void btn_mesa_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_14ActionPerformed
        new GestaoPedidosVisao( btn_mesa_14.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_14ActionPerformed

    private void btn_mesa_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_16ActionPerformed
        new GestaoPedidosVisao( btn_mesa_16.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_16ActionPerformed

    private void btn_mesa_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesa_15ActionPerformed
        // TODO add your handling code here:
        new GestaoPedidosVisao( btn_mesa_15.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_15ActionPerformed

    private void btn_abertura_primeiro_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abertura_primeiro_turnoActionPerformed
        // TODO add your handling code here:
        abertura_primeiro_turno();
    }//GEN-LAST:event_btn_abertura_primeiro_turnoActionPerformed

    private void btn_abertura_segundo_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abertura_segundo_turnoActionPerformed
        // TODO add your handling code here:
        abertura_segundo_turno();
    }//GEN-LAST:event_btn_abertura_segundo_turnoActionPerformed

    private void btn_mesa_32ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_32ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_32ActionPerformed
        new GestaoPedidosVisao( btn_mesa_32.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_32ActionPerformed

    private void btn_mesa_24ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_24ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_24ActionPerformed
        new GestaoPedidosVisao( btn_mesa_24.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_24ActionPerformed

    private void btn_mesa_23ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_23ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_23ActionPerformed
        new GestaoPedidosVisao( btn_mesa_23.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_23ActionPerformed

    private void btn_mesa_31ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_31ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_31ActionPerformed
        new GestaoPedidosVisao( btn_mesa_31.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_31ActionPerformed

    private void btn_mesa_30ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_30ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_30ActionPerformed
        new GestaoPedidosVisao( btn_mesa_30.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_30ActionPerformed

    private void btn_mesa_22ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_22ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_22ActionPerformed
        new GestaoPedidosVisao( btn_mesa_22.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_22ActionPerformed

    private void btn_mesa_21ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_21ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_21ActionPerformed
        new GestaoPedidosVisao( btn_mesa_21.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_21ActionPerformed

    private void btn_mesa_29ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_29ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_29ActionPerformed
        new GestaoPedidosVisao( btn_mesa_29.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_29ActionPerformed

    private void btn_mesa_28ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_28ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_28ActionPerformed
        new GestaoPedidosVisao( btn_mesa_28.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_28ActionPerformed

    private void btn_mesa_20ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_20ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_20ActionPerformed
        new GestaoPedidosVisao( btn_mesa_20.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_20ActionPerformed

    private void btn_mesa_19ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_19ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_19ActionPerformed
        new GestaoPedidosVisao( btn_mesa_19.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_19ActionPerformed

    private void btn_mesa_27ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_27ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_27ActionPerformed
        new GestaoPedidosVisao( btn_mesa_27.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_27ActionPerformed

    private void btn_mesa_26ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_26ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_26ActionPerformed
        new GestaoPedidosVisao( btn_mesa_26.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_26ActionPerformed

    private void btn_mesa_18ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_18ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_18ActionPerformed
        new GestaoPedidosVisao( btn_mesa_18.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_18ActionPerformed

    private void btn_mesa_17ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_17ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_17ActionPerformed
        new GestaoPedidosVisao( btn_mesa_17.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_17ActionPerformed

    private void btn_mesa_25ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_25ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_25ActionPerformed
        new GestaoPedidosVisao( btn_mesa_25.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_25ActionPerformed

    private void btn_mesa_33ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_33ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_33ActionPerformed
        new GestaoPedidosVisao( btn_mesa_33.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_33ActionPerformed

    private void btn_mesa_34ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_34ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_34ActionPerformed
        new GestaoPedidosVisao( btn_mesa_34.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_34ActionPerformed

    private void btn_mesa_35ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_35ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_35ActionPerformed
        new GestaoPedidosVisao( btn_mesa_35.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_35ActionPerformed

    private void btn_mesa_36ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_36ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_36ActionPerformed
        new GestaoPedidosVisao( btn_mesa_36.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_36ActionPerformed

    private void btn_mesa_37ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_37ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_37ActionPerformed
        new GestaoPedidosVisao( btn_mesa_37.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_37ActionPerformed

    private void btn_mesa_38ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_38ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_38ActionPerformed
        new GestaoPedidosVisao( btn_mesa_38.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_38ActionPerformed

    private void btn_mesa_39ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_39ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_39ActionPerformed
        new GestaoPedidosVisao( btn_mesa_39.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_39ActionPerformed

    private void btn_mesa_40ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_mesa_40ActionPerformed
    {//GEN-HEADEREND:event_btn_mesa_40ActionPerformed
        new GestaoPedidosVisao( btn_mesa_40.getText(), "",this.idUser, id_armazem, conexao ).show();
    }//GEN-LAST:event_btn_mesa_40ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( PrincipalLavandariaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( PrincipalLavandariaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( PrincipalLavandariaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( PrincipalLavandariaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new PrincipalLavandariaVisao( 15, 1, BDConexao.getInstancia() ).setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_abertura_primeiro_turno;
    public static javax.swing.JButton btn_abertura_segundo_turno;
    private javax.swing.JButton btn_mesa_1;
    private javax.swing.JButton btn_mesa_10;
    private javax.swing.JButton btn_mesa_11;
    private javax.swing.JButton btn_mesa_12;
    private javax.swing.JButton btn_mesa_13;
    private javax.swing.JButton btn_mesa_14;
    private javax.swing.JButton btn_mesa_15;
    private javax.swing.JButton btn_mesa_16;
    private javax.swing.JButton btn_mesa_17;
    private javax.swing.JButton btn_mesa_18;
    private javax.swing.JButton btn_mesa_19;
    private javax.swing.JButton btn_mesa_2;
    private javax.swing.JButton btn_mesa_20;
    private javax.swing.JButton btn_mesa_21;
    private javax.swing.JButton btn_mesa_22;
    private javax.swing.JButton btn_mesa_23;
    private javax.swing.JButton btn_mesa_24;
    private javax.swing.JButton btn_mesa_25;
    private javax.swing.JButton btn_mesa_26;
    private javax.swing.JButton btn_mesa_27;
    private javax.swing.JButton btn_mesa_28;
    private javax.swing.JButton btn_mesa_29;
    private javax.swing.JButton btn_mesa_3;
    private javax.swing.JButton btn_mesa_30;
    private javax.swing.JButton btn_mesa_31;
    private javax.swing.JButton btn_mesa_32;
    private javax.swing.JButton btn_mesa_33;
    private javax.swing.JButton btn_mesa_34;
    private javax.swing.JButton btn_mesa_35;
    private javax.swing.JButton btn_mesa_36;
    private javax.swing.JButton btn_mesa_37;
    private javax.swing.JButton btn_mesa_38;
    private javax.swing.JButton btn_mesa_39;
    private javax.swing.JButton btn_mesa_4;
    private javax.swing.JButton btn_mesa_40;
    private javax.swing.JButton btn_mesa_5;
    private javax.swing.JButton btn_mesa_6;
    private javax.swing.JButton btn_mesa_7;
    private javax.swing.JButton btn_mesa_8;
    private javax.swing.JButton btn_mesa_9;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JLabel lb_mesa_01;
    public static javax.swing.JLabel lb_mesa_02;
    public static javax.swing.JLabel lb_mesa_03;
    public static javax.swing.JLabel lb_mesa_04;
    public static javax.swing.JLabel lb_mesa_05;
    public static javax.swing.JLabel lb_mesa_06;
    public static javax.swing.JLabel lb_mesa_07;
    public static javax.swing.JLabel lb_mesa_08;
    public static javax.swing.JLabel lb_mesa_09;
    public static javax.swing.JLabel lb_mesa_10;
    public static javax.swing.JLabel lb_mesa_11;
    public static javax.swing.JLabel lb_mesa_12;
    public static javax.swing.JLabel lb_mesa_13;
    public static javax.swing.JLabel lb_mesa_14;
    public static javax.swing.JLabel lb_mesa_15;
    public static javax.swing.JLabel lb_mesa_16;
    public static javax.swing.JLabel lb_mesa_17;
    public static javax.swing.JLabel lb_mesa_18;
    public static javax.swing.JLabel lb_mesa_19;
    public static javax.swing.JLabel lb_mesa_20;
    public static javax.swing.JLabel lb_mesa_21;
    public static javax.swing.JLabel lb_mesa_22;
    public static javax.swing.JLabel lb_mesa_23;
    public static javax.swing.JLabel lb_mesa_24;
    public static javax.swing.JLabel lb_mesa_25;
    public static javax.swing.JLabel lb_mesa_26;
    public static javax.swing.JLabel lb_mesa_27;
    public static javax.swing.JLabel lb_mesa_28;
    public static javax.swing.JLabel lb_mesa_29;
    public static javax.swing.JLabel lb_mesa_30;
    public static javax.swing.JLabel lb_mesa_31;
    public static javax.swing.JLabel lb_mesa_32;
    public static javax.swing.JLabel lb_mesa_33;
    public static javax.swing.JLabel lb_mesa_34;
    public static javax.swing.JLabel lb_mesa_35;
    public static javax.swing.JLabel lb_mesa_36;
    public static javax.swing.JLabel lb_mesa_37;
    public static javax.swing.JLabel lb_mesa_38;
    public static javax.swing.JLabel lb_mesa_39;
    public static javax.swing.JLabel lb_mesa_40;
    public static javax.swing.JLabel status_mensagem_primaria;
    public static javax.swing.JLabel status_mensagem_secundaria;
    // End of variables declaration//GEN-END:variables

//    public static void pintar_mesas(JLabel label_mesa, String mesa) {
//
//        //0 - oucupado - amarelo, 1 - livre - verde 
//        try {
//            System.out.println("QTD lugares oucupados: " + itemPedidosDao.getQtdItensByIdPedido(pedidoDao.getLastPedidoByMesa(mesa)));
//
//            long numero_lugares_oucupado = itemPedidosDao.getQtdItensByIdPedido(pedidoDao.getLastPedidoByMesa(mesa));
//
//            //Mesa Oucupada
//            if (numero_lugares_oucupado > 0) {
//                label_mesa.setBackground(new Color(255, 153, 51));
//                label_mesa.setOpaque(true);
//            }
//        } catch (Exception e) {
//        }
//
//    }
    public static void pintar_mesas( JLabel label_mesa, String mesa )
    {

        //0 - oucupado - amarelo, 1 - livre - verde 
        try
        {
            System.out.println( "QTD lugares oucupados: " + itemPedidosDao.getQtdItensByIdPedido( pedidoDao.getLastPedidoByMesa( mesa ) ) );

            long numero_lugares_oucupado = itemPedidosDao.getQtdItensByIdPedido( pedidoDao.getLastPedidoByMesa( mesa ) );

            //Mesa Oucupada
            if ( numero_lugares_oucupado > 0 )
            {
                label_mesa.setBackground( new Color( 255, 153, 51 ) );
                label_mesa.setOpaque( true );
            }
        }
        catch ( Exception e )
        {
        }

    }

    public static void mesas_livres( JLabel label_mesa )
    {
        label_mesa.setBackground( new Color( 51, 153, 0 ) );
        label_mesa.setOpaque( true );
    }

    private void procedimento_mesas_livre()
    {

        lb_mesa_01.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_01.setOpaque( true );
        pintar_mesas( lb_mesa_01, "MESA 1" );

        lb_mesa_02.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_02.setOpaque( true );
        pintar_mesas( lb_mesa_02, "MESA 2" );

        lb_mesa_03.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_03.setOpaque( true );
        pintar_mesas( lb_mesa_03, "MESA 3" );

        lb_mesa_04.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_04.setOpaque( true );
        pintar_mesas( lb_mesa_04, "MESA 4" );

        lb_mesa_05.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_05.setOpaque( true );
        pintar_mesas( lb_mesa_05, "MESA 5" );

        lb_mesa_06.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_06.setOpaque( true );
        pintar_mesas( lb_mesa_06, "MESA 6" );

        lb_mesa_07.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_07.setOpaque( true );
        pintar_mesas( lb_mesa_07, "MESA 7" );

        lb_mesa_08.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_08.setOpaque( true );
        pintar_mesas( lb_mesa_08, "MESA 8" );

        lb_mesa_09.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_09.setOpaque( true );
        pintar_mesas( lb_mesa_09, "MESA 9" );

        lb_mesa_10.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_10.setOpaque( true );
        pintar_mesas( lb_mesa_10, "MESA 10" );

        lb_mesa_11.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_11.setOpaque( true );
        pintar_mesas( lb_mesa_11, "MESA 11" );

        lb_mesa_12.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_12.setOpaque( true );
        pintar_mesas( lb_mesa_12, "MESA 12" );

        lb_mesa_13.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_13.setOpaque( true );
        pintar_mesas( lb_mesa_13, "MESA 13" );

        lb_mesa_14.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_14.setOpaque( true );
        pintar_mesas( lb_mesa_14, "MESA 14" );

        lb_mesa_15.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_15.setOpaque( true );
        pintar_mesas( lb_mesa_15, "MESA 15" );

        lb_mesa_16.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_16.setOpaque( true );
        pintar_mesas( lb_mesa_16, "MESA 16" );

        lb_mesa_17.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_17.setOpaque( true );
        pintar_mesas( lb_mesa_17, "MESA 17" );

        lb_mesa_18.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_18.setOpaque( true );
        pintar_mesas( lb_mesa_18, "MESA 18" );

        lb_mesa_19.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_19.setOpaque( true );
        pintar_mesas( lb_mesa_19, "MESA 19" );

        lb_mesa_20.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_20.setOpaque( true );
        pintar_mesas( lb_mesa_20, "MESA 20" );

        lb_mesa_21.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_21.setOpaque( true );
        pintar_mesas( lb_mesa_21, "MESA 21" );

        lb_mesa_22.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_22.setOpaque( true );
        pintar_mesas( lb_mesa_22, "MESA 22" );

        lb_mesa_23.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_23.setOpaque( true );
        pintar_mesas( lb_mesa_23, "MESA 23" );

        lb_mesa_24.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_24.setOpaque( true );
        pintar_mesas( lb_mesa_24, "MESA 24" );

        lb_mesa_25.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_25.setOpaque( true );
        pintar_mesas( lb_mesa_25, "MESA 25" );

        lb_mesa_26.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_26.setOpaque( true );
        pintar_mesas( lb_mesa_26, "MESA 26" );

        lb_mesa_27.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_27.setOpaque( true );
        pintar_mesas( lb_mesa_27, "MESA 27" );

        lb_mesa_28.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_28.setOpaque( true );
        pintar_mesas( lb_mesa_28, "MESA 28" );

        lb_mesa_29.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_29.setOpaque( true );
        pintar_mesas( lb_mesa_29, "MESA 29" );

        lb_mesa_30.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_30.setOpaque( true );
        pintar_mesas( lb_mesa_30, "MESA 30" );

        lb_mesa_31.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_31.setOpaque( true );
        pintar_mesas( lb_mesa_31, "MESA 31" );

        lb_mesa_32.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_32.setOpaque( true );
        pintar_mesas( lb_mesa_32, "MESA 32" );

        lb_mesa_33.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_33.setOpaque( true );
        pintar_mesas( lb_mesa_33, "MESA 33" );

        lb_mesa_34.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_34.setOpaque( true );
        pintar_mesas( lb_mesa_34, "MESA 34" );

        lb_mesa_35.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_35.setOpaque( true );
        pintar_mesas( lb_mesa_35, "MESA 35" );

        lb_mesa_36.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_36.setOpaque( true );
        pintar_mesas( lb_mesa_36, "MESA 36" );

        lb_mesa_37.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_37.setOpaque( true );
        pintar_mesas( lb_mesa_37, "MESA 37" );

        lb_mesa_38.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_38.setOpaque( true );
        pintar_mesas( lb_mesa_38, "MESA 38" );

        lb_mesa_39.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_39.setOpaque( true );
        pintar_mesas( lb_mesa_39, "MESA 39" );

        lb_mesa_40.setBackground( new Color( 51, 153, 0 ) );
        lb_mesa_40.setOpaque( true );
        pintar_mesas( lb_mesa_40, "MESA 40" );
    }

    private void abertura_primeiro_turno()
    {

        this.turno = new Turno();
        this.turno.setData( new Date() );
        this.turno.setHoraAbertura( new Date() );
        this.turno.setHoraFecho( null );
        this.turno.setTurno( DVML.PRIMEIRO_TURNO );
        this.turno.setFkUsuario( usuarioDao.findTbUsuario( this.idUser ) );

        try
        {
            turnoDao.create( this.turno );
            controlo_turno();
            procedimento_abrir_mesas();
            JOptionPane.showMessageDialog( null, "Abertura efectuada com sucesso!..." );
        }
        catch ( Exception e )
        {

            JOptionPane.showMessageDialog( null, "Falha na abertura do 1º turno!...", "ERRO", JOptionPane.ERROR_MESSAGE );
        }

    }

    private void abertura_segundo_turno()
    {

        if ( turnoDao.existe_fecho_by_data( new Date(), DVML.PRIMEIRO_TURNO ) )
        {

            this.turno = new Turno();
            this.turno.setData( new Date() );
            this.turno.setHoraAbertura( new Date() );
            this.turno.setHoraFecho( null );
            this.turno.setTurno( DVML.SEGUNDO_TURNO );
            this.turno.setFkUsuario( usuarioDao.findTbUsuario( this.idUser ) );

            try
            {
                turnoDao.create( this.turno );
                controlo_turno();
                procedimento_abrir_mesas();
                JOptionPane.showMessageDialog( null, "Abertura efectuada com sucesso!..." );
            }
            catch ( Exception e )
            {
                JOptionPane.showMessageDialog( null, "Falha na abertura do 2º turno!...", "ERRO", JOptionPane.ERROR_MESSAGE );
            }

        }
        else
        {
            JOptionPane.showMessageDialog( null, "Impossivel abrir o 2º turno sem fechar o 1º turno!...", "ERRO", JOptionPane.ERROR_MESSAGE );
        }

    }

    private void controlo_turno()
    {

        /*1 - TURNO*/
        if ( turnoDao.existe_abertura_by_data( new Date(), DVML.PRIMEIRO_TURNO ) )
        {
            btn_abertura_primeiro_turno.setEnabled( false );
        }
        else
        {
            btn_abertura_primeiro_turno.setEnabled( true );
        }

        /*2 - TURNO*/
        if ( turnoDao.existe_abertura_by_data( new Date(), DVML.SEGUNDO_TURNO ) )
        {
            btn_abertura_segundo_turno.setEnabled( false );
        }
        else
        {
            btn_abertura_segundo_turno.setEnabled( true );
        }

    }

    private void enable_mesas( boolean status )
    {

        btn_mesa_1.setEnabled( status );
        btn_mesa_2.setEnabled( status );
        btn_mesa_3.setEnabled( status );
        btn_mesa_4.setEnabled( status );
        btn_mesa_5.setEnabled( status );
        btn_mesa_6.setEnabled( status );
        btn_mesa_7.setEnabled( status );
        btn_mesa_8.setEnabled( status );
        btn_mesa_9.setEnabled( status );
        btn_mesa_10.setEnabled( status );
        btn_mesa_11.setEnabled( status );
        btn_mesa_12.setEnabled( status );
        btn_mesa_13.setEnabled( status );
        btn_mesa_14.setEnabled( status );
        btn_mesa_15.setEnabled( status );
        btn_mesa_16.setEnabled( status );
        btn_mesa_17.setEnabled( status );
        btn_mesa_18.setEnabled( status );
        btn_mesa_19.setEnabled( status );
        btn_mesa_20.setEnabled( status );
        btn_mesa_21.setEnabled( status );
        btn_mesa_22.setEnabled( status );
        btn_mesa_23.setEnabled( status );
        btn_mesa_24.setEnabled( status );
        btn_mesa_25.setEnabled( status );
        btn_mesa_26.setEnabled( status );
        btn_mesa_27.setEnabled( status );
        btn_mesa_28.setEnabled( status );
        btn_mesa_29.setEnabled( status );
        btn_mesa_30.setEnabled( status );
        btn_mesa_31.setEnabled( status );
        btn_mesa_32.setEnabled( status );
        btn_mesa_33.setEnabled( status );
        btn_mesa_34.setEnabled( status );
        btn_mesa_35.setEnabled( status );
        btn_mesa_36.setEnabled( status );
        btn_mesa_37.setEnabled( status );
        btn_mesa_38.setEnabled( status );
        btn_mesa_39.setEnabled( status );
        btn_mesa_40.setEnabled( status );
//        btn_vendas_pontuais.setEnabled(status);

    }

    private void procedimento_abrir_mesas()
    {

        if ( turnoDao.existe_abertura_by_data( new Date(), DVML.PRIMEIRO_TURNO ) && !turnoDao.existe_fecho_by_data( new Date(), DVML.PRIMEIRO_TURNO ) )
        {
            enable_mesas( true );
        }
        else if ( turnoDao.existe_fecho_by_data( new Date(), DVML.PRIMEIRO_TURNO )
                && turnoDao.existe_abertura_by_data( new Date(), DVML.SEGUNDO_TURNO )
                && !turnoDao.existe_fecho_by_data( new Date(), DVML.SEGUNDO_TURNO ) )
        {
            enable_mesas( true );
        }
        else
        {
            enable_mesas( false );
        }

    }

    @Override
    public void run()
    {

        while ( true )
        {

            try
            {
                Thread.sleep( 6000 );
                procedimento_mesas_livre();
                System.out.println( "cheguei aqui dallas" );
            }
            catch ( InterruptedException ex )
            {
                Logger.getLogger( PrincipalLavandariaVisao.class.getName() ).log( Level.SEVERE, null, ex );
            }

        }

    }

    public static void verificarCaixa()
    {

        if ( !caixaDao.existeCaixas() )
        {
            btn_abertura_primeiro_turno.setEnabled( false );
            btn_abertura_segundo_turno.setEnabled( false );
            status_mensagem_primaria.setText( "" );
        }
        else if ( caixaDao.existe_abertura() && caixaDao.existe_fecho() )
        {
            btn_abertura_primeiro_turno.setEnabled( false );
            btn_abertura_segundo_turno.setEnabled( false );
            status_mensagem_primaria.setText( "Deves abrir o caixa" );

        }
        else
        {
            btn_abertura_primeiro_turno.setEnabled( true );
            btn_abertura_segundo_turno.setEnabled( true );
            status_mensagem_primaria.setText( "" );
        }
    }

}
