/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import java.sql.Connection;
import comercial.controller.ItemVendasController;
import controller.TipoProdutoController;
import dao.DadosInstituicaoDao;
import dao.NotasDao;
import dao.VendaDao;
import entity.Notas;
import entity.TbItemVenda;
import entity.TbProduto;
import entity.TbVenda;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import lista.ListaNotaDebito;
import lista.ListaVenda1;
import lista.ListaVenda2;
import lista.ListaVendaPorMesas;
import lista.ListaVendaRecolhas;
import lista.ListaVendaRecolhasReimpressao;
import modelo.TipoProdutoModelo;
import tesouraria.novo.util.AnyReport;
import util.BDConexao;
import util.DVML;
import util.DVML.Abreviacao;
import static util.DVML.SEGUNDA_VIA_CONFORMIDADE_COM_ORIGINAL;
import util.JPAEntityMannagerFactoryUtil;
import util.MetodosUtil;
import static visao.RecolhaPedidosVisao.abreviacao;

/**
 *
 * @author Domingos Dala Vunge
 */
public class ReemprimirFacturasRecolhaVisao extends javax.swing.JFrame
{

    /**
     * Creates new form UsuarioVisao
     */
    private static EntityManagerFactory emf = JPAEntityMannagerFactoryUtil.em;
    private static VendaDao vendaDao = new VendaDao( emf );
    private NotasDao notasDao = new NotasDao( emf );
    private static ItemVendasController itemVendasController;

    private TipoProdutoModelo tipoProdutoModelo;
    private DadosInstituicaoDao dadosInstituicaoDao;
    private TipoProdutoController tipoProdutoController;
    private static Abreviacao abreviacao, abreviacao_nota;
    private Frame parent;
    private static BDConexao conexao;

    public ReemprimirFacturasRecolhaVisao( java.awt.Frame parent, boolean modal, BDConexao conexao )
    {
        //this.parent =  parent1;
        this.parent = parent;
        this.conexao = conexao;
        itemVendasController = new ItemVendasController( ReemprimirFacturasRecolhaVisao.conexao );
//        ck_A4.setVisible( false);
        initComponents();
        confLabel();
        setLocationRelativeTo( null );
        try
        {

            setFolhaImpressora( dadosInstituicaoDao.findTbDadosInstituicao( 1 ).getImpressora() );
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }
//        rb_A6.setVisible( false );
        txtFactura.requestFocus();

    }

    public void confLabel()
    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        lbFactura = new javax.swing.JLabel();
        txtFactura = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ck_A4 = new javax.swing.JRadioButton();
        ck_simplificada = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reimprimir Documentos");

        lbFactura.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbFactura.setText("Ref. Documento:");

        txtFactura.setBackground(new java.awt.Color(0, 0, 153));
        txtFactura.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFactura.setForeground(new java.awt.Color(255, 255, 255));
        txtFactura.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFactura.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtFacturaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SAIR/sair_verde_32x32.png"))); // NOI18N
        jButton1.setText("Saír");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Número do Documento"));

        buttonGroup1.add(ck_A4);
        ck_A4.setText("A 4");
        ck_A4.setEnabled(false);
        ck_A4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ck_A4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(ck_simplificada);
        ck_simplificada.setSelected(true);
        ck_simplificada.setText("A6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ck_A4)
                .addGap(18, 18, 18)
                .addComponent(ck_simplificada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ck_A4)
                    .addComponent(ck_simplificada))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturaActionPerformed
        // TODO add your handling code here:
        procedimento_reimprimir();
        procedimentoReimprimirTicket();
    }//GEN-LAST:event_txtFacturaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ck_A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_A4ActionPerformed
//        actualizar_abreviacao();
    }//GEN-LAST:event_ck_A4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( ReemprimirFacturasRecolhaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( ReemprimirFacturasRecolhaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( ReemprimirFacturasRecolhaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( ReemprimirFacturasRecolhaVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                ReemprimirFacturasRecolhaVisao dialog = new ReemprimirFacturasRecolhaVisao( new javax.swing.JFrame(), true, BDConexao.getInstancia()
                );
                dialog.addWindowListener( new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing( java.awt.event.WindowEvent e )
                    {
                        System.exit( 0 );
                    }
                } );
                dialog.setVisible( true );
            }
        } );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton ck_A4;
    private javax.swing.JRadioButton ck_simplificada;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbFactura;
    private static javax.swing.JTextField txtFactura;
    // End of variables declaration//GEN-END:variables

    private static void procedimentoReimprimirTicket()
    {
        String ref_doc = txtFactura.getText();
        TbVenda venda = vendaDao.findByCodFactReemprensaoGeral( ref_doc );
        List<TbItemVenda> listaItem = itemVendasController.listarTodosByCodigoVenda( venda.getCodigo() );
//        List<TbItemVenda> listaItem = itemVendasController.listarTodosByCodigoVenda( lastVenda.getCodigo() );
//        String impressora = "";
        String file = "ticket_recolha_unico.jasper";
        HashMap hashMap = new HashMap();

        hashMap.put( "CodVenda", venda.getCodigo() );
        int totalPecas = listaItem.size();
        hashMap.put( "TotalPecas", totalPecas );

        AnyReport anyReport = new AnyReport( hashMap, file );

//        for ( int i = 0; i < totalPecas; i++ )
//        {
//            TbItemVenda item = listaItem.get( i );
//            HashMap hashMap = new HashMap();
////            hashMap.put( "CodItem", item.getCodigo() );
//            hashMap.put( "CodItem", item.getCodigo() );
//            hashMap.put( "TotalPecas", totalPecas );
////            AnyReport anyReport = new AnyReport( hashMap, file );
//            AnyReport anyReport = new AnyReport( hashMap, file );
//        }
    }

    private void procedimento_reimprimir()
    {
        HashMap hashMap = new HashMap();
        String ref_doc = txtFactura.getText();
//                TbVenda lastVenda = vendasController.getLastVenda();
        TbVenda venda = vendaDao.findByCodFactReemprensaoGeral( ref_doc );
        List<TbItemVenda> listaItem = itemVendasController.listarTodosByCodigoVenda( venda.getCodigo() );
//        Notas notas = notasDao.findByCodFactReemprensao( ref_doc );
        System.out.println( "CODIGO VENDA: " + venda );
        if ( venda != null )
        {
            Abreviacao abreviacao = DVML.getAbreviacao( venda.getFkDocumento().getPkDocumento() );
//            Abreviacao abreviacao_nota = DVML.getAbreviacao(notas.getFkDocumento().getPkDocumento() );

            abreviacao = ck_simplificada.isSelected() ? DVML.Abreviacao.FR_S_A6 : abreviacao;
//            abreviacao = rbR.isSelected() ? DVML.Abreviacao.RC : abreviacao;
//            abreviacao = jRadioNota.isSelected() ? DVML.Abreviacao.NC : abreviacao;
//            abreviacao_nota = rbNC.isSelected() ? DVML.Abreviacao.NC : abreviacao_nota;
//            abreviacao = rbN.isSelected() ? DVML.Abreviacao.:abreviacao;
            List<TbProduto> lista_produto_isentos = new ArrayList<>();
            lista_produto_isentos = MetodosUtil.getProdutosIsentos( venda.getTbItemVendaList() );
//            lista_produto_isentos = MetodosUtil.getProdutosIsentosNotas( notas.getNotasItemList() );
            String motivos_isentos = MetodosUtil.getMotivoIsensaoProdutos( lista_produto_isentos );
//            ListaVendaRecolhas listaVendaCliente = new ListaVendaRecolhas( venda.getCodigo(), abreviacao, false, true, "Duplicado" );
            ListaVendaRecolhasReimpressao listaVenda1 = new ListaVendaRecolhasReimpressao( venda.getCodigo(), abreviacao, false, true, SEGUNDA_VIA_CONFORMIDADE_COM_ORIGINAL );

//            AnyReport anyReport = new AnyReport( hashMap, venda.getCodigo(), "ticket_recolha.jasper");
//            ListaVendaPorMesas listaVenda1 = new ListaVendaPorM.esas( venda.getCodigo(), abreviacao, false, true, "Original" );
//            ListaVenda2 listaVenda1 = new ListaVenda2( venda.getCodigo(), abreviacao, false, false, SEGUNDA_VIA_CONFORMIDADE_COM_ORIGINAL, motivos_isentos );
//            ListaNotaDebito listaVenda2 = new ListaNotaDebito( notas.getPkNota(), abreviacao_nota, false, true, hashMap, "" );
//            ListaNotaDebito listaNotaDebito = new ListaNotaDebito( notasDao.getLastNota(), Abreviacao.NC, false, false, hashMap, motivos_isentos );
        }
        else
        {
            JOptionPane.showMessageDialog( null, "O Documento não existente na base de dados. \nObs:Verifique a referência. " );
        }

    }

    private void setFolhaImpressora( String folha )
    {
        if ( folha.equalsIgnoreCase( "A6" ) )
        {
            ck_simplificada.setSelected( true );
            ck_A4.setSelected( false );
            this.abreviacao = Abreviacao.FR_S_A6;
        }

        else
        {
            ck_A4.setSelected( true );
            ck_simplificada.setSelected( false );
            this.abreviacao = Abreviacao.FR_A4;
        }
    }

}
