/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import comercial.controller.ProdutosController;
import comercial.controller.ReferenciasController;
import entity.Referencias;
import entity.TbProduto;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import util.BDConexao;
import util.DVML;

/**
 *
 * @author Domingos Dala Vunge
 */
public class ReferenciasVisao extends javax.swing.JDialog
{

    private int idUser;
    private BDConexao conexao;
    private static ProdutosController produtosController;
    private static ReferenciasController referenciasController;
    private static int codProduto;
    private int codArmazem;
    private Map<Integer, String> produtosMap = new HashMap<>();

    public ReferenciasVisao( int idUser, int codProduto, int codArmazem, BDConexao conexao )
    {
        initComponents();
        setLocationRelativeTo( null );
        this.conexao = conexao;
        this.idUser = idUser;
        this.codProduto = codProduto;
        this.codArmazem = codArmazem;
        produtosController = new ProdutosController( conexao );
        referenciasController = new ReferenciasController( conexao );

        setWindowsListener();
        try
        {
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }
//        carregarProdutos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lbProduto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        txtProduto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodBarra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txAreaObs = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbProduto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbProduto.setForeground(new java.awt.Color(255, 255, 255));
        lbProduto.setText("XXX");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("REFERÊNCIAS PRODUTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "cod", "Designação Produto", "Código Barra", "OBS"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0)
        {
            table.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proucura.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Produto: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Codigo de Barra:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Observação:");

        txAreaObs.setColumns(20);
        txAreaObs.setRows(5);
        jScrollPane2.setViewportView(txAreaObs);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Button-Add-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProduto)
                            .addComponent(txtCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOUT - VERMELHO/Logout 32x32.png"))); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        new BuscaProdutoVisao(
                (java.awt.Frame) SwingUtilities.getWindowAncestor( this ),
                true,
                codArmazem,
                DVML.JANELA_REFERENCIAS,
                BDConexao.getInstancia()
        ).setVisible( true );

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        try
        {
            salvarReferencia();
        }
        catch ( Exception e )
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( ReferenciasVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//            java.util.logging.Logger.getLogger( AssociacaoServicoVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( ReferenciasVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( ReferenciasVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( ReferenciasVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            @Override
            public void run()
            {
                new ReferenciasVisao( 15, 1, 1, BDConexao.getInstancia() ).setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbProduto;
    private static javax.swing.JTable table;
    private javax.swing.JTextArea txAreaObs;
    private javax.swing.JTextField txtCodBarra;
    private static javax.swing.JTextField txtCodigo;
    private static javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables

    public void actualizar_tabela()
    {

    }

    private void setWindowsListener()
    {

        this.addWindowListener( new WindowAdapter()
        {
            @Override
            public void windowActivated( WindowEvent e )
            {
            }

        } );

    }

    private void salvarReferencia()
    {
        try
        {
            // 1️⃣ Pega valores dos campos
            String codBarra = txtCodBarra.getText().trim();
            String codigoStr = txtCodigo.getText().trim(); // Campo que contém o código do produto
            String obs = txAreaObs.getText().trim();

            if ( codBarra.isEmpty() )
            {
                JOptionPane.showMessageDialog( this, "Informe o código de barras", "Atenção", JOptionPane.WARNING_MESSAGE );
                txtCodBarra.requestFocus();
                return;
            }

            if ( codigoStr.isEmpty() )
            {
                JOptionPane.showMessageDialog( this, "Produto não selecionado", "Atenção", JOptionPane.WARNING_MESSAGE );
                txtCodigo.requestFocus();
                return;
            }

            // 2️⃣ Converte código para int
            int codigoProduto;
            try
            {
                codigoProduto = Integer.parseInt( codigoStr );
            }
            catch ( NumberFormatException e )
            {
                JOptionPane.showMessageDialog( this, "Código do produto inválido", "Erro", JOptionPane.ERROR_MESSAGE );
                txtCodigo.requestFocus();
                return;
            }

            // 3️⃣ Busca produto pelo código
            TbProduto p = produtosController.buscarPorCodigo( codigoProduto );
            if ( p == null )
            {
                JOptionPane.showMessageDialog( this, "Produto não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE );
                txtCodigo.requestFocus();
                return;
            }

            // 4️⃣ Monta entity Referencias
            Referencias ref = new Referencias();
            ref.setProdutoId( p.getCodigo() );            // Salva o ID do produto
            ref.setCodBarra( codBarra );
            ref.setObs( obs.isEmpty() ? null : obs );
            ref.setDataReferencia( new Date() );
            ref.setUsuarioId( 15 );         // Usuário logado

            // 5️⃣ Salva no banco via controller/DAO
            boolean sucesso = referenciasController.salvar( ref );

            if ( sucesso )
            {
                // 6️⃣ Atualiza JTable
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.addRow( new Object[]
                {
                    codigoProduto, // ✅ Primeira coluna = código do produto
                    p.getDesignacao(), // Segunda coluna = designação
                    codBarra, // Terceira coluna = cod_barra
                    obs                // Quarta coluna = obs
                } );

                // Foca na nova linha
                int ultimaLinha = model.getRowCount() - 1;
                table.setRowSelectionInterval( ultimaLinha, ultimaLinha );
                table.scrollRectToVisible( table.getCellRect( ultimaLinha, 0, true ) );

                // 7️⃣ Feedback e limpar campos
                JOptionPane.showMessageDialog( this, "Referência salva com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE );
                limparCampos();

            }
            else
            {
                JOptionPane.showMessageDialog( this, "Erro ao salvar referência!", "Erro", JOptionPane.ERROR_MESSAGE );
            }

        }
        catch ( Exception e )
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog( this, "Erro inesperado ao salvar referência", "Erro", JOptionPane.ERROR_MESSAGE );
        }
    }

//private void salvarReferencia() {
//    try {
//        // 1️⃣ Validação dos campos
//        String codBarra = txtCodBarra.getText().trim();
//        String produtoCodigoStr = txtProduto.getText().trim();
//        String obs = txAreaObs.getText().trim();
//
//        if (codBarra.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Informe o código de barras", "Atenção", JOptionPane.WARNING_MESSAGE);
//            txtCodBarra.requestFocus();
//            return;
//        }
//
//        if (produtoCodigoStr.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Produto não selecionado", "Atenção", JOptionPane.WARNING_MESSAGE);
//            txtProduto.requestFocus();
//            return;
//        }
//
//        // 2️⃣ Converte ID do produto
//        int produtoId;
//        try {
//            produtoId = Integer.parseInt(produtoCodigoStr);
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "ID do produto inválido", "Erro", JOptionPane.ERROR_MESSAGE);
//            txtProduto.requestFocus();
//            return;
//        }
//
//        // 3️⃣ Monta entity
//        Referencias ref = new Referencias();
//        ref.setProdutoId(produtoId);
//        ref.setCodBarra(codBarra);
//        ref.setObs(obs.isEmpty() ? null : obs);       // null se vazio
//        ref.setDataReferencia(new Date());
//        ref.setUsuarioId(15);              // pega ID do usuário logado
//
//        // 4️⃣ Salva no banco via controller/DAO
//        boolean sucesso = referenciasController.salvar(ref);
//
//        if (sucesso) {
//            // 5️⃣ Pega a designação do produto do Map
//            String produtoNome = produtosMap.getOrDefault(produtoId, "Produto não encontrado");
//
//            // 6️⃣ Atualiza JTable e foca na nova linha
//            DefaultTableModel model = (DefaultTableModel) table.getModel();
//            model.addRow(new Object[]{produtoId, produtoNome, codBarra, obs});
//
//            int ultimaLinha = model.getRowCount() - 1;
//            table.setRowSelectionInterval(ultimaLinha, ultimaLinha);
//            table.scrollRectToVisible(table.getCellRect(ultimaLinha, 0, true));
//
//            // 7️⃣ Feedback ao usuário
//            JOptionPane.showMessageDialog(this, "Referência salva com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
//
//            // 8️⃣ Limpa campos para nova entrada
////            limparCampos();
//
//        } else {
//            JOptionPane.showMessageDialog(this, "Erro ao salvar referência!", "Erro", JOptionPane.ERROR_MESSAGE);
//        }
//
//    } catch (Exception e) {
//        e.printStackTrace();
//        JOptionPane.showMessageDialog(this, "Erro inesperado ao salvar referência", "Erro", JOptionPane.ERROR_MESSAGE);
//    }
//}
    private void carregarProdutos()
    {
        try
        {
            List<TbProduto> listaProdutos = produtosController.listarTodos(); // pega todos os produtos
            produtosMap.clear(); // limpa antes de carregar
            for ( TbProduto p : listaProdutos )
            {
                produtosMap.put( p.getCodigo(), p.getDesignacao() );
            }
        }
        catch ( Exception e )
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog( this, "Erro ao carregar produtos", "Erro", JOptionPane.ERROR_MESSAGE );
        }
    }

    public static void adicionar_dados( int codigo )
    {

        TbProduto produto_local = (TbProduto) produtosController.findById( codigo );

        if ( !Objects.isNull( produto_local ) )
        {

            txtCodigo.setText( String.valueOf( produto_local.getCodigo() ) );
            txtProduto.setText( produto_local.getDesignacao() );

        }
        else
        {
            JOptionPane.showMessageDialog( null, "O Produto não existe. ", DVML.DVML_COMERCIAL, JOptionPane.INFORMATION_MESSAGE );

        }

    }

    private void limparCampos()
    {
        txtCodBarra.setText( "" );
        txtProduto.setText( "" );
        txAreaObs.setText( "" );
        txtCodBarra.requestFocus();
    }







}
