/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controller.ProdutoController;
import controller.StockController;
import controller.TipoProdutoController;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelo.ProdutoModelo;
import modelo.StockModelo;
import modelo.TipoProdutoModelo;
import util.BDConexao;




/**
 *
 * @author Domingos Dala Vunge
 */
public class StockVisao extends javax.swing.JDialog {

    /**
     * Creates new form StockVisao
     */
    
    
   
    private BDConexao conexao;
    private StockModelo stockModelo;
    private StockController stockController;
    private int codigo =0;
    private Frame parent;
    public StockVisao(java.awt.Frame parent, boolean modal) throws SQLException {
        //this.parent =  parent1;
        
        super(parent, modal);
        
        this.parent = parent;
        
     
        initComponents();
        confiLabel();
        
        setLocationRelativeTo(null);
        
       
        conexao = new BDConexao();
        stockController = new StockController(conexao);
        
        jcDataEntrada.setDate( new Date() );
        
        cmbtipoProduto.setModel( new DefaultComboBoxModel( conexao.getElementos("tb_tipo_produto", "designacao", false)   ) );
       
        cmbArmazem.setModel( new DefaultComboBoxModel( conexao.getElementos("tb_armazem", "designacao", false)   ) );
        
      //  cmbArmazem.setSelectedItem("RETALHO");
        
        cmbProduto.setModel( new DefaultComboBoxModel( conexao.getElementos2("tb_produto", "designacao", "cod_Tipo_Produto", getCodigoTipoProduto())   ) );
         
       //txtNome.addKeyListener( new TratarEventoTeclado() );

       txtIniciaisProdutos.addKeyListener( new TratarEventoProduto());
      
       
       //txtPrecoVenda.addKeyListener( new TratarEventoLucroProduto());
  
//         jSPrecoVenda.addPropertyChangeListener("nextValue",  
//                    new java.beans.PropertyChangeListener() {  
//                        public void propertyChange(java.beans.PropertyChangeEvent e) {  
//                            System.out.println("propertyChange(nextValue)"); // TODO Auto-generated property Event stub "nextValue"   
//                        }  
//                    });  
//        
        //TratarEventoValorVenda
        
        //txtPrecoCompra.addKeyListener(new TratarEventoValorVenda());
        
        
        //txtPrecoVenda.setText( String.valueOf( getValor(   getValorPercentagem() ) ) );
        
        
    }
    
    
    
    
    private void configurar_combos_tipo_produto_produto()
    {
            
           
            try {
                 cmbtipoProduto.setModel( new DefaultComboBoxModel( conexao.getElementos("tb_tipo_produto", "designacao", false)   ) );
                 cmbProduto.setModel( new DefaultComboBoxModel( conexao.getElementos2("tb_produto", "designacao", "cod_Tipo_Produto", getCodigoTipoProduto())   ) );
            } catch (Exception e) {
            }
           
    
    }
    
    
    public void confiLabel()
    {
        
        lbInicaisNome.setHorizontalAlignment(JLabel.RIGHT);
        lbInicaisNome.setHorizontalAlignment(JLabel.RIGHT);
    
        lbProduto.setHorizontalAlignment(JLabel.RIGHT);
        lbDataEntrada.setHorizontalAlignment(JLabel.RIGHT);
        lbStatus.setHorizontalAlignment(JLabel.RIGHT);
        lbStatus.setHorizontalAlignment(JLabel.RIGHT);
        lbQuantidade.setHorizontalAlignment(JLabel.RIGHT);
        lbProdutos.setHorizontalAlignment(JLabel.RIGHT);
        lbPrecoVenda.setHorizontalAlignment(JLabel.RIGHT);
        lbPrecoVendaFabrica.setHorizontalAlignment(JLabel.RIGHT);
        lbPrecoCompra.setHorizontalAlignment(JLabel.RIGHT);
        lbQuantidade.setHorizontalAlignment(JLabel.RIGHT);
        lbQuantidadeBaixa.setHorizontalAlignment(JLabel.RIGHT);
        lbQuantidadeCritica.setHorizontalAlignment(JLabel.RIGHT);
      
        lbStatus.setHorizontalAlignment(JLabel.RIGHT);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cmbProdutos = new javax.swing.JComboBox();
        lbProdutos = new javax.swing.JLabel();
        lbInicaisNome = new javax.swing.JLabel();
        txtIniciaisProdutos = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lbCategoria = new javax.swing.JLabel();
        cmbtipoProduto = new javax.swing.JComboBox();
        lbProduto = new javax.swing.JLabel();
        lbDataEntrada = new javax.swing.JLabel();
        cmbProduto = new javax.swing.JComboBox();
        jcDataEntrada = new com.toedter.calendar.JDateChooser();
        lbCategoria1 = new javax.swing.JLabel();
        cmbArmazem = new javax.swing.JComboBox();
        lbCategoria2 = new javax.swing.JLabel();
        txtCodigoBarra = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox();
        lbQuantidade = new javax.swing.JLabel();
        lbPrecoCompra = new javax.swing.JLabel();
        txtPrecoCompra = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        lbPrecoVenda = new javax.swing.JLabel();
        txtPrecoVenda = new javax.swing.JTextField();
        lbQuantidadeCritica = new javax.swing.JLabel();
        txtQuantidadeCritica = new javax.swing.JTextField();
        lbQuantidadeBaixa = new javax.swing.JLabel();
        txtQuantidadeBaixa = new javax.swing.JTextField();
        lbPrecoVendaFabrica = new javax.swing.JLabel();
        txtPrecoVendaFabrica = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("...::::: DVML-STOCK ::::...");
        setIconImage(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button  Salvar-.png"))); // NOI18N
        btnSalvar.setAlignmentX(0.5F);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button-Alterar.png"))); // NOI18N
        btnAlterar.setAlignmentX(0.5F);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button-Eliminar.png"))); // NOI18N
        btnEliminar.setAlignmentX(0.5F);
        btnEliminar.setEnabled(false);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button-Cancelar.png"))); // NOI18N
        btnCancelar.setAlignmentX(0.5F);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STOCK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(51, 153, 0)));
        jPanel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N

        jTabbedPane1.setForeground(new java.awt.Color(51, 153, 0));
        jTabbedPane1.setFont(new java.awt.Font("Showcard Gothic", 0, 13)); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCA DO PRODUTO NO STOCK"));

        cmbProdutos.setBackground(new java.awt.Color(51, 153, 0));
        cmbProdutos.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cmbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdutosActionPerformed(evt);
            }
        });

        lbProdutos.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbProdutos.setText("Produtos Existentes no Stock:");

        lbInicaisNome.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbInicaisNome.setText("Inicias Produtos:");

        txtIniciaisProdutos.setBackground(new java.awt.Color(51, 153, 0));
        txtIniciaisProdutos.setForeground(new java.awt.Color(255, 255, 255));
        txtIniciaisProdutos.setCaretColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lbProdutos)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIniciaisProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(cmbProdutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbInicaisNome, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInicaisNome)
                    .addComponent(txtIniciaisProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProdutos))
                .addGap(22, 22, 22))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("PRODUTO A ENTRAR NO STOCK"));

        lbCategoria.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbCategoria.setText("Tipo Produto:");

        cmbtipoProduto.setBackground(new java.awt.Color(51, 153, 0));
        cmbtipoProduto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cmbtipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipoProdutoActionPerformed(evt);
            }
        });

        lbProduto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbProduto.setText("Produto:");

        lbDataEntrada.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbDataEntrada.setText("Data Entrada:");

        cmbProduto.setBackground(new java.awt.Color(51, 153, 0));
        cmbProduto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cmbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdutoActionPerformed(evt);
            }
        });

        lbCategoria1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbCategoria1.setText("Armazém:");

        cmbArmazem.setBackground(new java.awt.Color(51, 153, 0));
        cmbArmazem.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cmbArmazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbArmazemActionPerformed(evt);
            }
        });

        lbCategoria2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbCategoria2.setText("Cód. Barra:");

        txtCodigoBarra.setBackground(new java.awt.Color(51, 153, 0));
        txtCodigoBarra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCodigoBarra.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoBarra.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCodigoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbArmazem, 0, 188, Short.MAX_VALUE)
                    .addComponent(cmbtipoProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcDataEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(txtCodigoBarra))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategoria1)
                    .addComponent(cmbArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategoria2)
                    .addComponent(txtCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategoria)
                    .addComponent(cmbtipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("DADOS", jPanel4);

        lbStatus.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbStatus.setText("Status:");

        cmbStatus.setBackground(new java.awt.Color(51, 153, 0));
        cmbStatus.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Desactivo" }));

        lbQuantidade.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbQuantidade.setText("Quantidade:");

        lbPrecoCompra.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbPrecoCompra.setText("Preco da Compra:");

        txtPrecoCompra.setEditable(false);
        txtPrecoCompra.setBackground(new java.awt.Color(51, 153, 0));
        txtPrecoCompra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrecoCompra.setForeground(new java.awt.Color(255, 255, 255));

        txtQuantidade.setEditable(false);
        txtQuantidade.setBackground(new java.awt.Color(51, 153, 0));
        txtQuantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        txtQuantidade.setText("0");
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        lbPrecoVenda.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbPrecoVenda.setText("Preco de Venda:");

        txtPrecoVenda.setBackground(new java.awt.Color(51, 153, 0));
        txtPrecoVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrecoVenda.setForeground(new java.awt.Color(255, 255, 255));

        lbQuantidadeCritica.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbQuantidadeCritica.setText("Qt.Critica:");

        txtQuantidadeCritica.setBackground(new java.awt.Color(51, 153, 0));
        txtQuantidadeCritica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuantidadeCritica.setForeground(new java.awt.Color(255, 255, 255));

        lbQuantidadeBaixa.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbQuantidadeBaixa.setText("Qt.Baixa:");

        txtQuantidadeBaixa.setBackground(new java.awt.Color(51, 153, 0));
        txtQuantidadeBaixa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuantidadeBaixa.setForeground(new java.awt.Color(255, 255, 255));

        lbPrecoVendaFabrica.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbPrecoVendaFabrica.setText("Preco de Venda (Fábrica)");

        txtPrecoVendaFabrica.setBackground(new java.awt.Color(51, 153, 0));
        txtPrecoVendaFabrica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrecoVendaFabrica.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbPrecoVendaFabrica, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecoVendaFabrica, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbQuantidadeCritica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantidadeCritica, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbPrecoCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(lbQuantidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 2, Short.MAX_VALUE)
                                        .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbQuantidadeBaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantidadeBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoCompra)
                    .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbQuantidadeCritica)
                    .addComponent(txtQuantidadeCritica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantidadeBaixa)
                    .addComponent(txtQuantidadeBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoVenda)
                    .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoVendaFabrica)
                    .addComponent(txtPrecoVendaFabrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/imagens/1323444801_currency_dollar red.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        try {
            // TODO add your handling code here:

            operacao(1,"SALVOS", "SALVAR");
            
        } catch (SQLException ex) {
            Logger.getLogger(StockVisao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            // TODO add your handling code here:

            codigo =   conexao.getCodigoStockByCodArmazem( getCodigoProduto() ,  getCodigoArmazem() );
            
            operacao(2,"ALTERADO", "ALTERAR");
        } catch (SQLException ex) {
            Logger.getLogger(StockVisao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbtipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipoProdutoActionPerformed
        
        try {
            // TODO add your handling code here:
             cmbProduto.setModel( new DefaultComboBoxModel( conexao.getElementos2("tb_produto", "designacao", "cod_Tipo_Produto", getCodigoTipoProduto())   ) );
             
             setPrecoCompraProduto();
             
        } catch (SQLException ex) {
            Logger.getLogger(StockVisao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_cmbtipoProdutoActionPerformed

    private void cmbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdutoActionPerformed
        try {
            setPrecoCompraProduto();
        } catch (SQLException ex) {
            Logger.getLogger(StockVisao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmbProdutoActionPerformed

    
    
    
    public void setPrecoCompraProduto() throws SQLException{
    
        txtPrecoCompra.setText( String.valueOf(  new ProdutoController(conexao).getProduto(getCodigoProduto()).getPreco()  ) );
  
    
    }
    
    
    
    private void cmbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdutosActionPerformed
        // TODO add your handling code here:
        
 try {
                    limpar_stock();
                    ver_dados_stock(  getProduto() );
                    setPrecoCompraProduto();
          
                    
                } catch (SQLException ex) {
                    Logger.getLogger(StockVisao.class.getName()).log(Level.SEVERE, null, ex);
                    
                }finally{
                
                        
                            
                
                }
//        
        
    }//GEN-LAST:event_cmbProdutosActionPerformed

    private void cmbArmazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbArmazemActionPerformed
        // TODO add your handling code here:
        
        
        try {
                    limpar_stock();
                    
                    ver_dados_stock(  getProduto() );
                    setPrecoCompraProduto();
          
                    
                } catch (SQLException ex) {
                    Logger.getLogger(StockVisao.class.getName()).log(Level.SEVERE, null, ex);
                    
                }finally{
                
                        
                            
                
                }
//        
        
        
    }//GEN-LAST:event_cmbArmazemActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtCodigoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarraActionPerformed
        // TODO add your handling code here:
         try {
             
              Long codigo_barra =    Long.parseLong( txtCodigoBarra.getText() );
              ProdutoModelo produtoModelo = new ProdutoController(conexao).getProdutoByCodigoBarra( codigo_barra );             
              cmbtipoProduto.setModel( new DefaultComboBoxModel( conexao.getElementos("tb_tipo_produto", "designacao", false)   ) );
              
              TipoProdutoController tipoProdutoController = new TipoProdutoController(conexao);
              TipoProdutoModelo tipoProdutoModelo   =      tipoProdutoController.getTipoProdutoModelo( produtoModelo.getCod_Tipo_Produto() );
              cmbtipoProduto.setSelectedItem(  tipoProdutoModelo.getDesignacao()  );              
              cmbProduto.setModel( new DefaultComboBoxModel( conexao.getElementos2("tb_produto", "designacao", "cod_Tipo_Produto", produtoModelo.getCod_Tipo_Produto() ) ) );              
              cmbProduto.setSelectedItem(  produtoModelo.getDesignacao() );
              
              setPrecoCompraProduto();
              
        } catch (SQLException ex) {
            //Logger.getLogger(StockVisao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_txtCodigoBarraActionPerformed

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    StockVisao dialog = new StockVisao(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(StockVisao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    
    /* CRIACAO DO GETS  */
    public int getQuantidade()
    {
        return  Integer.parseInt(txtQuantidade.getText());
    }
    
     /* CRIACAO DO GETS  */
    public int getQuantidadeAntiga()
    {
        return  Integer.parseInt(txtQuantidade.getText());
    }
    
    
  
     public int getCodigoSyockByCodProduto() throws SQLException
    {
           return conexao.getCodigoByCodigoPublico("tb_stock","codigo","cod_produto_codigo",  getCodigoProduto());   
    }
    
    

     
      
    public int getProduto() throws SQLException
    {
           return conexao.getCodigoPublico("tb_produto", String.valueOf(  cmbProdutos.getSelectedItem()));   
    }
    
     public int getCodigoArmazem() throws SQLException
    {
           return conexao.getCodigoPublico("tb_armazem", String.valueOf(  cmbArmazem.getSelectedItem() ) );   
    }
    
    
    
    public int getCodigoProduto() throws SQLException
    {
           return conexao.getCodigoPublico("tb_produto", String.valueOf(  cmbProduto.getSelectedItem()));   
    }
    
    public String getStatus()
    {
        return String.valueOf(cmbStatus.getSelectedItem());
    }
    
    
    
    public int getCodigoTipoProduto() throws SQLException
    {
           return conexao.getCodigoPublico("tb_tipo_produto", String.valueOf(  cmbtipoProduto.getSelectedItem()));   
    }
    
    
    public String getDataEntrada()
    {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(jcDataEntrada.getDate());
        
        String dataSelecionada = gc.get(GregorianCalendar.YEAR) + "-" +
                        (gc.get(GregorianCalendar.MONTH) + 1) + "-" +
                        gc.get(GregorianCalendar.DATE);
        return dataSelecionada;
    }
    
    
    public float getPrecoVenda()
    {
            return Float.parseFloat(  String.valueOf( txtPrecoVenda.getText()) );
    
    }
   
     public float getPrecoVendaFabrica()
    {
            return Float.parseFloat(  String.valueOf( txtPrecoVendaFabrica.getText()) );
    
    }
   
    public float getValor(int percentagen){
            return getPrecoCompra() * (percentagen / 100) + getPrecoCompra() ;
    }
    
    public float getPrecoCompra(){
            return Float.parseFloat(  String.valueOf( txtPrecoCompra.getText()) );
    }
    
    
    public String getProduto(int codigo)
    {
            return conexao.getDescrisoByCodigoPublico("tb_produto", "designacao", codigo);
    
    }
    
    public int getQuantidadeCritica(){
                return    Integer.parseInt( txtQuantidadeCritica.getText() ); 
    }
    
    public int getQuantidadeBaixa(){
                return    Integer.parseInt( txtQuantidadeBaixa.getText() ); 
    }
    
    
    
     public void limpar()
     {
                    
          
          cmbProduto.setSelectedIndex(0);
          cmbStatus.setSelectedItem("Activo");
     
     }
     
     
    public boolean campos_invalidos()
    {     
        Color backGround = Color.WHITE;
        Color foreGround = Color.BLACK;
        Color caretColor = Color.BLACK;
            
        if (txtQuantidade.getText().equals(""))
        {
            txtQuantidade.setBackground(backGround);
            txtQuantidade.setForeground(foreGround);
            txtQuantidade.setCaretColor(caretColor);
            JOptionPane.showMessageDialog(null, "Pf. Insira a quantidade: ");
            return true;
        }
        
        
        return false;
    }

    
    public void operacao(int operacao , String descricaoCerto, String descricaoErro) throws SQLException
    {
         stockModelo = new StockModelo(codigo, getCodigoProduto(),  getCodigoArmazem(),  getDataEntrada(), getQuantidade(), getQuantidadeAntiga(), getStatus(), getPrecoVenda() , getQuantidadeCritica() , getQuantidadeBaixa(), getPrecoVendaFabrica());
        
         if(!campos_invalidos())  
         {
             if(operacao == 1)
             {
//                 if(!exist_produto())
//                 {
                     
                     if(!exist_produto_armazem() )
                     {
                           if(stockController.operacao(operacao, stockModelo))
                           {

                                JOptionPane.showMessageDialog(null, "DADOS   " + descricaoCerto + " COM SUCESSO NA BD!...");
                                limpar();
                                limpar_stock();
                                
                           }
                          else JOptionPane.showMessageDialog(null, "ERRO AO " + descricaoErro + "NA BD!...", "ERRO", JOptionPane.ERROR_MESSAGE);   
                           
                     }else JOptionPane.showMessageDialog(null, "ERRO ESTE PRODUTO JA SE ENCONTRA NESTE ARMAZEM","ERRO" , JOptionPane.ERROR_MESSAGE );   
                     
              //  }else JOptionPane.showMessageDialog(null, "IMPOSSIVEL ADICIONAR: O PRODUTO JA SE ENCONTRA NO STOCK!...", "ERRO", JOptionPane.ERROR_MESSAGE);      
                 
             }else{
             
                       if(stockController.operacao(operacao, stockModelo))
                       {
                            JOptionPane.showMessageDialog(null, "DADOS   " + descricaoCerto + " COM SUCESSO NA BD!...");
                            limpar();
                            limpar_stock();
                       }
                       else JOptionPane.showMessageDialog(null, "ERRO AO " + descricaoErro + "NA BD!...", "ERRO", JOptionPane.ERROR_MESSAGE);   
          
             }
         }
    }
    
 
    
    public boolean exist_produto() throws SQLException{
                    return new StockController(conexao).exist( getCodigoProduto() );
    }
    
    
    public boolean exist_produto_armazem() throws SQLException{
                    return new StockController(conexao).exist_armazem(getCodigoProduto(),  getCodigoArmazem() );
    }

    //CLASSE EVENTO TECLADO 
    
    
 
    
     //----------- evento do teclado ---------------------------------------
    class TratarEventoTeclado implements KeyListener
    {
        String prefixo = "";
        int codigo_produto =0;

        public void keyPressed(KeyEvent evt)
        {

            if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_ENTER)
            {
                char key = evt.getKeyChar();
                prefixo = txtIniciaisProdutos.getText().trim() + key;
                
                cmbProdutos.setModel(new DefaultComboBoxModel(conexao.getElementosLike("tb_produto", "designacao", prefixo) ) );     
                
                codigo_produto = conexao.getCodigoByNamePublico("tb_produto", "designacao", String.valueOf( cmbProdutos.getSelectedItem()));
                
                System.out.println("CODIGO: " +codigo_produto +"Produto: " +String.valueOf( cmbProdutos.getSelectedItem()));
                
                
                
                ProdutoController produtoController = new ProdutoController(conexao);
                
                ProdutoModelo produtoModelo = new ProdutoModelo();
                
                try {
                    produtoModelo=  produtoController.getProduto(codigo_produto);
                    
                    txtPrecoCompra.setText(String.valueOf(produtoModelo.getPreco()));
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(StockVisao.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                
                ver_dados_stock(codigo_produto);
                
            }
        }

        public void keyReleased(KeyEvent evt)
        {}
        public void keyTyped(KeyEvent evt)
        {}
    }

    
    
    
       //----------- evento do teclado do tipo produto ---------------------------------------
    class TratarEventoProduto implements KeyListener
    {
        String prefixo = "";
        int codigo_produto =0;

        public void keyPressed(KeyEvent evt)
        {

            if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_ENTER)
            {
                char key = evt.getKeyChar();
                prefixo = txtIniciaisProdutos.getText().trim() + key;
                
                
                
                System.err.println("CHEGUEI");
                
                cmbProdutos.setModel(new DefaultComboBoxModel(  conexao.getElementosProdutoStockLike(prefixo) )  );     
                try {
                    limpar_stock();
                    ver_dados_stock(  getProduto() );
                    setPrecoCompraProduto();
          
                    
                } catch (SQLException ex) {
                    Logger.getLogger(StockVisao.class.getName()).log(Level.SEVERE, null, ex);
                    
                }finally{
                
                        
                            
                
                }
                
                
                
            }
        }

        public void keyReleased(KeyEvent evt)
        {}
        public void keyTyped(KeyEvent evt)
        {}
    }
    
    
    
        //----------- evento do teclado do tipo produto ---------------------------------------
    class TratarEventoLucroProduto implements KeyListener
    {
        String prefixo = "";
        double lucro, lucroTotal;
        int codigo_produto =0;

        public void keyPressed(KeyEvent evt)
        {

            if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_ENTER)
            {
                char key = evt.getKeyChar();
                
                prefixo = txtPrecoVenda.getText().trim() + key;
              
                lucro = Double.parseDouble(prefixo) - Double.parseDouble(txtPrecoCompra.getText()) ;
                
                lucroTotal = lucro * Double.parseDouble(txtQuantidade.getText());
                
               
           
            }
        }

        public void keyReleased(KeyEvent evt)
        {}
        public void keyTyped(KeyEvent evt)
        {}
    }
    
    
    
     //----------- evento do teclado ---------------------------------------
    class TratarEventoValorVenda implements KeyListener
    {
       
        public void keyPressed(KeyEvent evt)
        {

               
               System.out.println("Cheguei!..");
                

        }

        public void keyReleased(KeyEvent evt)
        {}
        public void keyTyped(KeyEvent evt)
        {}
    }

    
    public void limpar_stock(){
           
            txtQuantidade.setText(  "0" );
            txtQuantidadeCritica.setText( "0" );
            txtQuantidadeBaixa.setText( "0" );
            txtPrecoVenda.setText( "0" );
            txtPrecoVendaFabrica.setText( "0" );
    
    
    }
    
    public void ver_dados_stock(int codigo)
    {
    
     
            try {
           
            StockModelo stockModelo = new StockController(conexao).getStockProduto(codigo, getCodigoArmazem() );
            ProdutoModelo produtoModelo =   new ProdutoController(conexao).getProduto(stockModelo.getCodigo_produto());
            
            
            if(  produtoModelo.getCod_Tipo_Produto() == 0 )
            {
                    configurar_combos_tipo_produto_produto();
            }
            else 
            {
                cmbtipoProduto.setSelectedItem(   new TipoProdutoController(conexao).getTipoProdutoModelo( produtoModelo.getCod_Tipo_Produto()).getDesignacao()  );
                cmbArmazem.setSelectedItem(   conexao.getDescrisaoArmazemByCodigo( stockModelo.getCod_armazem()  )   );
                cmbProduto.setSelectedItem(  produtoModelo.getDesignacao()  );


                 String data = stockModelo.getDataEntrada();


                    try {
                                //Ex.: 2012-06-26
                      int dia = Integer.parseInt(data.substring(8, 10));;
                      int mes = Integer.parseInt(data.substring(5, 7));;
                      int ano = Integer.parseInt(data.substring(0, 4));

                      jcDataEntrada.setDate(new Date(ano - 1900, mes - 1, dia));
                    } catch (Exception e) {
                    }

                setPrecoCompraProduto();
                txtQuantidade.setText(  String.valueOf( stockModelo.getQuantidade_existente() )   );
                txtQuantidadeCritica.setText(  String.valueOf( stockModelo.getQuantidadeCritica())   );
                txtQuantidadeBaixa.setText(  String.valueOf( stockModelo.getQuantidadeBaixa())   );
                txtPrecoVenda.setText( String.valueOf( stockModelo.getPreco_venda()  )   );
                txtPrecoVendaFabrica.setText( String.valueOf( stockModelo.getPreco_venda_fabrica())   );

                cmbStatus.setSelectedItem( stockModelo.getStatus() ) ;

            }
//            
        } catch (SQLException ex) {
            Logger.getLogger(StockVisao.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbArmazem;
    private javax.swing.JComboBox cmbProduto;
    private javax.swing.JComboBox cmbProdutos;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JComboBox cmbtipoProduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jcDataEntrada;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCategoria1;
    private javax.swing.JLabel lbCategoria2;
    private javax.swing.JLabel lbDataEntrada;
    private javax.swing.JLabel lbInicaisNome;
    private javax.swing.JLabel lbPrecoCompra;
    private javax.swing.JLabel lbPrecoVenda;
    private javax.swing.JLabel lbPrecoVendaFabrica;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JLabel lbProdutos;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JLabel lbQuantidadeBaixa;
    private javax.swing.JLabel lbQuantidadeCritica;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTextField txtCodigoBarra;
    private javax.swing.JTextField txtIniciaisProdutos;
    private javax.swing.JTextField txtPrecoCompra;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtPrecoVendaFabrica;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtQuantidadeBaixa;
    private javax.swing.JTextField txtQuantidadeCritica;
    // End of variables declaration//GEN-END:variables
}

