/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import java.sql.Connection;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import util.DVML;
import util.FinanceUtils;
import util.MetodosUtil;
import static visao.FormaPagamentoVisao.tabela_forma_pagamento;

/**
 *
 * @author Domingos Dala Vunge
 */
public class TecladoNumeroPOSVisao extends javax.swing.JDialog
{

    /**
     * Creates new form TecladoNumeroPOSVisao
     */
    private JTable tabela;
    private int linha, coluna;
    private int formulario;

    public TecladoNumeroPOSVisao( java.awt.Frame parent, boolean modal, JTable tabela, int linha, int coluna, int formulario )
    {
        super( parent, modal );
        initComponents();
//        setSize( parent.getWidth()/2, parent.getHeight()/2 );
//        setLocation( ( int ) parent.getX() + ( parent.getWidth() / 3 ), parent.getHeight() / 2 );

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation( dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2 );
        this.linha = linha;
        this.coluna = coluna;
        this.tabela = tabela;
        this.formulario = formulario;
        txtVisor.setText( "" );
        txtVisor.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtVisor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_01 = new javax.swing.JButton();
        btn_02 = new javax.swing.JButton();
        btn_03 = new javax.swing.JButton();
        btn_04 = new javax.swing.JButton();
        btn_05 = new javax.swing.JButton();
        btn_06 = new javax.swing.JButton();
        btn_07 = new javax.swing.JButton();
        btn_08 = new javax.swing.JButton();
        btn_09 = new javax.swing.JButton();
        btn_ponto = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_apagar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        txtVisor.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        txtVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVisor.setText("0");
        jPanel1.add(txtVisor, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 291));
        jPanel2.setLayout(new java.awt.GridLayout(5, 3));

        btn_01.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_01.setText("1");
        btn_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_01ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_01);

        btn_02.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_02.setText("2");
        btn_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_02ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_02);

        btn_03.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_03.setText("3");
        btn_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_03ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_03);

        btn_04.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_04.setText("4");
        btn_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_04ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_04);

        btn_05.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_05.setText("5");
        btn_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_05ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_05);

        btn_06.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_06.setText("6");
        btn_06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_06ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_06);

        btn_07.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_07.setText("7");
        btn_07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_07ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_07);

        btn_08.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_08.setText("8");
        btn_08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_08ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_08);

        btn_09.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_09.setText("9");
        btn_09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_09ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_09);

        btn_ponto.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_ponto.setText(".");
        btn_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pontoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ponto);

        btn_0.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_0);

        btn_apagar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_apagar.setText("Apagar");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_apagar);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2934_32x32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jPanel2.add(jButton2);

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton3.setText("ENTER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_01ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_01ActionPerformed
    {//GEN-HEADEREND:event_btn_01ActionPerformed
        // TODO add your handling code here:
        accao_valor_entregue( btn_01 );
    }//GEN-LAST:event_btn_01ActionPerformed

    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_apagarActionPerformed
    {//GEN-HEADEREND:event_btn_apagarActionPerformed
        // TODO add your handling code here:
        apagar();
    }//GEN-LAST:event_btn_apagarActionPerformed

    private void btn_02ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_02ActionPerformed
    {//GEN-HEADEREND:event_btn_02ActionPerformed
        // TODO add your handling code here:
        accao_valor_entregue( btn_02 );
    }//GEN-LAST:event_btn_02ActionPerformed

    private void btn_03ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_03ActionPerformed
    {//GEN-HEADEREND:event_btn_03ActionPerformed
        // TODO add your handling code here:
        accao_valor_entregue( btn_03 );
    }//GEN-LAST:event_btn_03ActionPerformed

    private void btn_04ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_04ActionPerformed
    {//GEN-HEADEREND:event_btn_04ActionPerformed
        // TODO add your handling code here:
        accao_valor_entregue( btn_04 );
    }//GEN-LAST:event_btn_04ActionPerformed

    private void btn_05ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_05ActionPerformed
    {//GEN-HEADEREND:event_btn_05ActionPerformed
        // TODO add your handling code here:
        accao_valor_entregue( btn_05 );
    }//GEN-LAST:event_btn_05ActionPerformed

    private void btn_06ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_06ActionPerformed
    {//GEN-HEADEREND:event_btn_06ActionPerformed
        // TODO add your handling code here:
        accao_valor_entregue( btn_06 );
    }//GEN-LAST:event_btn_06ActionPerformed

    private void btn_07ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_07ActionPerformed
    {//GEN-HEADEREND:event_btn_07ActionPerformed
        // TODO add your handling code here:
        accao_valor_entregue( btn_07 );
    }//GEN-LAST:event_btn_07ActionPerformed

    private void btn_08ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_08ActionPerformed
    {//GEN-HEADEREND:event_btn_08ActionPerformed
        // TODO add your handling code here:
        accao_valor_entregue( btn_08 );
    }//GEN-LAST:event_btn_08ActionPerformed

    private void btn_09ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_09ActionPerformed
    {//GEN-HEADEREND:event_btn_09ActionPerformed
        // TODO add your handling code here:
        accao_valor_entregue( btn_09 );
    }//GEN-LAST:event_btn_09ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_0ActionPerformed
    {//GEN-HEADEREND:event_btn_0ActionPerformed
        // TODO add your handling code here:

        accao_valor_entregue( btn_0 );

    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_pontoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_pontoActionPerformed
    {//GEN-HEADEREND:event_btn_pontoActionPerformed
        // TODO add your handling code here:

        if ( txtVisor.getText().length() > 0 )
        {
            accao_valor_entregue( btn_ponto );
            btn_ponto.setEnabled( false );
        }
    }//GEN-LAST:event_btn_pontoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
        procedimento_enviar();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( TecladoNumeroPOSVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( TecladoNumeroPOSVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( TecladoNumeroPOSVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( TecladoNumeroPOSVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new TecladoNumeroPOSVisao( new JFrame(), true, null, 0, 0, 0 ).setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_01;
    private javax.swing.JButton btn_02;
    private javax.swing.JButton btn_03;
    private javax.swing.JButton btn_04;
    private javax.swing.JButton btn_05;
    private javax.swing.JButton btn_06;
    private javax.swing.JButton btn_07;
    private javax.swing.JButton btn_08;
    private javax.swing.JButton btn_09;
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_ponto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtVisor;
    // End of variables declaration//GEN-END:variables

    private void accao_valor_entregue( JButton button )
    {
        String text = txtVisor.getText();
        txtVisor.setText( text + button.getText() );
    }

    private void apagar()
    {
        String str = txtVisor.getText();
        if ( str.length() - 1 >= 0 )
        {
            if ( str.substring( str.length() - 1, str.length() ).equals( "." ) )
            {
                btn_ponto.setEnabled( true );
            }
            StringBuilder w = new StringBuilder( str );
            str = String.valueOf( w.deleteCharAt( str.length() - 1 ) );
            txtVisor.setText( str );

        }

    }

    private void procedimento_enviar()
    {
        if ( formulario == DVML.NUMERO_TECLADO_VENDA_POS )
        {
            enviar_pos();
        }
        else if ( formulario == DVML.NUMERO_TECLADO_FORMA_PAGAMENTO )
        {
            enviar_forma_pagamento();
        }
        else if ( formulario == DVML.NUMERO_TECLADO_ABERTURA_CAIXA )
        {
            enviar_abertura_caixa();
        }
        else if ( formulario == DVML.NUMERO_TECLADO_FECHO_CAIXA )
        {
            enviar_fecho_caixa();
        }
    }

    private void enviar_pos()
    {
        if ( !txtVisor.getText().equals( "" ) )
        {
            if ( coluna == 4 )
            {

                double qtd = Double.parseDouble( txtVisor.getText() );
                if ( qtd != 0 )
                {

                    int cod_produto = Integer.parseInt( tabela.getValueAt( linha, 1 ).toString() );
                    if ( VendaPOSVisao.possivel_quantidade( cod_produto, qtd ) )
                    {
                        if ( VendaPOSVisao.estado_critico( cod_produto ) )
                        {
                            JOptionPane.showMessageDialog( null, "O Produto precisa ser actualizado no stock." );
                        }

                        double desconto = Double.parseDouble( tabela.getValueAt( linha, 6 ).toString() );
                        tabela.setValueAt( qtd, linha, coluna );
                        actualizar_total( qtd, desconto );
                        dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog( null, "O produto nao pode ser vendido para esta quantidade." );
                    }

                }
                else
                {
                    JOptionPane.showMessageDialog( null, "A quatidade nao pode ser zero(0)." );
                }

            }
            if ( coluna == 6 )
            {

                double preco_linha = Double.parseDouble( tabela.getValueAt( linha, 3 ).toString() );

                double desconto = Double.parseDouble( txtVisor.getText() );
                if ( desconto > preco_linha )
                {
                    JOptionPane.showMessageDialog( null, "O Desconto nao pode ser superior ao preco unitario." );
                }
                else
                {
                    tabela.setValueAt( desconto, linha, coluna );
                    double qtd = Double.parseDouble( tabela.getValueAt( linha, 4 ).toString() );
                    actualizar_total( qtd, desconto );
                    dispose();
                }

            }
            VendaPOSVisao.setTotalGeral();

        }

    }

//    private void enviar_form_vendas()
//    {
//        if ( !txtVisor.getText().equals( "" ) )
//        {
//            if ( coluna == 4 )
//            {
//
//                double qtd = Double.parseDouble( txtVisor.getText() );
//                if ( qtd != 0 )
//                {
//
//                    int cod_produto = Integer.parseInt( tabela.getValueAt( linha, 1 ).toString() );
//                    if ( GestaoPedidosVisao.possivel_quantidade( cod_produto) )
//                    {
//                        try
//                        {
//
//                            if ( GestaoPedidosVisao.estado_critico(cod_produto) )
//                            {
//                                JOptionPane.showMessageDialog( null, "O Produto precisa ser actualizado no stock." );
//                            }
//
//                        }
//                        catch ( Exception e )
//                        {
//                        }
//
//                        double desconto = Double.parseDouble( tabela.getValueAt( linha, 6 ).toString() );
//                        tabela.setValueAt( qtd, linha, coluna );
//                        actualizar_total( qtd, desconto );
//                        dispose();
//                    }
//                    else
//                    {
//                        JOptionPane.showMessageDialog( null, "O produto nao pode ser vendido para esta quantidade." );
//                    }
//
//                }
//                else
//                {
//                    JOptionPane.showMessageDialog( null, "A quatidade nao pode ser zero(0)." );
//                }
//
//            }
//            if ( coluna == 6 )
//            {
//
//                double preco_linha = Double.parseDouble( tabela.getValueAt( linha, 3 ).toString() );
//
//                double desconto = Double.parseDouble( txtVisor.getText() );
//                if ( desconto > preco_linha )
//                {
//                    JOptionPane.showMessageDialog( null, "O Desconto nao pode ser superior ao preco unitario." );
//                }
//                else
//                {
//                    tabela.setValueAt( desconto, linha, coluna );
//                    double qtd = Double.parseDouble( tabela.getValueAt( linha, 4 ).toString() );
//                    actualizar_total( qtd, desconto );
//                    dispose();
//                }
//
//            }
//            GestaoPedidosVisao.setTotalGeral();
//
//        }
//
//    }
    private void actualizar_total( double qtd, double desconto )
    {

        double total_linha = 0;
        double preco_linha = Double.parseDouble( tabela.getValueAt( linha, 3 ).toString() );
        double taxa = Double.parseDouble( tabela.getValueAt( linha, 5 ).toString() );
        total_linha = FinanceUtils.getValorComIVA( qtd, taxa, preco_linha, desconto );
        tabela.setValueAt( total_linha, linha, 7 );
    }

    private void enviar_forma_pagamento()
    {
        System.out.println( "CHEGUEI AQUI FORMA DE PAGAMENTO" );
        if ( !txtVisor.getText().equals( "" ) )
        {
            if ( coluna == 2 )
            {

                String referencia = txtVisor.getText();

                if ( Objects.nonNull( FormaPagamentoVisao.tabela_forma_pagamento ) )
                {
                    FormaPagamentoVisao.tabela_forma_pagamento.setValueAt( referencia, linha, coluna );
                }
                else //if ( Objects.nonNull( FormaPagamentoLugarVisao.tabela_forma_pagamento ) )
                {
                    FormaPagamentoLugarVisao.tabela_forma_pagamento.setValueAt( referencia, linha, coluna );
                }

                dispose();
            }
            if ( coluna == 3 )
            {
                String valor = txtVisor.getText();

                if ( Objects.nonNull( FormaPagamentoVisao.tabela_forma_pagamento ) )
                {
                    FormaPagamentoVisao.tabela_forma_pagamento.setValueAt( Double.parseDouble( valor ), linha, coluna );
                }
                else //if ( Objects.nonNull( FormaPagamentoLugarVisao.tabela_forma_pagamento ) )
                {
                    FormaPagamentoLugarVisao.tabela_forma_pagamento.setValueAt( Double.parseDouble( valor ), linha, coluna );
                }

//                tabela_forma_pagamento.setValueAt( Double.parseDouble( valor ), linha, coluna );
                dispose();

            }

            if ( Objects.nonNull( FormaPagamentoVisao.tabela_forma_pagamento ) )
            {
                FormaPagamentoVisao.visualizar_troco();
            }
            else // if ( Objects.nonNull( FormaPagamentoLugarVisao.tabela_forma_pagamento ) )
            {
                FormaPagamentoLugarVisao.visualizar_troco();
            }

        }
    }

    private void enviar_fecho_caixa()
    {
        System.out.println( "CHEGUEI AQUI FORMA DE PAGAMENTO" );
        if ( !txtVisor.getText().equals( "" ) )
        {

//            if ( coluna == 3 )
//            {
            String valor = txtVisor.getText();
            CaixaFechoVisao.tabela_fecho_caixa.setValueAt( Double.parseDouble( valor ), linha, coluna );
            dispose();
//            }

        }
    }

    private void enviar_abertura_caixa()
    {
        if ( !txtVisor.getText().equals( "" ) )
        {
            String referencia = txtVisor.getText();
            CaixaAberturaVisao.txtValorInicial.setText( referencia );
            dispose();

        }
    }

}
