/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import static javax.swing.GroupLayout.Alignment.CENTER;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import kitanda.util.CfMethods;

/**
 *
 * @author hp
 */
public class TelaCliente extends javax.swing.JFrame
{

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente( DefaultTableModel modeloRecebido )
    {
        initComponents();

        // --- TRANSPARÊNCIA REAL PARA NIMBUS ---
        jTableCliente.setOpaque( false );
        jScrollPane1.getViewport().setOpaque( false );
        jScrollPane1.setOpaque( false );

        // CANCELA FUNDO QUE O NIMBUS FORÇA
        jTableCliente.putClientProperty( "Nimbus.Overrides", null );
        jTableCliente.putClientProperty( "Nimbus.Overrides.InheritDefaults", false );

        // --- IMPEDE A TABELA DE PINTAR FUNDO POR CIMA DO DEGRADÊ ---
        jTableCliente.setUI( new javax.swing.plaf.basic.BasicTableUI()
        {
            @Override
            public void paint( Graphics g, JComponent c )
            {
                // NÃO PINTA FUNDO NENHUM → permite o degradê do renderer
                super.paint( g, c );
            }
        } );

        // --- USA O MODELO RECEBIDO ---
        jTableCliente.setModel( modeloRecebido );

        // --- AJUSTES DE COLUNAS ---
        ocultarColunas();
        ajustarLarguraColunas();

        // --- RENDERER COM DEGRADÊ EM TODAS AS COLUNAS ---
        aplicarRenderizacaoProfissional();

        // --- ATUALIZA TOTAL AO MODIFICAR LINHAS ---
        modeloRecebido.addTableModelListener( e -> atualizarTotal() );
        atualizarTotal();

        // --- ESTILO GERAL (FONTE, ALTURA, CABEÇALHO) ---
        configurarEstilo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        lblTotalCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCliente);

        lblTotalCliente.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTotalCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalCliente.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addComponent(lblTotalCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( TelaCliente.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( TelaCliente.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( TelaCliente.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( TelaCliente.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater( new Runnable()
//        {
////            public void run()
////            {
////                new TelaCliente().setVisible( true );
////            }
//        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JLabel lblTotalCliente;
    // End of variables declaration//GEN-END:variables

    private void atualizarTotal()
    {
        double total = 0;

        for ( int i = 0; i < jTableCliente.getRowCount(); i++ )
        {
            double subtotal = Double.parseDouble( jTableCliente.getValueAt( i, jTableCliente.getColumnCount() - 1 ).toString() );
            total += subtotal;
        }

        lblTotalCliente.setText( "TOTAL: " + CfMethods.formatarComoMoeda( total ) );
    }

    private void configurarEstilo()
    {
        // Tabela
        jTableCliente.setFont( new Font( "Segoe UI", Font.PLAIN, 20 ) );
        jTableCliente.setRowHeight( 32 );
        jTableCliente.setShowHorizontalLines( false );
        jTableCliente.setShowVerticalLines( false );
        jTableCliente.setIntercellSpacing( new java.awt.Dimension( 0, 0 ) );
        jTableCliente.setForeground( Color.WHITE );
        jTableCliente.setBackground( new Color( 45, 45, 48 ) );

        // Cabeçalho estilo POS moderno
        jTableCliente.getTableHeader().setFont( new Font( "Segoe UI", Font.BOLD, 22 ) );
        jTableCliente.getTableHeader().setOpaque( false );
        jTableCliente.getTableHeader().setBackground( new Color( 30, 144, 255 ) );
        jTableCliente.getTableHeader().setForeground( Color.WHITE );
        jTableCliente.getTableHeader().setReorderingAllowed( false );

        // Painel Total
        lblTotalCliente.setFont( new Font( "Segoe UI", Font.BOLD, 50 ) );
        lblTotalCliente.setForeground( new Color( 0, 255, 128 ) );
        lblTotalCliente.setOpaque( true );
        lblTotalCliente.setBackground( new Color( 20, 20, 20 ) );
        lblTotalCliente.setBorder( BorderFactory.createEmptyBorder( 10, 10, 10, 20 ) );

    }

    private void ocultarColunas()
    {
        int[] colunasParaOcultar =
        {
            0, 1, 3, 6
        };

        for ( int i : colunasParaOcultar )
        {
            try
            {
                jTableCliente.getColumnModel().getColumn( i ).setMinWidth( 0 );
                jTableCliente.getColumnModel().getColumn( i ).setMaxWidth( 0 );
                jTableCliente.getColumnModel().getColumn( i ).setPreferredWidth( 0 );
            }
            catch ( Exception e )
            {
                System.out.println( "Coluna já removida ou não encontrada: " + i );
            }
        }
    }

    private void ajustarLarguraColunas()
    {
        // Coluna Qtd (índice 4)
        jTableCliente.getColumnModel().getColumn( 4 ).setPreferredWidth( 90 );
        jTableCliente.getColumnModel().getColumn( 4 ).setMinWidth( 70 );
        jTableCliente.getColumnModel().getColumn( 4 ).setMaxWidth( 110 );

        // Coluna Taxa (índice 5)
        jTableCliente.getColumnModel().getColumn( 5 ).setPreferredWidth( 100 );
        jTableCliente.getColumnModel().getColumn( 5 ).setMinWidth( 80 );
        jTableCliente.getColumnModel().getColumn( 5 ).setMaxWidth( 130 );

        // Coluna Total (índice 7)
        jTableCliente.getColumnModel().getColumn( 7 ).setPreferredWidth( 130 );
        jTableCliente.getColumnModel().getColumn( 7 ).setMinWidth( 100 );
        jTableCliente.getColumnModel().getColumn( 7 ).setMaxWidth( 160 );
    }

    private void aplicarRenderizacaoProfissional()
    {
        jTableCliente.setDefaultRenderer( Object.class, new DefaultTableCellRenderer()
        {
            private int viewRow;
            private boolean cellSelected;
            private JTable tableRef;

            @Override
            public Component getTableCellRendererComponent(
                    JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column )
            {
                viewRow = row;
                cellSelected = isSelected;
                tableRef = table;

                super.getTableCellRendererComponent( table, value, isSelected, hasFocus, row, column );

                // números
                if ( value instanceof Number )
                {
                    setHorizontalAlignment( RIGHT );

                    double numero = ( ( Number ) value ).doubleValue();
                    if ( column == 4 )
                    {
                        setText( String.format( "%,.3f", numero ) );
                    }
                    else
                    {
                        setText( String.format( "%,.2f", numero ) );
                    }
                }
                else
                {
                    setHorizontalAlignment( LEFT );
                }

                // texto sempre preto
                setForeground( Color.BLACK );

                // FORÇA transparência total
                setOpaque( false );

                return this;
            }

            @Override
            protected void paintComponent( Graphics g )
            {
                Graphics2D g2 = ( Graphics2D ) g;

                int modelRow = tableRef.convertRowIndexToModel( viewRow );

                GradientPaint gp;

                if ( cellSelected )
                {
                    gp = new GradientPaint(
                            0, 0, new Color( 0, 255, 255 ),
                            getWidth(), getHeight(), new Color( 0, 180, 255 )
                    );
                }
                else if ( modelRow % 2 == 0 )
                {
                    gp = new GradientPaint(
                            0, 0, new Color( 0, 255, 255 ),
                            getWidth(), getHeight(), new Color( 0, 120, 255 )
                    );
                }
                else
                {
                    gp = new GradientPaint(
                            0, 0, new Color( 0, 230, 240 ),
                            getWidth(), getHeight(), new Color( 0, 150, 255 )
                    );
                }

                // pinta a linha inteira (TODAS AS COLUNAS)
                g2.setPaint( gp );
                g2.fillRect( 0, 0, getWidth(), getHeight() );

                super.paintComponent( g );
            }
        } );
    }

}
