/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controlador.exceptions.NonexistentEntityException;
import dao.UsuarioDao;
import entity.TbUsuario;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import static kitanda.util.CfMethodsSwing.*;
import util.BDConexao;
import static util.JPAEntityMannagerFactoryUtil.em;
import util.MetodosUtil;

/**
 *
 * @author tagif
 */
public class UsuarioAlterarSenhaVissao extends javax.swing.JFrame
{

    TbUsuario tbUsuario;
    private UsuarioDao usuarioDao;

    public UsuarioAlterarSenhaVissao( TbUsuario tbUsuario )
    {
        this.tbUsuario = tbUsuario;
        usuarioDao = new UsuarioDao( em );
        initComponents();
        usuarioJTextField.setText( tbUsuario.getUserName() );

        setDefaultCloseOperation( DISPOSE_ON_CLOSE );
        setSize( 550, 600 );
        setLocationRelativeTo( null );
        setVisible( true );
        senhaAtualJPasswordField.requestFocus();
        postInitComponents();
    }

    public UsuarioAlterarSenhaVissao()
    {
        initComponents();
        System.err.println( "já." );
        setLocationRelativeTo( null );
        setVisible( true );
        postInitComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        principaljPanel = new javax.swing.JPanel();
        usuarioJLabel = new javax.swing.JLabel();
        senhaAntigaJLabel = new javax.swing.JLabel();
        senhaNovaJLabel = new javax.swing.JLabel();
        senhaNovaRepetirJLabel = new javax.swing.JLabel();
        usuarioJTextField = new javax.swing.JTextField();
        senhaAtualJPasswordField = new javax.swing.JPasswordField();
        senhaNovaJPasswordField = new javax.swing.JPasswordField();
        senhaNovaConfirmarJPasswordField = new javax.swing.JPasswordField();
        cancelarJButton = new javax.swing.JButton();
        concluirJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        head = new javax.swing.JPanel();
        bannerJLabel = new javax.swing.JLabel();
        logoJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 102));
        addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentResized(java.awt.event.ComponentEvent evt)
            {
                formComponentResized(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                formPropertyChange(evt);
            }
        });

        principaljPanel.setBackground(getBackground());

        usuarioJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        usuarioJLabel.setForeground(new java.awt.Color(255, 255, 255));
        usuarioJLabel.setText("Usuário");

        senhaAntigaJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        senhaAntigaJLabel.setForeground(new java.awt.Color(255, 255, 255));
        senhaAntigaJLabel.setText("Senha atual");

        senhaNovaJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        senhaNovaJLabel.setForeground(new java.awt.Color(255, 255, 255));
        senhaNovaJLabel.setText("Nova senha");

        senhaNovaRepetirJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        senhaNovaRepetirJLabel.setForeground(new java.awt.Color(255, 255, 255));
        senhaNovaRepetirJLabel.setText("Confirmar ");

        usuarioJTextField.setEditable(false);
        usuarioJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usuarioJTextField.setForeground(new java.awt.Color(0, 0, 153));

        senhaAtualJPasswordField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        senhaAtualJPasswordField.setForeground(new java.awt.Color(0, 51, 255));
        senhaAtualJPasswordField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                senhaAtualJPasswordFieldActionPerformed(evt);
            }
        });

        senhaNovaJPasswordField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        senhaNovaJPasswordField.setForeground(new java.awt.Color(0, 153, 51));
        senhaNovaJPasswordField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                senhaNovaJPasswordFieldActionPerformed(evt);
            }
        });

        senhaNovaConfirmarJPasswordField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        senhaNovaConfirmarJPasswordField.setForeground(new java.awt.Color(0, 153, 51));

        cancelarJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/img32x32/_cancel.png"))); // NOI18N
        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarJButtonActionPerformed(evt);
            }
        });

        concluirJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmacao.png"))); // NOI18N
        concluirJButton.setText("Concluir");
        concluirJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                concluirJButtonActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGOUT - VERMELHO/Logout 32x32.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout principaljPanelLayout = new javax.swing.GroupLayout(principaljPanel);
        principaljPanel.setLayout(principaljPanelLayout);
        principaljPanelLayout.setHorizontalGroup(
            principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principaljPanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principaljPanelLayout.createSequentialGroup()
                        .addGroup(principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaNovaJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(senhaAntigaJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usuarioJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(senhaNovaRepetirJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(senhaNovaConfirmarJPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                            .addComponent(senhaNovaJPasswordField)
                            .addComponent(usuarioJTextField)
                            .addComponent(senhaAtualJPasswordField))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principaljPanelLayout.createSequentialGroup()
                        .addComponent(cancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(concluirJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        principaljPanelLayout.setVerticalGroup(
            principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principaljPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioJLabel))
                .addGap(24, 24, 24)
                .addGroup(principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaAtualJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaAntigaJLabel))
                .addGap(18, 18, 18)
                .addGroup(principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaNovaJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaNovaJLabel))
                .addGap(16, 16, 16)
                .addGroup(principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaNovaConfirmarJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaNovaRepetirJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(principaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelarJButton)
                        .addComponent(concluirJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        principaljPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelarJButton, concluirJButton});

        getContentPane().add(principaljPanel, java.awt.BorderLayout.CENTER);

        head.setBackground(new java.awt.Color(204, 255, 255));
        head.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        head.setLayout(new java.awt.BorderLayout());

        bannerJLabel.setBackground(head.getBackground());
        bannerJLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Alterar senha", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Serif", 1, 24), new java.awt.Color(0, 0, 102))); // NOI18N
        head.add(bannerJLabel, java.awt.BorderLayout.CENTER);

        logoJLabel.setBackground(head.getBackground());
        logoJLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 1, true), "Kitanda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Serif", 3, 14), new java.awt.Color(0, 153, 51))); // NOI18N
        head.add(logoJLabel, java.awt.BorderLayout.WEST);

        getContentPane().add(head, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_formPropertyChange
    {//GEN-HEADEREND:event_formPropertyChange

    }//GEN-LAST:event_formPropertyChange

    private void formComponentResized(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentResized
    {//GEN-HEADEREND:event_formComponentResized
        atualizar();
    }//GEN-LAST:event_formComponentResized

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarJButtonActionPerformed
    {//GEN-HEADEREND:event_cancelarJButtonActionPerformed
        fechar();
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void concluirJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_concluirJButtonActionPerformed
    {//GEN-HEADEREND:event_concluirJButtonActionPerformed
        concluir();
    }//GEN-LAST:event_concluirJButtonActionPerformed

    private void senhaAtualJPasswordFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_senhaAtualJPasswordFieldActionPerformed
    {//GEN-HEADEREND:event_senhaAtualJPasswordFieldActionPerformed
        senhaNovaJPasswordField.requestFocus();
    }//GEN-LAST:event_senhaAtualJPasswordFieldActionPerformed

    private void senhaNovaJPasswordFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_senhaNovaJPasswordFieldActionPerformed
    {//GEN-HEADEREND:event_senhaNovaJPasswordFieldActionPerformed
        senhaNovaConfirmarJPasswordField.requestFocus();
    }//GEN-LAST:event_senhaNovaJPasswordFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( UsuarioAlterarSenhaVissao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( UsuarioAlterarSenhaVissao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( UsuarioAlterarSenhaVissao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( UsuarioAlterarSenhaVissao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new UsuarioAlterarSenhaVissao().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerJLabel;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JButton concluirJButton;
    private javax.swing.JPanel head;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel logoJLabel;
    private javax.swing.JPanel principaljPanel;
    private javax.swing.JLabel senhaAntigaJLabel;
    private javax.swing.JPasswordField senhaAtualJPasswordField;
    private javax.swing.JPasswordField senhaNovaConfirmarJPasswordField;
    private javax.swing.JLabel senhaNovaJLabel;
    private javax.swing.JPasswordField senhaNovaJPasswordField;
    private javax.swing.JLabel senhaNovaRepetirJLabel;
    private javax.swing.JLabel usuarioJLabel;
    private javax.swing.JTextField usuarioJTextField;
    // End of variables declaration//GEN-END:variables

    private void postInitComponents()
    {
        DocumentListener documentListener = new DocumentListener()
        {
            @Override
            public void insertUpdate( DocumentEvent e )
            {
                atualizarFormulario();
            }

            @Override
            public void removeUpdate( DocumentEvent e )
            {
                atualizarFormulario();
            }

            @Override
            public void changedUpdate( DocumentEvent e )
            {
            }

        };
        senhaAtualJPasswordField.getDocument().addDocumentListener( documentListener );
        senhaNovaJPasswordField.getDocument().addDocumentListener( documentListener );
        senhaNovaConfirmarJPasswordField.getDocument().addDocumentListener( documentListener );

        resizeJLableIcon( ( getWidth() / 5 ), 100, getClass().getResource( "/imagens/img32x32/_logo.png" ), logoJLabel );
        resizeJLableIcon( ( ( getWidth() / 5 ) * 4 ), 100, getClass().getResource( "/imagens/img32x32/_banner.png" ), bannerJLabel );

        resizeJLableIcon( 40, 40, getClass().getResource( "/imagens/img32x32/_user.png" ), usuarioJLabel );
        resizeJLableIcon( 40, 40, getClass().getResource( "/imagens/img32x32/_pass.png" ), senhaAntigaJLabel );
        resizeJLableIcon( 40, 40, getClass().getResource( "/imagens/img32x32/_pass.png" ), senhaNovaJLabel );
        resizeJLableIcon( 40, 40, getClass().getResource( "/imagens/img32x32/_pass.png" ), senhaNovaRepetirJLabel );

        int tamanho = 20;

        resizeJButtonIcon( tamanho, tamanho, getClass().getResource( "/imagens/img32x32/_cancel.png" ), cancelarJButton );
        resizeJButtonIcon( tamanho, tamanho, getClass().getResource( "/imagens/img32x32/_ok.png" ), concluirJButton );
        concluirJButton.setVisible( false );
    }

    private void atualizar()
    {
        postInitComponents();
    }

    private void fechar()
    {
        MetodosUtil.fechar_todas_janelas();
        new LoginVisao( new BDConexao() );
    }

    private void atualizarFormulario()
    {
        concluirJButton.setVisible( senhaValida() );
    }

    private void concluir()
    {
        if ( senhaValida() )
        {
            try
            {
                String senha = new String( senhaNovaJPasswordField.getPassword() );
                String encriptedPass = usuarioDao.encriptPass( senha );

                tbUsuario.setSenha( encriptedPass );
                tbUsuario.setDataUltimoAcesso( new Date() );

                usuarioDao.edit( tbUsuario );
                JOptionPane.showMessageDialog( null, "Os dados foram salvos!" );
                fechar();
            }
            catch ( NonexistentEntityException ex )
            {
                Logger.getLogger( UsuarioAlterarSenhaVissao1.class.getName() ).log( Level.SEVERE, null, ex );
            }
            catch ( Exception ex )
            {
                Logger.getLogger( UsuarioAlterarSenhaVissao1.class.getName() ).log( Level.SEVERE, null, ex );
            }
        }
    }

    private boolean senhaValida()
    {
        String senhaAtual = new String( senhaAtualJPasswordField.getPassword() );
        String senhaNova = new String( senhaNovaJPasswordField.getPassword() );
        String senhaNovaConfirmar = new String( senhaNovaConfirmarJPasswordField.getPassword() );
        String senhaNovaEncripted = usuarioDao.encriptPass( senhaNova );
        String encriptedAtualPass = usuarioDao.encriptPass( senhaAtual );

        boolean senhaAtualCorreta = ( tbUsuario.getSenha().compareTo( encriptedAtualPass ) == 0 );
        boolean senhaNovaDiferenteAntiga = ( tbUsuario.getSenha().compareTo( senhaNovaEncripted ) != 0 );
        boolean senhaNovaNaoVazia = !senhaNova.isEmpty();
        boolean senhaNovaConfirmarNaoVazia = !senhaNovaConfirmar.isEmpty();
        boolean senhaNovaConfirmadaComSucesso = senhaNova.compareTo( senhaNovaConfirmar ) == 0 && senhaNovaConfirmarNaoVazia;
//

        if ( senhaAtualCorreta )
        {
            System.err.println( "1 senhaAtualCorreta" );
        }
        System.err.println( "Senha usuario:\n " + tbUsuario.getSenha() );
        System.err.println( "encriptedAtualPass:\n " + encriptedAtualPass );
        if ( senhaNovaDiferenteAntiga )
        {
            System.err.println( "2 senhaNovaDiferenteAntiga" );
        }
        if ( senhaNovaNaoVazia )
        {
            System.err.println( "3 senhaNovaNaoVazia" );
        }
        if ( senhaNovaConfirmarNaoVazia )
        {
            System.err.println( "4 senhaNovaConfirmarNaoVazia" );
        }
        if ( senhaNovaConfirmadaComSucesso )
        {
            System.err.println( "5 senhaNovaConfirmadaComSucesso" );
        }
        return senhaNovaDiferenteAntiga && senhaNovaNaoVazia && senhaNovaConfirmarNaoVazia && senhaNovaConfirmadaComSucesso && senhaAtualCorreta;
    }
}
