/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.mysql.jdbc.Connection;
import comercial.controller.StatusController;
import comercial.controller.UsuariosController;
import controller.UsuarioController;
import entity.TbStatus;
import entity.TbUsuario;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import modelo.UsuarioModelo;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
import util.BDConexao;
import util.MetodosUtil;

/**
 *
 * @author Domingos Dala Vunge
 */
public class UsuarioVisao extends javax.swing.JFrame
{

    /**
     * Creates new form UsuarioVisao
     */
    private UsuarioModelo usuarioModelo;
    private static TbUsuario usuario;
    private static BDConexao conexao, conexaoTransaction;
//    private BDConexao conexao;
    private static UsuariosController usuariosController;
    private static StatusController statusController;
    private Frame parent;
    private int codigo = 0;

    public UsuarioVisao( java.awt.Frame parent, boolean modal, BDConexao conexao )
    {
        //this.parent =  parent1;

//        super ( parent, modal );
        this.parent = parent;

        initComponents();
        confLabel();
        setLocationRelativeTo( null );

        usuarioModelo = new UsuarioModelo();
        this.conexao = conexao;
        usuariosController = new UsuariosController( conexao );
        statusController = new StatusController( conexao );

        cmbTipoUsuario.setModel( new DefaultComboBoxModel( conexao.getElementos( "tb_tipo_usuario", "descricao", false ) ) );

        txtInicias.addKeyListener( new TratarEventoTeclado() );
        inicilizarComponentes();

        btnAlterar.setVisible( false );
        btnEliminar.setVisible( false );

    }

    public int getIdTipoUsuario() throws SQLException
    {
        return BDConexao.getCodigoTipousuario( String.valueOf( cmbTipoUsuario.getSelectedItem() ) );
    }

    public void confLabel()
    {

        lbNome.setHorizontalAlignment( JLabel.RIGHT );

        lbUserName.setHorizontalAlignment( JLabel.RIGHT );
        lbDataNascimento.setHorizontalAlignment( JLabel.RIGHT );
        lbTelefone.setHorizontalAlignment( JLabel.RIGHT );
        lbEmail.setHorizontalAlignment( JLabel.RIGHT );
        lbEndereco.setHorizontalAlignment( JLabel.RIGHT );
        lbStatus.setHorizontalAlignment( JLabel.RIGHT );
        lbSexo.setHorizontalAlignment( JLabel.RIGHT );
        lbNomes.setHorizontalAlignment( JLabel.RIGHT );
        lbInicaisNome1.setHorizontalAlignment( JLabel.RIGHT );
        lbTipoUsuario.setHorizontalAlignment( JLabel.RIGHT );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        lbNomes = new javax.swing.JLabel();
        txtInicias = new javax.swing.JTextField();
        cmbNome = new javax.swing.JComboBox();
        lbInicaisNome1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbDataNascimento = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox();
        chDatanascimneto = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        lbUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox();
        lbTipoUsuario = new javax.swing.JLabel();
        cmbTipoUsuario = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("...:::::  KITANDA -  CADASTRO DE USUÁRIOS ::::...");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button  Salvar-.png"))); // NOI18N
        btnSalvar.setAlignmentX(0.5F);
        btnSalvar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button-Alterar.png"))); // NOI18N
        btnAlterar.setAlignmentX(0.5F);
        btnAlterar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAlterarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button-Eliminar.png"))); // NOI18N
        btnEliminar.setAlignmentX(0.5F);
        btnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/button-Cancelar.png"))); // NOI18N
        btnCancelar.setAlignmentX(0.5F);
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CASDASTRO USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 15), new java.awt.Color(51, 153, 0))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N

        jTabbedPane1.setForeground(new java.awt.Color(51, 153, 0));
        jTabbedPane1.setFont(new java.awt.Font("Showcard Gothic", 0, 13)); // NOI18N

        lbNomes.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbNomes.setText("Nomes:");

        txtInicias.setBackground(new java.awt.Color(51, 153, 0));
        txtInicias.setForeground(new java.awt.Color(255, 255, 255));
        txtInicias.setCaretColor(new java.awt.Color(255, 255, 255));
        txtInicias.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIniciasActionPerformed(evt);
            }
        });

        cmbNome.setBackground(new java.awt.Color(51, 153, 0));
        cmbNome.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cmbNome.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbNomeActionPerformed(evt);
            }
        });

        lbInicaisNome1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbInicaisNome1.setText("Inicias Nome:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNomes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInicaisNome1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbNome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtInicias, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInicias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInicaisNome1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomes))
                .addGap(93, 93, 93))
        );

        jTabbedPane1.addTab("PROUCURA", jPanel5);

        txtNome.setBackground(new java.awt.Color(51, 153, 0));
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setCaretColor(new java.awt.Color(255, 255, 255));

        lbNome.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbNome.setText("Nome:");

        lbDataNascimento.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbDataNascimento.setText("Data Nascimento:");

        lbTelefone.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbTelefone.setText("Telefone:");

        txtTelefone.setBackground(new java.awt.Color(51, 153, 0));
        txtTelefone.setForeground(new java.awt.Color(255, 255, 255));

        lbEmail.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbEmail.setText("Email:");

        lbEndereco.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbEndereco.setText("Endereco:");

        txtEmail.setBackground(new java.awt.Color(51, 153, 0));
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));

        txtEndereco.setBackground(new java.awt.Color(51, 153, 0));
        txtEndereco.setForeground(new java.awt.Color(255, 255, 255));

        lbSexo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbSexo.setText("Sexo:");

        cmbSexo.setBackground(new java.awt.Color(51, 153, 0));
        cmbSexo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(cmbSexo, 0, 182, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtEndereco))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(lbDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(txtTelefone)
                            .addComponent(txtEmail)
                            .addComponent(chDatanascimneto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDataNascimento)
                    .addComponent(chDatanascimneto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEndereco)
                    .addComponent(lbEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("Dados Pessoais", jPanel4);

        lbUserName.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbUserName.setText("*User Name:");

        txtUserName.setBackground(new java.awt.Color(51, 153, 0));
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("DADOS OBRIGATORIOs!....");

        lbStatus.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbStatus.setText("*Status:");

        cmbStatus.setBackground(new java.awt.Color(51, 153, 0));
        cmbStatus.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Desactivo" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbStatusActionPerformed(evt);
            }
        });

        lbTipoUsuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbTipoUsuario.setText("*Tipo Usuario:");

        cmbTipoUsuario.setBackground(new java.awt.Color(51, 153, 0));
        cmbTipoUsuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTipoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        jTabbedPane1.addTab("Outros Dados", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        operacao( 1, "SALVOS", "SALVAR" );


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
//        operacao( 2, "ALTERADO", "ALTERAR" );

        procedimento_alterar_usuario();

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void procedimento_alterar_usuario()
    {
        System.out.println( "ID_SATUS: "+getIdStatus() );
        System.out.println( "NOME: "+txtNome.getText() );
        TbUsuario usuarioLocal = new TbUsuario();

        usuarioLocal.setIdStatus( new TbStatus( getIdStatus() ) );;

        if ( new UsuariosController(conexao).actualizar( usuarioLocal ) )
        {
            JOptionPane.showMessageDialog( null, "Status Actualizado com Sucesso!..." );
        }
        else
        {
            JOptionPane.showMessageDialog( null, "Falha ao actualizar o Status!...", "ERRO", JOptionPane.ERROR_MESSAGE );
        }

    }

//    private void preparar_usuario()
//    {
//
//        usuario.setIdStatus( new TbStatus( getIdStatus() ) );
//
//    }

    private int getIdStatus()
    {
        try
        {
            return statusController
                    .getSatusByDesignacao( cmbStatus.getSelectedItem().toString() )
                    .getIdStatus();
        }
        catch ( Exception e )
        {
        }
        return 0;
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int resposta = JOptionPane.showConfirmDialog( null, "TENS A CERTEZA QUE PRETENDES ELIMINAR ESTE O USUARIO: " + getNome() );

        if ( resposta == JOptionPane.YES_OPTION )
        {
            operacao( 3, "ELIMNADO", "ELIMINAR" );
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNomeActionPerformed
        // TODO add your handling code here:
        ver_dados();
    }//GEN-LAST:event_cmbNomeActionPerformed

    private void txtIniciasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtIniciasActionPerformed
    {//GEN-HEADEREND:event_txtIniciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIniciasActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbStatusActionPerformed
    {//GEN-HEADEREND:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Windows".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( UsuarioVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( UsuarioVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( UsuarioVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( UsuarioVisao.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                UsuarioVisao dialog = new UsuarioVisao( new javax.swing.JFrame(), true, new BDConexao() );
                dialog.addWindowListener( new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing( java.awt.event.WindowEvent e )
                    {
                        System.exit( 0 );
                    }
                } );
                dialog.setVisible( true );
            }
        } );
    }

    /* CRIACAO DO GETS  */
    public String getNome()
    {
        return txtNome.getText();
    }

    /*
     *   lbNome.setHorizontalAlignment(JLabel.RIGHT);
     lbSobreNome.setHorizontalAlignment(JLabel.RIGHT);
     lbUserName.setHorizontalAlignment(JLabel.RIGHT);
     lbSenha.setHorizontalAlignment(JLabel.RIGHT);
     lbConfirSenha.setHorizontalAlignment(JLabel.RIGHT);
     lbDataNascimento.setHorizontalAlignment(JLabel.RIGHT);
     lbTelefone.setHorizontalAlignment(JLabel.RIGHT);
     lbEmail.setHorizontalAlignment(JLabel.RIGHT);
     lbEndereco.setHorizontalAlignment(JLabel.RIGHT);
     
     
     */
    public String getUserName()
    {
        return txtUserName.getText();
    }

    public String getStatus()
    {
        return String.valueOf( cmbStatus.getSelectedItem() );
    }

    public String getDataNascimento()
    {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime( chDatanascimneto.getDate() );

        String dataSelecionada = gc.get( GregorianCalendar.YEAR ) + "-"
                + ( gc.get( GregorianCalendar.MONTH ) + 1 ) + "-"
                + gc.get( GregorianCalendar.DATE );
        return dataSelecionada;
    }

    public String getTelefone()
    {
        return txtTelefone.getText();
    }

    public String getEmail()
    {
        return txtEmail.getText();
    }

    public String getEndereco()
    {
        return txtEndereco.getText();
    }

    /*VALIDACOES */
    public int getSexo()
    {
        if ( cmbSexo.getSelectedItem().equals( "Masculino" ) )
        {
            return 1;
        }
        else
        {
            return 2;
        }
    }

    public void limpar()
    {

        txtNome.setText( "" );
        txtInicias.setText( "" );
        txtUserName.setText( "" );
        txtEmail.setText( "" );
        txtTelefone.setText( "" );
        txtEndereco.setText( "" );
        cmbSexo.setSelectedIndex( -1 );
        cmbStatus.setSelectedIndex( -1 );
        cmbNome.setSelectedIndex( -1 );

    }

    public boolean campos_invalidos()
    {
        Color backGround = Color.WHITE;
        Color foreGround = Color.BLACK;
        Color caretColor = Color.BLACK;

        if ( getNome().equals( "" ) )
        {
            txtNome.setBackground( backGround );
            txtNome.setForeground( foreGround );
            txtNome.setCaretColor( caretColor );
            JOptionPane.showMessageDialog( null, "Pf. Preêncha o campo Nome: " );
            return true;
        }
        else if ( getTelefone().equals( "" ) )
        {

            txtTelefone.setBackground( backGround );
            txtTelefone.setForeground( foreGround );
            txtTelefone.setCaretColor( caretColor );
            JOptionPane.showMessageDialog( null, "Pf. Preêncha o Campo Sobre Telefone: " );
            return true;
        }
        else if ( getEmail().equals( "" ) )
        {

            txtEmail.setBackground( backGround );
            txtEmail.setForeground( foreGround );
            txtEmail.setCaretColor( caretColor );
            JOptionPane.showMessageDialog( null, "Pf. Preêncha o Campo Sobre Email: " );
            return true;

        }
        else if ( getUserName().equals( "" ) )
        {

            txtUserName.setBackground( backGround );
            txtUserName.setForeground( foreGround );
            txtUserName.setCaretColor( caretColor );
            JOptionPane.showMessageDialog( null, "Pf. Preêncha o Campo Sobre UserName: " );
            return true;

        }

        return false;
    }

    public void operacao( int operacao, String descricaoCerto, String descricaoErro )
    {
        try
        {
            String novaSenha = novaSenha();

            //int codigo_sexo, int idTipousuario, String nome ,String senha, String status, String dataNascimento, String telefone, String email, String endereco, String userName
            usuarioModelo = new UsuarioModelo( codigo, getSexo(), getIdTipoUsuario(), getNome(),
                    novaSenha,
                    getStatus(),
                    getDataNascimento(),
                    getTelefone(),
                    getEmail(),
                    getEndereco(),
                    getUserName()
            );

            TbUsuario tbUsuario = null;

            if ( operacao != 3 )
            {
                if ( !campos_invalidos() )
                {
                    tbUsuario = usuariosController.createNewUsuarioInstance( operacao, usuarioModelo );
                    System.err.println( "tbUsuario: " + tbUsuario );
                    if ( tbUsuario != null )
                    {
                        JOptionPane.showMessageDialog( null, "DADOS   " + descricaoCerto + " COM SUCESSO NA BD!..." );
                        limpar();
                    }
                    else
                    {
                        System.err.println( "#1 operacao != 3 tbUsuario: " + tbUsuario );
                        JOptionPane.showMessageDialog( null, "ERRO AO " + descricaoErro + "NA BD!...", "ERRO", JOptionPane.ERROR_MESSAGE );
                    }

                }
            }
            else
            {
                if ( usuariosController.operacao( operacao, usuarioModelo ) )
                {
                    JOptionPane.showMessageDialog( null, "DADOS   " + descricaoCerto + " COM SUCESSO NA BD!..." );
                    limpar();
                }
                else
                {
                    System.err.println( "#1 else tbUsuario: " + tbUsuario );
                    JOptionPane.showMessageDialog( null, "ERRO AO " + descricaoErro + "NA BD!...", "ERRO", JOptionPane.ERROR_MESSAGE );
                }
            }

            revelarSenha( tbUsuario.getCodigo(), novaSenha );
        }
        catch ( SQLException ex )
        {
            Logger.getLogger( UsuarioVisao.class.getName() ).log( Level.SEVERE, null, ex );
        }

    }

    /**
     * @return the usuarioModelo
     */
    public void atualizarDadosDaConta()
    {
        String text = txtNome.getText();

        if ( !text.isEmpty() )
        {
//Caso o utilizador já exista            TbUsuario usuarioByNome = new UsuarioDao (em).getUsuarioByNome ( text );
            String[] listaDePalavras = MetodosUtil.listarPalavras( text );

            String primeira = listaDePalavras[ 0 ];
            String ultima = ( listaDePalavras.length > 1 ) ? listaDePalavras[ listaDePalavras.length - 1 ] : "";

            System.err.println( "primeira: " + primeira );
            System.err.println( "ultima: " + ultima );
            ultima = ( ultima.equals( "" ) ) ? "user" : ultima;
            txtUserName.setText( primeira.toLowerCase() + "." + ultima.toLowerCase() );
        }
    }

    private void inicilizarComponentes()
    {
        txtNome.getDocument().addDocumentListener( new DocumentListener()
        {

            @Override
            public void insertUpdate( DocumentEvent e )
            {
                atualizarDadosDaConta();
            }

            @Override
            public void removeUpdate( DocumentEvent e )
            {
                atualizarDadosDaConta();
            }

            @Override
            public void changedUpdate( DocumentEvent e )
            {

            }
        } );
    }

    private String novaSenha()
    {
        String nome = txtNome.getText();
        String primeiroNome = MetodosUtil.listarPalavras( nome )[ 0 ];
        String ultimoNome = "";

        try
        {
            ultimoNome = MetodosUtil.listarPalavras( nome )[ 1 ];

        }
        catch ( Exception e )
        {
            ultimoNome = "user";
        }

        String ano = new SimpleDateFormat( "yy" ).format( chDatanascimneto.getDate() );
//        String mes = new SimpleDateFormat( "MMM" ).format( chDatanascimneto.getDate() );
//        String dia = new SimpleDateFormat( "dd" ).format( chDatanascimneto.getDate() );

        return String.format( "%s%s%s", primeiroNome.toUpperCase(), ".", ultimoNome.toUpperCase() );
//        return String.format( "%s%s%s%s%s", ano, primeiroNome.toUpperCase(), mes, ultimoNome.toUpperCase(), dia );
    }

    private void revelarSenha( int codigoUtilizador, String novasenha )
    {
//        BDConexao conexao = new BDConexao();

        Connection connection = ( Connection ) conexao.conectar();
        HashMap hashMap = new HashMap();
        String relatorio = "";
        relatorio = "relatorios/credenciais.jasper";
        System.err.println( "codigoUtilizador: " + codigoUtilizador );
        hashMap.put( "_UTILIZADOR", codigoUtilizador );
        hashMap.put( "_SENHA_DESINCRIPTADA", novasenha );

        File file = new File( relatorio ).getAbsoluteFile();
        String obterCaminho = file.getAbsolutePath();

        try
        {

            JasperFillManager.fillReport( obterCaminho, hashMap, connection );

            JasperPrint jasperPrint = JasperFillManager.fillReport( obterCaminho, hashMap, connection );

            if ( jasperPrint.getPages().size() >= 1 )
            {
                JasperViewer jasperViewer = new JasperViewer( jasperPrint, false );

                jasperViewer.setVisible( true );
            }
            else
            {
                JOptionPane.showMessageDialog( null, "Nao Existem Usuarios Para essa Listagen!..." );
            }
        }
        catch ( JRException jex )
        {
            jex.printStackTrace();
            //System.out.println("aqui");
            JOptionPane.showMessageDialog( null, "FALHA AO TENTAR MOSTRAR OS USUARIOS!..." );
        }
        catch ( Exception ex )
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog( null, "ERRO AO TENTAR OS USUARIOS!..." );
        }
    }

    //CLASSE EVENTO TECLADO 
    //----------- evento do teclado ---------------------------------------
    class TratarEventoTeclado implements KeyListener
    {

        String prefixo = "";

        public void keyPressed( KeyEvent evt )
        {

            UsuarioModelo usuario = new UsuarioModelo();

            if ( evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_ENTER )
            {
                char key = evt.getKeyChar();
                prefixo = txtInicias.getText().trim() + key;

                cmbNome.setModel( new DefaultComboBoxModel( conexao.getElementosLike( "tb_usuario", "nome", prefixo ) ) );

                try
                {
                    codigo = usuariosController.getCodigo( String.valueOf( cmbNome.getSelectedItem() ) );
                    usuario = usuariosController.getUsuario( codigo );

                    txtNome.setText( usuario.getNome() );
                    //chDatanascimneto.setDate
                    //chDatanascimneto.setDateFormatString(usuario.getDataNascimento());
                    txtUserName.setText( usuario.getUserName() );
                    txtTelefone.setText( usuario.getTelefone() );
                    txtEmail.setText( usuario.getEmail() );
                    txtEndereco.setText( usuario.getEndereco() );
                    cmbSexo.setSelectedIndex( usuario.getCodigo_sexo() - 1 );
                    cmbStatus.setSelectedItem( String.valueOf( usuario.getStatus() ) );
                    btnSalvar.setVisible( false );
                    btnAlterar.setVisible( true );
                    btnEliminar.setVisible( true );
                    String data = String.valueOf( usuario.getDataNascimento() );

                    //2012-06-26
                    int dia = Integer.parseInt( data.substring( 8, 10 ) );;
                    int mes = Integer.parseInt( data.substring( 5, 7 ) );;
                    int ano = Integer.parseInt( data.substring( 0, 4 ) );

                    chDatanascimneto.setDate( new Date( ano - 1900, mes - 1, dia ) );

                    System.err.println( "TIPO USUARIO  " + String.valueOf( BDConexao.getDescrisoTipoUsuarioByCodigo( usuario.getIdTipousuario() ) ) );

                    cmbTipoUsuario.setSelectedItem( String.valueOf( BDConexao.getDescrisoTipoUsuarioByCodigo( usuario.getIdTipousuario() ) ) );
                }
                catch ( Exception ex )
                {
                    Logger.getLogger( UsuarioVisao.class.getName() ).log( Level.SEVERE, null, ex );
                }
            }
        }

        public void keyReleased( KeyEvent evt )
        {
        }

        public void keyTyped( KeyEvent evt )
        {
        }
    }

    private void ver_dados()
    {
        UsuarioModelo usuario = new UsuarioModelo();

        try
        {
            codigo = usuariosController.getCodigo( String.valueOf( cmbNome.getSelectedItem() ) );
            usuario = usuariosController.getUsuario( codigo );
        }
        catch ( SQLException ex )
        {
            Logger.getLogger( UsuarioVisao.class.getName() ).log( Level.SEVERE, null, ex );
        }
        if ( usuario.getCodigo() > 0 )
        {

            System.err.println( "usuario.getCodigo (): " + usuario.getCodigo() );
            System.err.println( "usuario.getDataNascimento (): " + usuario.getDataNascimento() );
            txtNome.setText( usuario.getNome() );
            //chDatanascimneto.setDate
            //chDatanascimneto.setDateFormatString(usuario.getDataNascimento());
            txtUserName.setText( usuario.getUserName() );
            txtTelefone.setText( usuario.getTelefone() );
            txtEmail.setText( usuario.getEmail() );
            txtEndereco.setText( usuario.getEndereco() );
            cmbSexo.setSelectedIndex( usuario.getCodigo_sexo() - 1 );
            cmbStatus.setSelectedItem( String.valueOf( usuario.getStatus() ) );

            String data = String.valueOf( usuario.getDataNascimento() );

            //2012-06-26
            int dia = Integer.parseInt( data.substring( 8, 10 ) );;
            int mes = Integer.parseInt( data.substring( 5, 7 ) );;
            int ano = Integer.parseInt( data.substring( 0, 4 ) );

            chDatanascimneto.setDate( new Date( ano - 1900, mes - 1, dia ) );

            System.err.println( "TIPO USUARIO  " + String.valueOf( BDConexao.getDescrisoTipoUsuarioByCodigo( usuario.getIdTipousuario() ) ) );

            cmbTipoUsuario.setSelectedItem( String.valueOf( BDConexao.getDescrisoTipoUsuarioByCodigo( usuario.getIdTipousuario() ) ) );
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalvar;
    private com.toedter.calendar.JDateChooser chDatanascimneto;
    private javax.swing.JComboBox cmbNome;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JComboBox cmbTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbDataNascimento;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbInicaisNome1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomes;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbTipoUsuario;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtInicias;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

}
